### ISSUE TITLE
Criar ícone com a ordem original do barramento

### ISSUE THREAD

**Issue by fe-neto** [pengovbr/mod-sei-pen#136]
O reordenamento dos documentos na árvore do processo frequentemente inviabiliza a devolução via barramento. Poderia ser criado um botão “Retornar à ordem original”.Outra possibilidade é apresentar de forma mais visual quais documentos foram reordenados (colocando um número de ordem na frente, p.e.). Terceira opção seria criar um novo botão com a listagem correta

**Comment by caduvieira** [comment]
Duplicada #261
