### ISSUE TITLE
Criar críticas para impedir Desativar ou Excluir Tipos de Documentos, Tipos de Processos e Unidades utilizados na Administração do Módulo PEN

### ISSUE THREAD

**Issue by neijobson** [pengovbr/mod-sei-pen#153]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
O módulo não está utilizando eventos de bloqueio da API de módulos para impedir Desativações e Exclusões de Tipos de Documentos, Tipos de Processos e Unidades ~~Hipóteses Legais de Restrição de Acesso~~ utilizadas nas diversas telas de Administração do Módulo PEN o que gera erros no uso do módulo com mapeamentos feitos com registros Desativados que na prática dá erros que são difíceis de descobrir.

-----

**Descreva a solução que você gostaria**
O módulo PEN tem que implementar mensagens de crítica utilizando eventos de bloqueio da API de módulos para impedir Desativar ou Excluir Tipos de Documentos, Tipos de Processos, Unidades e Hipóteses Legais de Restrição de Acesso utilizadas nas diversas telas de Administração do Módulo PEN.

Desativar:
- [x] Tipos de Documentos
- [x] Tipos de Processos
- [x] Unidades
~~- [ ] Hipóteses Legais de Restrição de Acesso~~

Excluir:
- [x] Tipos de Documentos
- [x] Tipos de Processos
- [x] Unidades
~~- [ ] Hipóteses Legais de Restrição de Acesso~~

**Comment by euviniciusmendonca** [comment]
@higodf @caduvieira  @guilhermeadc Após implantar a branch nos ambientes super5 e super6, eu consegui excluir normalmente o tipo de processo mapeado na tela Parâmetros de Configuração do Módulo de Tramitações PEN.

**Comment by davidnascimento1618** [comment]
@michael-ferreira2022, o sistema está permitindo a exclusão ou desativação de um tipo de processo no qual foi mapeado em: 'Parâmetros de Configuração', através do _combobox_ 'Tipo de Documento Externo', conforme é exemplificado no _.gif_ abaixo:

![Sistema está permitindo excluir ou desativar um tipo de processo mapeado](https://github.com/supergovbr/mod-sei-pen/assets/87980947/dd811acb-8efd-4473-8865-6bdc764a1165)

**Comment by davidnascimento1618** [comment]
@michael-ferreira2022, conforme visto na agenda de hoje à tarde, falta realizar o tratamento na mensagem de erro, quando se tenta realizar uma exclusão de uma hipótese legal que esteja vinculada no mapeamento (do lado do SEI), tanto para o envio como para o recebimento. Abaixo segue um _.gif_ evidenciando o problema:

![Mensagem de erro sem tratamento ao tentar exluir uma hipotese legal mapeada do lado do SEI](https://github.com/supergovbr/mod-sei-pen/assets/87980947/a4bdae8a-c0b7-4aee-8244-9aadea81a035)

**Comment by michael-ferreira2022** [comment]
@davidnascimento1618 esta tarefa depende da https://github.com/supergovbr/super/pull/280. Para tratar a exceção no módulo existem métodos no SeiIntegração.php que são usados para este fim, porém não existiam estes métodos para alguns casos como hipótese legal e foi necessário sua criação para o correto tratamento da exceção.

**Comment by davidnascimento1618** [comment]
@michael-ferreira2022, após novos testes, foi verificado que o sistema não está mais permitindo a exclusão ou desativação de 'Hipóteses Legais' que não estejam mapeadas, conforme é exemplificado na evidência abaixo:

https://github.com/supergovbr/mod-sei-pen/assets/87980947/47530074-98a7-47ef-b49f-97999f7c7c96

**Comment by davidnascimento1618** [comment]
@michael-ferreira2022, o sistema está permitindo a exclusão ou desativação de um tipo de processo no qual foi mapeado em: 'Parâmetros de Configuração', através do _combobox_ 'Tipo de Processo Externo', conforme é exemplificado no _.gif_ abaixo:

![Sistema está permitindo a exclusão ou desativação de um tipo de processo no qual foi mapeado em: 'Parâmetros de Configuração'](https://github.com/supergovbr/mod-sei-pen/assets/87980947/ca08c844-582b-46fe-a4c3-813c13bc3275)

**Comment by michael-ferreira2022** [comment]
@davidnascimento1618 para a exclusão do tipo de processo ser bloqueada você deve ter feito um tramite para outra unidade, havendo um tramite realizado  a tentativa de exclusão ou desativação ele não permitirá a ação.

**Comment by davidnascimento1618** [comment]
> @davidnascimento1618 para a exclusão do tipo de processo ser bloqueada você deve ter feito um tramite para outra unidade, havendo um tramite e realizando a tentativa de exclusão ou desativação ele não permitirá a ação.

O sistema não deveria realizar essa validação da exclusão ou desativação, de um tipo de processo, se baseando apenas se há vínculo ou não com algum processo, mas, também, deveria verificar se existe mapeamento deste tipo de processo na tabela de 'Parâmetros de Configuração do Módulo de Tramitações PEN', pois isto, evitaria que o usuário refizesse as configurações do módulo de tramitações, uma vez que 'Tipo de Processo Externo' é um campo obrigatório.

**Comment by neijobson** [comment]
@michael-ferreira2022 e @davidnascimento1618 
Se a vinculação do Tipo de Processo do core do SEI com a tabela do módulo for por FK, isoladamente só em parametrizar o tipo de processo já deveria impedir excluir o Tipo de Processo (que é físico no banco), dando estouro de tela SE não ativarem o evento de bloqueio para não deixar excluir o tipo de processo. O evento de bloqueio evita estouro de tela (que é feio) e ainda indica o motivo porque não deixou excluir.
Se não deu estouro de tela no teste do GIF acima, então sinaliza que no módulo o relacionamento do tipo de processo com a parametrização na Administração não foi forte (FK), o que deve ser revisado, pois a boa prática deveria ser uso de FK para relacionamento forte.

O desativar idem. Por si só, no uso do core do SEI normal, deixaria desativar o Tipo de Processo sem qualquer crítica. Mas se o tipo de processo em questão tiver sido parametrizado na Administração do módulo PEN e deixarem desativar ele, vai dar erro no módulo porque o core do SEI não vai deixar utilizar o tipo de processo em questão. Daí, o evento de bloqueio para não deixar desativar o tipo de processo é necessário para evitar problemas.

**Comment by davidnascimento1618** [comment]
Prezado, @michael-ferreira2022, foi verificado que o [item 1](https://github.com/pengovbr/mod-sei-pen/issues/153#issuecomment-1661065480-1) não foi corrigido.

Com relação ao [item 2](https://github.com/pengovbr/mod-sei-pen/issues/153#issuecomment-1661065480-2), nota-se que a mensagem de desativação de tipo de processo não está conforme o padrão, ou seja, a descrição da mensagem está divergente da que é exibida ao tentar excluir qualquer tipo de processo que já esteja vinculado a um processo, conforme é exemplificado no _.gif_ abaixo:

![Mensagem de desativação de tipo de processo não está conforme o padrão](https://github.com/pengovbr/mod-sei-pen/assets/87980947/e3398d2b-f49c-40c4-b4fb-581c99d45900)

**Comment by caduvieira** [comment]
O caso de hipótese legal deve ser movida para outra issue visto que não tem ponto de extensão para hipótese legal. @davidnascimento1618 favor separar essa issue em duas.

@michael-ferreira2022 remover do pr o código correspondente

**Comment by davidnascimento1618** [comment]
Issue #348 criada para tratar apenas da entidade 'Hipóteses Legais' e, seus respectivos mapeamentos (envio, recebimento e hipótese de restrição padrão).

**Comment by davidnascimento1618** [comment]
Prezado @michael-ferreira2022, favor corrigir os itens descritos no comentário [supracitado](https://github.com/pengovbr/mod-sei-pen/issues/153#issuecomment-1672064097), com exceção do [item 1](https://github.com/pengovbr/mod-sei-pen/issues/153#issuecomment-1661065480-1), que será tratado na _issue_ #348.

**Comment by davidnascimento1618** [comment]
@michael-ferreira2022, corrigir os conflitos mencionados [aqui](https://github.com/pengovbr/mod-sei-pen/pull/284#pullrequestreview-1627772326), assim como esse trecho de código [aqui](https://github.com/pengovbr/mod-sei-pen/pull/284#discussion_r1326529781)

**Comment by davidnascimento1618** [comment]
Prezados, favor corrigir os dois itens descritos no comentário [supracitado](https://github.com/pengovbr/mod-sei-pen/issues/153#issuecomment-1672064097), com exceção do [item 1](https://github.com/pengovbr/mod-sei-pen/issues/153#issuecomment-1661065480-1), que será tratado na _issue_ #348.

Tratar também este [ponto](https://github.com/pengovbr/mod-sei-pen/pull/284#pullrequestreview-1704702941).

**Comment by marvdias** [comment]
Testes funcionais do sei oficial

https://github.com/pengovbr/mod-sei-pen/assets/31357298/f821b3e9-327f-4b90-aa49-87ff6c634d21

Testes funcionais do sei4

https://github.com/pengovbr/mod-sei-pen/assets/31357298/6bd039b0-b66c-4ba3-a804-a010e1c18361

**Comment by marvdias** [comment]
Testes funcionais do sei3

https://github.com/pengovbr/mod-sei-pen/assets/31357298/92044b37-d963-4f19-bc39-3ecdc3dd2aa3

**Comment by sergioadao** [comment]
@marvdias e @mateussbh...Campo Tipo de Processo Externo não visível na tela de parametrização. Utilizada PR 431...segue evidência:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/0d040d23-e986-46df-b881-f9710176b02f

**Comment by mateussbh** [comment]
Prezado, favor criar novo PR, baseado na branch release 3.6.0, tendo em vista que nesta pré-release foi estabilizada a estrutura de teste usando Fixtures, e evitando alguns conflitos observados em merges recentes. Obrigado.

**Comment by sergioadao** [comment]
Bom dia @marvdias e @mateussbh ....segue evidência dos problemas relacionados a desabilitar uma hipótese mapeada e excluir uma hipótese mapeada.......SEI-OFICIAL/MYSQL


https://github.com/pengovbr/mod-sei-pen/assets/87815724/d9ccd59c-a6b5-43d6-a755-bb87cd0f4555

**Comment by marvdias** [comment]
Bom dia @sergioadao, as hipoteses legais foram retiradas da resolução dessa issue sendo resolvidas numa issue à parte

**Comment by sergioadao** [comment]
@marvdias ....Bom dia Marcus....testes a issue 153 com a PR 462...Contudo, apresentou o erro que segue na evidência abaixo:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/8ad39fb1-fdb0-4fd8-9871-6e990722c0af

**Comment by caduvieira** [comment]
Não há ponto de extensão para hipótese legal no 4.0.X por isso foi desmembrado em duas issues.

**Comment by sergioadao** [comment]
@marvdias e @mateussbh ...boa tarde .....seguem evidências do funcionamento como solicitado  na issue 153 / PR 462 , para documentos, unidades e processos.....

Documentos:

https://github.com/pengovbr/mod-sei-pen/assets/87815724/e9342008-3547-4c40-a3f0-3fa2f318902d


Unidades:

https://github.com/pengovbr/mod-sei-pen/assets/87815724/861ed81d-1304-469f-a6ce-4770fccb3fca


Processos:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/3b611f49-256b-44b3-9752-5c2c02342302

**Comment by sergioadao** [comment]
@marvdias ....bom dia.....Rodei o teste

make teste=CriticasDesativarExcluirUnidadeTipoProcDocTest test-functional
ESSSSS 6 / 6 (100%)

Time: 273 ms, Memory: 12.00 MB

There was 1 error:

CriticasDesativarExcluirUnidadeTipoProcDocTest::test_desativar_tipo_processo
Data too long for column 'sigla_unidade_rh' at row 1
OBS: No arquivo phpunit.xml tenho apenas setado as variáveis abaixo:

**<const name="CONTEXTO_ORGAO_A_ID_ESTRUTURA"
  value="154401" />**
<const name="CONTEXTO_ORGAO_A_SIGLA_ESTRUTURA"
  value="INFORME_A_SIGLA_DE_ESTRUTURA_UTILIZADO_PARA_TESTE_ORG1" />
<const name="CONTEXTO_ORGAO_A_SIGLA_UNIDADE_HIERARQUIA" value="" />
**<const name="CONTEXTO_ORGAO_A_NOME_UNIDADE"
  value="CGPRO_SERGIO_ORG1" />**

**<const name="CONTEXTO_ORGAO_B_ID_ESTRUTURA"
  value="154402" />**
<const name="CONTEXTO_ORGAO_B_SIGLA_ESTRUTURA"
  value="INFORME_A_SIGLA_DE_ESTRUTURA_UTILIZADO_PARA_TESTE_ORG2" />
<const name="CONTEXTO_ORGAO_B_SIGLA_UNIDADE_HIERARQUIA" value="" />
**<const name="CONTEXTO_ORGAO_B_NOME_UNIDADE"
  value="CGPRO_SERGIO_ORG2" />**

**Comment by sergioadao** [comment]
Bom dia @marvdias e @mateussbh ...teste funcional OK......segue evidência:

toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-4.0.12.15/src/sei/web/modulos/mod-sei-pen$ make teste=CriticasDesativarExcluirUnidadeTipoProcDocTest test-functional
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env up -d
funcional_org2-database_1 is up-to-date
funcional_org1-memcached_1 is up-to-date
funcional_smtp_1 is up-to-date
funcional_org2-memcached_1 is up-to-date
funcional_org1-database_1 is up-to-date
Starting funcional_php-test-unit_1 ... 
funcional_org2-http_1 is up-to-date
funcional_org1-http_1 is up-to-date
funcional_proxy_1 is up-to-date
Starting funcional_php-test-unit_1       ... done
Starting funcional_php-test-functional_1 ... done
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run -w /tests php-test-functional bash -c './composer.phar install'
Creating funcional_php-test-functional_run ... done
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Generating autoload files
26 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run --rm php-test-functional /tests/vendor/bin/phpunit -c /tests/phpunit.xml /tests/tests/CriticasDesativarExcluirUnidadeTipoProcDocTest.php ;
Creating funcional_php-test-functional_run ... done
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHPUnit 8.5.35 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

.
.....                                                              6 / 6 (100%)

Time: 1.69 minutes, Memory: 14.00 MB

OK (6 tests, 6 assertions)

**Comment by caduvieira** [comment]
Adicionado outros métodos para os pontos de extensão que não existiam no SEI 4.0 e 4.1. Os pontos de extensão foram cirados pelo TRF4 no SEI 5. Presentes na versão do módulo 4.0.2

**Comment by yurioliveiramgi** [comment]
@caduvieira apenas para fins de registro, poderia me confirmar se essa issue está na versão 4.0.2 do módulo? Obrigado.

**Comment by caduvieira** [comment]
Sim está.

**Comment by yurioliveiramgi** [comment]
@amelquia considerando que a issue está incluída na versão 4.0.2 do módulo, seguindo a confirmação acima. E levando em consideração o chamado 53045027, é necessário que a nota de versão seja atualizada com essa issue.

Além disso, estarei movendo essa issue da milestone "backlog" para a milestone da referida versão em que a issue foi incluída. Na sequência, a issue será concluída considerando que a versão já está disponível em produção.

@euviniciusmendonca e @higodf , PSC.

**Comment by yurioliveiramgi** [comment]
Informação sobre a issue inserida de nota de versão 4.0.2.

**Comment by neijobson** [comment]
Oi pessoal,

Essa Issue foi implementada na v4.0.2 com problema, com extrapolação da regra de negócio.

Por exemplo, em vez de criticar apenas o Tipo de Processo na Administração do módulo PEN na desativação e exclusão do tipo de processo, está criticando toda e qualquer desativação ou exclusão de Tipo de Processo.
- Inclusive, tinha críticas duplicadas em alguns trechos.

Abrimos o PR a seguir corrigindo a implementação: https://github.com/pengovbr/mod-sei-pen/pull/1209

**Comment by caduvieira** [comment]
O módulo tem que verificar todos os tipos de processo e, caso esteja mapeado, não pode permitir a exclusão ou desativação. Caso esteja bloqueando tipos de processo que não estão mapeados deve-se corrigir o código.

**Comment by neijobson** [comment]
@caduvieira 
O problema está aí.
Estava bloqueando desativação de Tipo de Processo não mapeado na Administração do módulo. Todos, indistintamente.

**Comment by yurioliveiramgi** [comment]
Agora, @caduvieira, a mensagem é diferente quando o processo está mapeado e quando o processo não está mapeado. 
É possível verificar se ambas foram implementadas por meio dessa issue?
Obrigado.

**Comment by caduvieira** [comment]
Sim.  A implementação via PR [pode ser verificada.](https://github.com/pengovbr/mod-sei-pen/pull/1209#issuecomment-5063286581) A mensagem está diferente da que foi solicitada conforme [comentário no PR](https://github.com/pengovbr/mod-sei-pen/pull/1209#issuecomment-5063107435).
