### ISSUE TITLE
Erro no reenvio de processos contendo documentos com mais de um componente digital

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#156]
**Descreva o erro**
Relatado falha ao reenviar um processo contendo um documento com mais de um componente digital/arquivo. Nesta situação, o Barramento de Serviços impede o envio alegando que houve possível mudança no Hash dos documentos do processo.
 
-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Acesse um sistema A que implemente a conceito de multiplos componentes digitais para um mesmo documento. No caso, o problema foi identificado utilizando o SAPIENS da AGU.
2. Crie um processo no sistema A contendo um documento composto por dois componentes digitais/arquivos.
3. Realize o trâmite do processo para um órgão que utiliza o sistema SEI com o módulo de integração instalado.
4. Acesse o sistema B destinatário e aguarde até finalizar o recebimento do processo.
5. Processo recebido no SEI, veja que o documento criado no sistema A foi recebido corretamente e os arquivos armazenados em arquivo .zip no processo.
6 - Adicione um novo documento a este processo e reenvie-o para o sistema B 
7. Veja o erro em que o processo não será enviado pois o Barramento de Serviço alega que um dos documentos teve seu Hash modificado.

-----

**Comportamento esperado**
Esperado que o processo seja reenviado corretamente, mantendo a estrutura original do processo com cada um dos componentes digitais separados.

-----

**Screenshots**
N/A

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do módulo: 3.1.14
 - Navegador: Qualquer
 - Perfil do Usuário: N/A
 - Banco de dados: Qualquer
-----

**Informações adicionais**
Problema identificado no trâmite de processos entr o SEI e SAPIENS da AGU.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by caduvieira** [comment]
Essa coreção vai envolver mudanças no barramento?
