### ISSUE TITLE
Limitação de Repositórios/Unidades Para o Envio de Processo

### ISSUE THREAD

**Issue by LeandroMedeirosLima** [pengovbr/mod-sei-pen#196]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Atualmente qualquer unidade pode enviar processos externos para repositório/unidades aptas para o recebimento de processos e documentos avulsos. 

Um gestor de negócio reportou que isso pode ser um problema dependendo do usuário e pode levar erro no envio do processo.

-----

**Descreva a solução que você gostaria**
A possibilidade do gestor de negócio restringir quais repositórios de estrutura uma unidade pode escolher como destino de envio de processos.

-----

**Contexto adicional**
Reunião com os gestores do TJMG que propuseram o requisito: https://mtegovbr-my.sharepoint.com/:v:/g/personal/vinicius_mendonca_economia_gov_br/EQJJpJ3y9bRJo6fJQ0JOANoBFg-X8gAPCGkfocInMXHHfQ

**Comment by caduvieira** [comment]
O arquivo não está liberado para leitura.

**Comment by euviniciusmendonca** [comment]
https://mtegovbr-my.sharepoint.com/:v:/g/personal/vinicius_mendonca_economia_gov_br/EQJJpJ3y9bRJo6fJQ0JOANoB9BhUL13IRCNwGiKTJy2YSQ?e=ACyHil 

@caduvieira, co?nfirma o acesso

**Comment by euviniciusmendonca** [comment]
Solicita-se um vídeo com a evidência da melhoria.

**Comment by caduvieira** [comment]
@Mauro1706 por favor pode gerar esse vídeo?

**Comment by Mauro1706** [comment]
Segue evidências de funcionamento.

https://github.com/supergovbr/mod-sei-pen/assets/83025710/9f579fb2-2e65-48b6-81a7-81b095e8b7c7


https://github.com/supergovbr/mod-sei-pen/assets/83025710/f17b14a7-50d4-4c36-b9a9-d4edfd6bb988

**Comment by davidnascimento1618** [comment]
Prezado, @Mauro1706, vi que os itens defeituosos encontrados na _issue_ em questão, que foram descritos e evidenciados no comentário deste [_pull request_](https://github.com/supergovbr/mod-sei-pen/pull/274#pullrequestreview-1546548532), ainda continuam.
Houve atualização no PR #274?

**Comment by Mauro1706** [comment]
@davidnascimento1618 a branch ficou com conflito e não subiu as correções pertinentes

**Comment by MatheusMarques80** [comment]
Não foi possível concluir os novos ajustes solicitados pelo @davidnascimento1618 dentro do time box da sprint atual. Foi feito um estudo da funcionalidade como um todo e para a correção dos pontos mencionados será necessário mais alguns dias.

**Comment by MatheusMarques80** [comment]
Foi corrigido os seguintes itens:

1. Ao adicionar unidades restritivas a algum repositório (a partir do segundo adicionado em diante), o sistema estava deletando todas as unidades restritivas da lista.

2. Ao editar um mapeamento existente para excluir uma unidade restritiva da lista, o sistema estava removendo os repositórios não correlacionados, ou seja, considerando a seguinte relação: A -> X; B -> Y; e C -> Z, caso o usuário excluísse a unidade X, ao salvar e voltar à tela (via edição), o sistema estava removendo os repositórios B e C, em vez de remover apenas o A.

3. Tempo que um repositório e uma unidade estão sendo carregados

4. Exibição do ícone de carregamento



https://github.com/pengovbr/mod-sei-pen/assets/13146046/a73f2b1a-250f-417c-bcc4-0fcf04a1898a

**Comment by davidnascimento1618** [comment]
@MatheusMarques80, favor corrigir o problema apontado neste [comentário](https://github.com/pengovbr/mod-sei-pen/pull/361#pullrequestreview-1634233459) do _pull request_ #361,

**Comment by gledson-sousa** [comment]
Realizado a correção no repositório de estruturas quando for um valor nulo "Repositório de Estruturas não Encontrado."

**Comment by davidnascimento1618** [comment]
Prezados, favor corrigir os [conflitos](https://github.com/pengovbr/mod-sei-pen/pull/370#issuecomment-1786468581) mencionados no _pull request_ em questão.

**Comment by Mauro1706** [comment]
Segue evidência da funcionalidade:

https://github.com/pengovbr/mod-sei-pen/assets/83025710/cc4c69db-1cbb-4120-bad7-1d8982fe662f

**Comment by mateussbh** [comment]
Prezados, favor incluir o teste funcional da issue.

**Comment by Mauro1706** [comment]
https://github.com/pengovbr/mod-sei-pen/assets/83025710/8a96c245-b4df-4731-bc2d-4868a09d0ae5

**Comment by Mauro1706** [comment]
Resolvido duplicidade de cadastro.

https://github.com/pengovbr/mod-sei-pen/assets/83025710/6265176f-44b1-4c83-9974-dc277e7b14a0

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @mateussbh ...testado e confirmado o funcionamento correto. Segue evidência:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/843791fc-6bba-4db6-8914-73c762b492ed

**Comment by amelquia** [comment]
06/05/24
Necessário realizar uma limpeza de arquivos que já foram ajustados nessa issue e, deixar apenas os arquivos pertinentes à mesma.

**Comment by amelquia** [comment]
12/05/24
Issue não finalizada e migrada para a Sprint 42.

**Comment by amelquia** [comment]
27/05/24
Sprint Planning - Sprint 43 realizada.
Issue transferida para a **Sprint 43** para dar sequencia no fluxo dos status. **Status atual: "Validação Técnica."**
Nova estimativa: 2 dias.

**Comment by Mauro1706** [comment]
Segue evidencia da funcionalidade:

https://github.com/pengovbr/mod-sei-pen/assets/83025710/67c65207-6ef2-42e1-8d11-931bf81c597f

**Comment by amelquia** [comment]
03/06/24
No dia 31/05, o Mauro refez os testes e colocou o vídeo para que o Sérgio possa entender que não há erro. A issue está disponível para validação técnica.

**Comment by Mauro1706** [comment]
Refeito o PR: https://github.com/pengovbr/mod-sei-pen/pull/511

**Comment by amelquia** [comment]
11/06/24
Resolvida a questão do java script que solucionava a estrutura e unidade. 
Outros erros foram gerados devido ao componente ser antigo. Resolvendo a parte do tramitar das unidades e resolução de bugs.

**Comment by Mauro1706** [comment]
Resolvido a seleção de repositórios que limpa a seleção de unidades.
PR: https://github.com/pengovbr/mod-sei-pen/pull/518

**Comment by yurioliveiramgi** [comment]
Foi identificado que a limitação de repositórios funciona corretamente por meio do campo em que o nome da unidade será inserido. Entretanto, ao clicar no ícone "Consultar Organograma" este não realiza o carregamento.

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/fe2caf50-efc9-4a50-b291-bc53f2f985b8)

**Comment by amelquia** [comment]
21/06/24
Movimento da issue em **Em Análise P.O.** para a Sprint 45 .

**Comment by amelquia** [comment]
24/06/24
Após explicação do @yurioliveiramgi , o card foi movido para **Ajustes Necessários**.

**Comment by Mauro1706** [comment]
Organograma resolvido no PR: https://github.com/pengovbr/mod-sei-pen/pull/528

**Comment by Mauro1706** [comment]
Resolvido restrição de envio para bloco e organograma!
https://github.com/pengovbr/mod-sei-pen/pull/537

**Comment by amelquia** [comment]
08/07/24
Planning realizada. 
Card movido para a **Sprint46**.

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @amelquia .... Segue erro encontrado no mapeamento de unidades após o pull do PR 537.

Segue evidência:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/1de15700-c56a-41da-a443-38f138478c15

**Comment by Mauro1706** [comment]
Realizado a correção no PR https://github.com/pengovbr/mod-sei-pen/pull/539 com a separação dos métodos de autocompletar no cadastro de unidades e envio de processo!

**Comment by caduvieira** [comment]
@sergioadao testar novo PR

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @amelquia ..... segue testes realizados com as versões 4.0.12 , 4.1.1 e 4.1.3.

No caso, da versão 4.1.3 , surgiu um novo erro na criação de um processo. Segue evidência.


https://github.com/pengovbr/mod-sei-pen/assets/87815724/ed44c69b-25b4-488a-a488-8c47f11c17b4


https://github.com/pengovbr/mod-sei-pen/assets/87815724/5dca54e0-99f0-4754-bacb-025a67f0737e


https://github.com/pengovbr/mod-sei-pen/assets/87815724/ce46f6fd-4c25-419f-9457-6e0cb40fb1e6

**Comment by euviniciusmendonca** [comment]
@amelquia @yurioliveiramgi @Mauro1706 

Conforme explicado em reunião, a funcionalidade organograma será ocultada, visto que não é utilizada pela maioria dos usuários. Dessa forma, eu acredito que o impeditivo para conclusão dessa issue foi removido.

Atenciosamente,

**Comment by euviniciusmendonca** [comment]
@yurioliveiramgi 

Realizar o mapeamento do impacto dessa alteração na documentação do Tramita GOV.BR.

**Comment by yurioliveiramgi** [comment]
A funcionalidade prevista para a issue está correta. 
No dia de hoje foi liberado um patch que resolveu o problema do organograma para as versões 4.1.x.
Diante disso, caso seja mantida a decisão de ocultar o organograma (issue #540), a issue está validada negocialmente.
Caso contrário, será necessário aguardar o merge do PR para posterior validação.

@euviniciusmendonca PSC e validação.

**Comment by yurioliveiramgi** [comment]
16/07/24 - Issue validada, funcionamento conforme esperado. Movida para Aceito Negocial.

@Mauro1706 , @amelquia , @euviniciusmendonca e @mateussbh , PSC

**Comment by yurioliveiramgi** [comment]
A presente issue está sendo encaminhada para realização de ajustes. Na realização de alguns testes, foi verificada a necessidade de algumas correções:
1. Ao realizar a limitação de apenas estruturas (mantendo o campo de unidades vazio), Figura 01, ao tentar realizar o envio de um trâmite, a limitação de repositórios de estruturas é respeitada, Figura 02. Entretanto, nenhuma unidade é exibida como destino, Figura 03.
- [ ] Caso o gestor preencha apenas o campo "Restringir às Estruturas" deve ser compreendido que todas as unidades pertencentes ao(s) repositório(s) selecionados deve(m) ser exibido(s). Ou seja, existirá apenas uma limitação de repositórios de estruturas e não de unidades;
Figura 01
![image](https://github.com/user-attachments/assets/5a3c82c2-cb1e-49f6-a07f-5dd4a881bd7c)
Figura 02
![image](https://github.com/user-attachments/assets/bdcbff85-135c-4b20-95f4-c39702c1b88e)
Figura 03
![image](https://github.com/user-attachments/assets/f98ef4a1-ec95-4c25-a97c-6d336745a6ef)

2. Correção gramatical no texto exibido nas telas "Novo Mapeamento de Unidades" (Figura 04) e "Editar Mapeamento de Unidades" (Figura 05).

- [ ] Em ambas telas alterar "Restringir as Estruturas" para **"Restringir às Estruturas"**.
Figura 04
![image](https://github.com/user-attachments/assets/7f2dcb68-f80f-4ada-98c1-ba62969bb4c3)
Figura 05
![image](https://github.com/user-attachments/assets/ede987f6-43b2-4fc0-83e5-69ae7aaf25b7)

3. Aproveito para solicitar a alteração do título da tela "Mapeamento de Unidade" para **"Mapeamento de Unidades"**
![image](https://github.com/user-attachments/assets/2357a548-23a5-4b96-90c1-e2077e6ba9a9)
 
 @euviniciusmendonca , @amelquia , @mateussbh , @Mauro1706 , PSC.

**Comment by amelquia** [comment]
@yurioliveiramgi 
Como essa issue foi validada e dada como **Aceito Negocial,** peço a gentileza de abrir uma nova issue para análise e correções.

**Comment by yurioliveiramgi** [comment]
@euviniciusmendonca, PSC

**Comment by amelquia** [comment]
30/07/24 - Daily
Conforme solicitado pelo @euviniciusmendonca, a fim de ganharmos celeridade com as tratativas para a liberação da release 3.7.0, a issue será alterada para **"Ajustes Necessários"** e, será tratada na Sprint atual - Sprint 47.

**Comment by Mauro1706** [comment]
Realizado as correções apontadas pelo @yurioliveiramgi no PR https://github.com/pengovbr/mod-sei-pen/pull/565
Segue evidência da correção:

https://github.com/user-attachments/assets/a6fc7bf3-5fed-4d6b-ba83-d67565063e23

**Comment by yurioliveiramgi** [comment]
Issue validada negocialmente. Funcionamento conforme o previsto.

@amelquia , @mateussbh e @euviniciusmendonca
