### ISSUE TITLE
Uncaught Error: Class 'PenAtualizadorRN' 

### ISSUE THREAD

**Issue by will76** [pengovbr/mod-sei-pen#197]
**Descreva o erro**
Estou obtendo o seguinte erro ao rodar o script _sei_atualizar_versao_modulo_pen.php_ na instalação:

```
php -c /etc/php.ini /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php
PHP Fatal error:  Uncaught Error: Class 'PenAtualizadorRN' not found in /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php:49
Stack trace:
#0 {main}
  thrown in /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php on line 49

```
Curiosamente, não obtive erros ao executar o script do passo anterior 1.6 - sip_atualizar_versao_modulo_pen.php

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
Instalação seguindo a documentação em INSTALL.md

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: SEI 4.0.7
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]
 - Banco de dados: MySQL
-----

-----

**Comment by caduvieira** [comment]
Isso, aparentemente pela informação dada, é um erro no ConfiguracaoSEI.php com a falta da importação do módulo.

Favor verificar se a pasta que se encontra o módulo é a mesma configurada no array SEI -> Modulos.
