### ISSUE TITLE
Criação de Ícone para indicativo de processo enviado por meio do Tramita.GOV.BR

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#226]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Atualmente, não existe indicativo visual para identificar processos enviados por meio do Tramita.GOV.BR.

-----

**Descreva a solução que você gostaria**
A criação de ícone para indicativo do processo enviado por meio do Tramita.GOV.BR.

-----

**Comment by guilhermeadc** [comment]
Inicialmente, poderia ser utilizado o mesmo ícone da implementação do Pull Request #191

**Comment by caduvieira** [comment]
Relacionada a #12

**Comment by guilhermeadc** [comment]
Prezados, 

_Foi identificado um problema semelhante a implementação da issue #12 - Ícone indicativo de processo recebido pelo Tramita.gov.br_

Durante os testes desta funcionalidade, foram identificados um pequeno problema que precisa ser ajustado antes de serem aceitos e incorporados ao mod-sei-pen.

1) O ícone indicativo de processo enviado pelo Tramita.gov.br está se repetindo inúmeras vezes, 1 para cada trâmite já realizado pelo processo, conforme demonstrado abaixo.
![image](https://user-images.githubusercontent.com/4326504/233874839-bf5037d2-999b-4abb-99b3-cd0acaf5d4d4.png)
![image](https://user-images.githubusercontent.com/4326504/233874931-0304ad70-30c2-4739-8e96-a46e40ed482b.png)


O comportamento correto deveria ser a apresentação de apenas 1 ícone indicando que o último envio.

**Comment by euviniciusmendonca** [comment]
Aguardando o novo ícone para incluir na issue @pedrohpms @caduvieira.

**Comment by Mauro1706** [comment]
Segue evidência da funcionalidade:

https://github.com/supergovbr/mod-sei-pen/assets/83025710/9959bc66-0e55-4412-a63f-21658f0fd6cf

**Comment by pedrohpms** [comment]
Excelente, Mauro! Aprovado.
