### ISSUE TITLE
Erro no Trâmite de Processo convertido de Documento Avulso

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#239]
**Descreva o erro**
Um documento avulso foi recebido pelo SEI e convertido em processo. O usuário incluiu novos documentos e tentou tramitar novamente. Contudo, seguinte erro aconteceu:

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/60577185/224429878-9fcee504-abf4-4577-ac6e-0f59037dcdc5.png)

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Um documento avulso ser enviado ao SEI para ser convertido em um processo;
2. Incluir novos documentos no processo;
3.  Tentar tramitar novamente o processo para o Tramita.GOV.BR.

-----

**Comportamento esperado**
Concluir o envio do processo para o Tramita.GOV.BR.

-----

**Screenshots**
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/60577185/224429878-9fcee504-abf4-4577-ac6e-0f59037dcdc5.png)

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/60577185/224432246-83af05e3-58b1-4727-a528-7f4834438d1d.png)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: N/A
 - Navegador: N/A
 - Perfil do Usuário: N/A
 - Banco de dados:  N/A
-----

**Informações adicionais**

A conclusão da correção desta issue deverá ter como resultado:
- Implementação com as devidas correções nas classes de Envio de Processo
- Implementação de teste automatizado para o cenário descrito nesta issue (Semelhante ao implementado em TramiteRecebimentoDocumentoAvulsoTest)

-----
**Log de Erros**
N/A

**Comment by gledson-sousa** [comment]
Card com impedimento pois não foi possível gerar um documento avulso.

**Comment by gledson-sousa** [comment]
Não está sendo possível gerar o documento avulso
pois as configurações no Repositório de Estruturas não estão funcionando.

**Comment by gledson-sousa** [comment]
Implementado a validação sugerida para o tipo de Documento Avulso, mas não foi possível testar pela aplicação.
Foi identificado que para o Protocolo normal o **sta_tipo_protocolo** é Protocolo = P e para Protocolo Documento Avulso = D.
Então, se o for um Documento Avulso "D",  já tramitado o NRE, Número de Registro Eletrônico será Null, corrigindo o erro.

Executando o teste funcional de trâmite de recebimento de documento avulso, foi gerado os dados no banco.
 make teste=TramiteRecebimentoDocumentoAvulsoTest test-functional
<img width="958" alt="Captura de tela 2023-07-10 161625" src="https://github.com/supergovbr/mod-sei-pen/assets/121505958/dd0a78a5-06c4-4666-94d8-43bb5a08092d">
<img width="470" alt="Captura de tela 2023-07-10 161725" src="https://github.com/supergovbr/mod-sei-pen/assets/121505958/f25a93e7-60c0-44e4-a30d-99d890fa9144">

**Comment by mateussbh** [comment]
Movido da sprint 19 para a 26.

**Comment by gledson-sousa** [comment]
Caro @mateussbh, poderia testar a funcionalidade? Fiz a alteração no código, porém  não consegui simular o erro.

**Comment by mateussbh** [comment]
Movido da sprint 26 para a 27.

**Comment by mateussbh** [comment]
Testes realizados com sucesso no SEI oficial (mysql/oracle/sqlserver), SEI4  (mysql/oracle/sqlserver) e SEI3 (mysql). Pendente execução do teste para SEI3 (oracle/sqlserver). 

Evidência SEI oficial - mysql
![ok - super - mysql](https://github.com/pengovbr/mod-sei-pen/assets/3789823/fb436d4a-e535-40a9-a685-3ba64ba2d38c)


Evidência SEI oficial - oracle
![ok - super - oracle](https://github.com/pengovbr/mod-sei-pen/assets/3789823/106f2f0c-bd07-4080-a283-ae32606bf422)


Evidência SEI oficial - sqlsersver
![ok - super - sqlserver](https://github.com/pengovbr/mod-sei-pen/assets/3789823/bb452675-b942-491f-8408-ccb798f5cbb2)


Evidência SEI 4 - mysql
![ok - sei4 - mysql](https://github.com/pengovbr/mod-sei-pen/assets/3789823/70eb58ff-ccd1-4718-9c2d-57916a7fac18)


Evidência SEI 4 - oracle
![ok - sei4 - oracle](https://github.com/pengovbr/mod-sei-pen/assets/3789823/f3b5caf8-60af-4f52-b6e9-20b6ee86caa3)


Evidência SEI 4 - sqlsersver
![ok - sei4 - sqlserver](https://github.com/pengovbr/mod-sei-pen/assets/3789823/65be45a5-f84e-4a78-97b0-417b7db63027)


Evidência SEI 3 - mysql
![ok - sei3 - mysql](https://github.com/pengovbr/mod-sei-pen/assets/3789823/51f27099-db8e-4f8b-b27b-18e699a7ad61)
