### ISSUE TITLE
Módulo do Tramita não exibe todas as unidades disponíveis para envio de processo

### ISSUE THREAD

**Issue by pedrohpms** [pengovbr/mod-sei-pen#242]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Ao buscar na lista de unidades disponíveis para envio a partir de um determinado critério qualquer de busca (como um trecho de nome ou de sigla de órgão ou unidade), a droplist exibida com os resultados sugeridos apresenta apenas as 20 (vinte) primeiras ocorrências, deixando de fora - nos casos em que há mais de 20 unidades disponíveis que satisfaçam o critério - quaisquer unidades que não as 20 primeiras.

-----

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você deseja que aconteça.
--
O acréscimo de uma barra de rolagem possibilitaria ao usuário visualizar a lista inteira de unidades que satisfazem o critério de busca.

-----

**Descreva alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.
--
Pode ser adotado mecanismo de paginação ou uma lista secundária ("clique aqui para ver mais"), mas não há ganho concreto com nenhuma das alternativas.

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.
--
Queixa de usuários:

![WhatsApp Image 2023-03-21 at 12 26 59](https://user-images.githubusercontent.com/79460464/226658665-1fd6c999-64d4-45e8-bc43-f3aefdb36096.jpeg)

**Comment by caduvieira** [comment]
Precisamos:
Verificar se é:

- Limitação do módulo ou;
- Se essa limitação de 20 é da API do barramento.

Sugerir mudança conforme análise.

**Comment by euviniciusmendonca** [comment]
@caduvieira @guilhermeadc @higodf  Eu não consigo simular o comportamento:

![image](https://github.com/supergovbr/mod-sei-pen/assets/60577185/ccc8b99d-069c-46ac-9292-ff1ae2911896)

**Comment by caduvieira** [comment]
@euviniciusmendonca 

O comportamento atual é o:
![image](https://github.com/supergovbr/mod-sei-pen/assets/3831408/2abd0815-d040-4e53-a690-a7103df1b8b1)

Isso atende a demanda?

**Comment by euviniciusmendonca** [comment]
@caduvieira de acordo com a sugestão.
