### ISSUE TITLE
Blocos de Trâmite Externo: Tela de Listagem de Blocos de Trâmite Externo

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#245]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
--
Criação de blocos de trâmite de processos para permitir a organização, revisão e envio de processos em bloco 

Disponibilizar nova opção no Menu Principal do Super.GOV.BR, chamada “Bloco de Trâmite Externo”, visível apenas aos usuários com perfil “Tramitador de Processos em Bloco”, contendo os submenus “Novo”, “Listar” e “Reativar”

____

**Descreva a solução que você gostaria**
--
Aqui vamos tratar do submenu Listar (Blocos de Trâmite Externo > Listar). Esses blocos podem ser listados e podem ser filtrados.

Quando selecionado o Menu “Blocos de Trâmite Externo”, submenu “Listar”, exibir tabela no padrão do sistema contendo as Colunas abaixo, com possibilidade de caixas de seleção na coluna da esquerda:

- Número do bloco; 
- Sinalizações   
- Estado 
- Descrição bloco ser criado; 
- Ações (“Processos do bloco”, “Trâmitar bloco”, “Alterar Bloco”, “Excluir”, "Concluir")  

Acima da tabela, nova seção contendo pesquisa com filtro (multinível, permitindo acréscimo de critério e operadores lógicos “E” ou “OU”) por:  

- Palavras-chave para pesquisa  
- Sinalizações
- Estado do Bloco (aberto, concluído, em processamento, etc.)  

____

**Descreva alternativas que você considerou**
--
N/A

____

**Contexto adicional**
--
Esse novo bloco é voltado para o trâmite conjunto de processos para um destino.

**Comment by mrglaydson** [comment]
Atividade concentrada na issue #292 e resolvida no Pr https://github.com/pengovbr/mod-sei-pen/pull/418

**Comment by mateussbh** [comment]
Funcionalidade do bloco externa finalizada e testada com sucesso nas versões sei 4.0.12.15, 4.0.12 e 3.1.7, nos BDs mysql, oracle e sqlserver. 

Comentários foram majoritariamente centralizados nas issues 306 e 292.  O PR com os arquivos da funcionalidade (pré-release) é o https://github.com/pengovbr/mod-sei-pen/pull/424.
