### ISSUE TITLE
Blocos de Trâmite Externo: Cadastrar/Alterar Bloco de Trâmite Externo

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#246]

**Comment by guilhermeadc** [comment]
As orientações de como deve ser desenvolvida esta funcionalidade foram passadas na reunião de planejamento (gravada) e deverá se basear na funcionalidade de Cadastro de Bloco Interno do SEI.

**Comment by MatheusMarques80** [comment]
https://github.com/supergovbr/mod-sei-pen/assets/13146046/dedc4f04-6ca1-46a0-913c-36f4a69b5919

**Comment by mateussbh** [comment]
Funcionalidade do bloco externa finalizada e testada com sucesso nas versões sei 4.0.12.15, 4.0.12 e 3.1.7, nos BDs mysql, oracle e sqlserver. 

Comentários foram majoritariamente centralizados nas issues 306 e 292.  O PR com os arquivos da funcionalidade (pré-release) é o https://github.com/pengovbr/mod-sei-pen/pull/424.
