### ISSUE TITLE
Blocos de Trâmite Externo: Excluir Bloco de Trâmite Externo

### ISSUE THREAD

**Issue by caduvieira** [pengovbr/mod-sei-pen#247]

**Comment by Mauro1706** [comment]
Segue evidência de funcionalidade:

https://github.com/supergovbr/mod-sei-pen/assets/83025710/53fc5317-670a-4c5c-aed1-164ab0f5700e

**Comment by mrglaydson** [comment]
Atividade concentrada na issue #292 e resolvida no Pr https://github.com/pengovbr/mod-sei-pen/pull/418
