### ISSUE TITLE
Blocos de Trâmite Externo: Vísualizar processos do bloco de trâmite externo

### ISSUE THREAD

**Issue by caduvieira** [pengovbr/mod-sei-pen#248]
Os campos da listagem deverão conter os atuais campos do "Envio em Lote" como referência.

![Image](https://github.com/supergovbr/mod-sei-pen/assets/4326504/2d43515d-6359-4e05-b94c-21cc27707959)

**Comment by Mauro1706** [comment]
Segue evidência da funcionalidade:

**Comment by mrglaydson** [comment]
Atividade concentrada na issue #292 e resolvida no Pr https://github.com/pengovbr/mod-sei-pen/pull/418

**Comment by mateussbh** [comment]
Funcionalidade do bloco externa finalizada e testada com sucesso nas versões sei 4.0.12.15, 4.0.12 e 3.1.7, nos BDs mysql, oracle e sqlserver. 

Comentários foram majoritariamente centralizados nas issues 306 e 292.  O PR com os arquivos da funcionalidade (pré-release) é o https://github.com/pengovbr/mod-sei-pen/pull/424.
