### ISSUE TITLE
Mapeamento de Tipos de Processos: Exportar Tipos de Processo do órgão remetente

### ISSUE THREAD

**Issue by caduvieira** [pengovbr/mod-sei-pen#252]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
---
Esta melhoria é parte do pacote referente à funcionalidade de Blocos de Envio Externo. A funcionalidade em questão permitirá que, entre órgãos que realizem mapeamento prévio de __Tipos de Processo__, os processos recebidos via Tramita GOV.BR já sejam recebidos no destino com o __Tipo de Processo__ escolhido pelo destinatário, sem a necessidade de intervenção posterior ao recebimento para corrigir seus metadados.

É necessário que o sistema **remetente** gere e exporte uma listagem de seus _Tipos de Processo_ em formato que possibilite posterior implantação no destinatário (sugere-se o .csv, mas fica a critério da área técnica).

_____

**Descreva a solução que você gostaria**
---

Solicito, para  viabilizar a exportação dos _Tipos de Processo_ do órgão **remetente**, a inclusão de novo **botão**, nos termos abaixo:

No menu do SEI, conforme caminho abaixo:
> Administração > Tipos de Processo > Listar

O sistema deve exibir, na lista de botões visíveis acima e abaixo da tabela exibida na referida tela, o botão "Exportar".

Para possibilitar a exportação, o usuário deve selecionar ao menos um Tipo de Processo, clicando na checkbox à esquerda da linha correspondente na tabela. Caso não selecione, exibir alerta padrão (_"Nenhum registro selecionado para gerar exportação dos Tipos de Processo."_).

Ao selecionar _Tipos de Processo_ e clicar no botão exportar, o sistema deve gerar um arquivo contendo a listagem dos tipos selecionados, trazendo o _ID_ e a _descrição_ de cada _Tipo de Processo_.

A frase abaixo resume a lógica do mapeamento de Tipos de Processo:

### **"processos com o Tipo de Processo ‘X’, ao serem recebidos do órgão ABC, devem receber o Tipo de Processo ‘Y’".**

Esta lógica implica na criação de uma tabela "De-Para" de _Tipos de Processo_. O arquivo exportado nesta tela deve ser importado no sistema destino, de modo a trazer a coluna "De" da Tabela "De-Para" já preenchida.

___

### Referência para criação

![image](https://github.com/supergovbr/mod-sei-pen/assets/79460464/cb80e66c-3120-495b-a73f-fd037348fec1)
_Tabela da tela "Tipos de Processo", com os botões acima. O botão exportar deve ser acrescentado a essa sequência de botões (sugere-se imediatamente antes do botão imprimir, se possível_.

____

**Contexto adicional**
---

**Comment by pedrohpms** [comment]
Foi verificada a necessidade de se criar uma modal para atender a presente demanda.

Acrescentar  modal em “Administração > Tipos de Processo > Listar”, acionada a partir de novo botão “Exportar”, alinhado aos botões já existentes. A modal deve exibir a lista de processos inteira, sem paginação, com checkboxes individuais e geral (“select all”). Selecionados os Tipos, deve-se clicar no botão “Exportar”, para que o sistema gere um arquivo “.csv” que deverá conter tanto os IDs quanto os nomes dos TdPs.

**Comment by mateussbh** [comment]
Funcionalidade testada com sucesso nas versões sei-oficial (antigo super), nos bancos mysql, oracle e sqlserver, no sei 4, versões de banco mysql, oracle e sqlserver, e sei3, versão de banco mysql.

Foi seguido um roteiro de testes, conforme documento (https://mtegovbr.sharepoint.com/:o:/s/Super.br/EtqPl3ipk2xOpTesIG25hwcBk1YxDoLax5bhcRBH18-b9w?e=uy8UtN), para registrar os casos de testes testados, e em quais versões do sistema e banco de dados.


Issues que fazem parte do pacote da funcionalidade "mapeamento de tipo de processo":

**Mapeamento de Tipos de Processos: Cadastro de Relacionamento entre Órgãos**
	https://github.com/pengovbr/mod-sei-pen/issues/250 
	
**Mapeamento de Tipos de Processos: Relacionamento entre Órgãos**
	https://github.com/pengovbr/mod-sei-pen/issues/251 

**Mapeamento de Tipos de Processos: Mapeamento de Tipo de Processo - [Nome do órgão origem]**
	https://github.com/pengovbr/mod-sei-pen/issues/324 
	
**Mapeamento de Tipos de Processos: Ação Reativar o mapeamento de órgão externo**
	https://github.com/pengovbr/mod-sei-pen/issues/253 

~~**Mapeamento de Tipos de Processos: Importar Tipos de Processos para mapeamento**
	https://github.com/pengovbr/mod-sei-pen/issues/257~~ [DUPLICADA]
	
**Mapeamento de Tipos de Processos: Importar no destinatário o arquivo com Tipos de Processo do remetente**
	https://github.com/pengovbr/mod-sei-pen/issues/254 

~~**Mapeamento de Tipos de Processos: Exportar Tipos de processos em arquivo**
	https://github.com/pengovbr/mod-sei-pen/issues/256~~  [DUPLICADA]
	
**Mapeamento de Tipos de Processos: Exportar Tipos de Processo do órgão remetente**
	https://github.com/pengovbr/mod-sei-pen/issues/252 

**Mapeamento de Tipos de Processo: Exclusão de Tipos de Processos Mapeados**
	https://github.com/pengovbr/mod-sei-pen/issues/384 

**Mapeamento de Tipos de Processos: Aplicar mapeamento automático de t. processo no recebimento**
	https://github.com/pengovbr/mod-sei-pen/issues/255

**Comment by euviniciusmendonca** [comment]
Após a validação negocial, a DIVIN liberou a release da versão 3.5.0 na qual está incluída a funcionalidade Mapeamento de Tipo de Processos.
