### ISSUE TITLE
Mapeamento de Tipos de Processos: Ação Reativar o mapeamento de órgão externo

### ISSUE THREAD

**Issue by caduvieira** [pengovbr/mod-sei-pen#253]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
---
Esta melhoria é parte do pacote referente à funcionalidade de Blocos de Envio Externo. A funcionalidade em questão permitirá que, entre órgãos que realizem mapeamento prévio de __Tipos de Processo__, os processos recebidos via Tramita GOV.BR já sejam recebidos no destino com o __Tipo de Processo__ correto, sem a necessidade de intervenção posterior ao recebimento para corrigir seus metadados.

Esta melhoria está relacionada diretamente à issue #250, que trata do cadastramento de órgãos externos para recebimento sem a necessidade de correção manual dos metadados.

Esta complementação diz respeito à possibilidade de **excluir ou desativar um órgão previamente mapeado.**

_____

**Descreva a solução que você gostaria**
---

A solicitação consiste na funcionalidade abaixo descrita:

A issue #250 solicitou a criação, no SEI, do seguinte menu:
> Administração > Processo Eletrônico Nacional > Órgãos Externos

que contenha os submenus:
> Listar, Novo e Reativar

A melhoria aqui retratada descreve funcionalidades que devem constar no submenu "Listar":

Ao se clicar em listar, o sistema deve exibir tabela com duas colunas: "Nome do Órgão" e "Ações". A coluna ações deve conter os 4 ícones habituais do SEI (Visualizar, Editar, Desativar e Excluir) e um 5º ícone chamado de "Unidades".

Esta funcionalidade diz respeito ao comportamento dos botões _Desativar_ e _Excluir_. 

Ao se clicar em qualquer dos botões, _Desativar_ ou _Excluir_, o sistema deve tornar sem efeito o **cadastro de órgão externo**, revertendo seu funcionamento para a **regra padrão** do Tramita GOV.BR, de que os processos remetidos entre estes órgãos serão cadastrados com Tipo Genérico padrão definido pelo órgão destinatário. 

O que os difere é que o _Desativar_ permite posterior reativação (ou seja, as configurações devem ser preservadas, ainda que inativadas), ao passo que o _Excluir_ reverte o funcionamento para a regra padrão e exclui as configurações previamente executadas.

Além disso, os órgãos externos _desativados_ devem passar a figurar na tela acessível do seguinte menu:
> Administração > Processo Eletrônico Nacional > Órgãos Externos

submenu:
>  Reativar

de modo a possibilitar sua reativação, quando considerado necessário pelo administrador do sistema.

A frase abaixo resume o efeito desta issue na lógica do mapeamento de Tipos de Processo:

**"Ao se _Desativar_ ou _Excluir_ o órgão externo ABC, processos com qualquer Tipo de Processo , ao serem recebidos desse órgão (ABC), devem voltar receber o Tipo de Processo padrão definido nos parâmetros de configuração do Tramita GOV.BR".**

**Comment by pedrohpms** [comment]
Alteração de requisito:

A presente funcionalidade deixou de ser uma tela específica do sistema, e passou a corresponder a um dos botões de ação da coluna "Ação" correspondente a cada linha da tabela de mapeamentos de órgãos externos. 

A partir da checkbox (ao lado da pesquisa) "Incluir Inativos", devem ser retornadas as linhas correspondentes aos órgãos eventualmente desativados, trazendo apenas a possibilidade de reativação ou exclusão.

**Comment by euviniciusmendonca** [comment]
Não é tela específica, conforme informado pelo @pedrohpms. A tela atual referente a essa funcionalidade é a seguinte: https://www.figma.com/file/w2MIP7290Ms7VIktsbTGdX/Tramita---Mapeamento-de-Tipo-de-Processo?type=design&node-id=9-3&mode=design&t=L4HtvO1LR6mNKMjy-0.

**Comment by MatheusMarques80** [comment]
Foi adicionado a rotina de reativação de um mapeamento. O botão de reativar só irá ser exibido caso o estado do mapeamento esteja inativo.

PR: #325

**Comment by davidnascimento1618** [comment]
@MatheusMarques80, em conversa com o Vinícius, decidimos por manter nesta _issue_ em questão, a ação do botão de desativar, já que ela trata de uma funcionalidade que é um pré-requisito, ou seja, para uma reativação, necessariamente tem que haver uma desativação, a reativação e desativação, tratam-se de uma evolução das _issues_ anteriores (250 e 251), inclusive, nesta seção do [protótipo](https://www.figma.com/file/w2MIP7290Ms7VIktsbTGdX/Tramita---Mapeamento-de-Tipo-de-Processo?type=design&node-id=9-3&mode=design), é exibido, na coluna de 'ações', os ícones: 'Mapeamento', 'Pesquisar', 'Editar', 'Desativar' e 'Excluir'; além dos botões: 'Pesquisar', 'Novo Relacionamento', 'Desativar', 'Excluir', 'Imprimir' e 'Fechar', onde as ações de pesquisar, editar, imprimir e excluir foram implementadas nessas _issues_, com os seus respectivos _pull requests_ (#316 e #323).
Portanto, realizar a implementação do botão de 'Desativar', caso julgue necessário, sinta-se à vontade para acrescentar os _story points_ necessários. Assim que finalizar, anexar uma evidência em vídeo da funcionalidade e dos testes funcionais.

**Comment by davidnascimento1618** [comment]
Foi verificado que quando há mais de um registro de relacionamento entre órgãos e, pelo menos um destes está inativo, está aparecendo o botão de 'Desativar'; ou se pelo menos um destes está ativo, está sendo exibido o botão de 'Reativar', em ambos os casos, não faz sentido o sistema permitir as ações de desativar um relacionamento já inativo ou reativar um relacionamento já ativo. O ideal seria o sistema impedir tais ações com mensagens impeditivas ou mesmo ao selecionar os _checkboxes_ destes relacionamentos, o sistema sequer exibir os dois botões simultaneamente.

**Comment by davidnascimento1618** [comment]
Prezado @MatheusMarques80, favor verificar o seguinte [comentário](https://github.com/pengovbr/mod-sei-pen/pull/325#discussion_r1308184446).

**Comment by MatheusMarques80** [comment]
Ajustes realizado @davidnascimento1618

**Comment by davidnascimento1618** [comment]
Prezados, @Mauro1706 e @mrglaydson,

Voltando o _status_ da _issue_ para realizar os seguintes [ajustes](https://github.com/pengovbr/mod-sei-pen/pull/325#pullrequestreview-1599457744) elencados no _pull request_ 323.

**Comment by mrglaydson** [comment]
@davidnascimento1618 @sergioadao 

Para a execução correta do teste funcional, é necessário fazer uma edição no arquivo phpunit.xml, que está localizada na pasta do teste que se deseja executar (tests_sei3/tests_sei4/tests_super). 

Mudar o "value" das constantes: _CONTEXTO_ORGAO_A_UNIDADE_ESTRUTURAS_ & _CONTEXTO_ORGAO_B_UNIDADE_ESTRUTURAS_. Esse campo servirá para configuração do campo **órgão origem** na tela da listagem do mapeamento dos órgãos.

Adicione a unidade do seu certificado no respectivos campos, por exemplo:

CONFIGURAÇÕES DE TESTE ÓRGÃO 1: 

![Image](https://github.com/pengovbr/mod-sei-pen/assets/11926294/6358d499-bc17-44f7-85f8-ee09277a42e3)

CONFIGURAÇÕES DE TESTE ÓRGÃO 2: 
![Image](https://github.com/pengovbr/mod-sei-pen/assets/11926294/288ed4a8-203f-45eb-aaee-d32d9b6aeec6)

**Comment by sergioadao** [comment]
@mrglaydson....problema encontrado no procedimento de DESATIVAR...conforme [comentário](https://github.com/pengovbr/mod-sei-pen/pull/386#pullrequestreview-1720938610).

**Comment by sergioadao** [comment]
@mrglaydson....Na aplicação da PR 386, foi encontrado....segue [evidência](https://github.com/pengovbr/mod-sei-pen/pull/386#pullrequestreview-1721185642).

**Comment by sergioadao** [comment]
@mrglaydson ....problemas na execução do teste funcional......[clique aqui.](https://github.com/pengovbr/mod-sei-pen/pull/386#pullrequestreview-1723360242)

**Comment by davidnascimento1618** [comment]
@Mauro1706, @mrglaydson, favor realizar também essa correção apontada [aqui](https://github.com/pengovbr/mod-sei-pen/pull/386#pullrequestreview-1738174045).

**Comment by sergioadao** [comment]
@mrglaydson....aplicação testada e confirmada a implementação. Porém, apresenta erros na execução do teste funcional. Segue evidência...[clique aqui](https://github.com/pengovbr/mod-sei-pen/pull/396#pullrequestreview-1744250444).

**Comment by sergioadao** [comment]
@mrglaydson ....segue link para visualização da gravação do teste funcional indicado no comentário anterior. [Clique aqui.](https://github.com/pengovbr/mod-sei-pen/pull/396#pullrequestreview-1744428049)

phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 6, Assertions: 0, Errors: 6.
ERROR: 2
make: *** [Makefile:177: test-functional] Erro 2

**Comment by sergioadao** [comment]
@mrglaydson...segue mensagem de conflito na aplicação da branch.....[clique aqui](https://github.com/pengovbr/mod-sei-pen/pull/396#pullrequestreview-1747882292)

**Comment by Mauro1706** [comment]
tarefa movida de sprint 29 para sprint 30

**Comment by sergioadao** [comment]
@mateussbh @Mauro1706  ....... ajuste no tamanho do nome de variáveis feito e implementado com sucesso.

**Comment by euviniciusmendonca** [comment]
Após a validação negocial, a DIVIN liberou a release da versão 3.5.0 na qual está incluída a funcionalidade Mapeamento de Tipo de Processos.
