### ISSUE TITLE
Mensagem de Erro na tentativa de novo trâmite para processo com trâmite em andamento

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#273]
**Descreva o erro**
O processo já foi recebido no destino. Contudo, o trâmite ainda não foi concluído. O erro é gerado ao tentar tramitar novamente o processo.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Criar um processo em uma instância e tramitar o processo para outra instância;
2. Ao receber o processo no destino, tentar tramitar o mesmo processo de volta antes que chegue ao status 6.

-----

**Comportamento esperado**

Uma mensagem mais clara:
O trâmite ainda não foi concluído. Acompanhe no Painel de Controle o andamento da tramitação, antes de realizar uma nova tentativa.  NRE: XXX. Processo: XXX.

A mensagem acima deve estar sendo armazenada em LOG também.

-----

**Screenshots**

![image](https://user-images.githubusercontent.com/60577185/236042923-d9071455-eed9-49f6-a5ce-a32d52f354b7.png)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema:  N/A
 - Navegador: N/A
 - Perfil do Usuário: N/A
 - Banco de dados: N/A
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by davidnascimento1618** [comment]
@euviniciusmendonca, conforme teste funcional realizado, a solicitação de melhoria encontra-se implementada segundo o requisito descrito. Abaixo segue um _.gif_ da evidência:

![Mensagem de Erro na tentativa de novo trâmite para processo com trâmite em andamento](https://github.com/supergovbr/mod-sei-pen/assets/87980947/492a2511-5798-40fd-96a2-efa05cba3983)

**Comment by davidnascimento1618** [comment]
_Issue_ foi retornada por conta das [solicitações](https://github.com/pengovbr/mod-sei-pen/pull/283#pullrequestreview-1502321876) do _pull request_ #283. Favor reabrir o PR e realizar as correções supracitadas.

**Comment by davidnascimento1618** [comment]
@michael-ferreira2022, ao realizar o reteste, recebendo um processo de outro órgão e tentando tramitar o mesmo processo de volta, antes que chegue ao status "6", foi verificado que o sistema está exibindo a seguinte mensagem de erro: _"Erro: Atributo [ProtocoloFormatado] não existe no DTO."_, conforme é exibido no _.gif_ abaixo:

![Erro: Atributo  ProtocoloFormatado  não existe no DTO](https://github.com/pengovbr/mod-sei-pen/assets/87980947/afc62c3b-ae3c-4137-9e9a-7a62c34c8b22)

**Comment by michael-ferreira2022** [comment]
Erro corrigido

**Comment by davidnascimento1618** [comment]
@michael-ferreira2022, ao realizar o reteste, recebendo um processo de outro órgão e tentando tramitar o mesmo processo de volta, antes que chegue ao status "6", foi verificado que o sistema agora está exibindo a seguinte mensagem de erro: _"Atributo [ProtocoloProcedimentoFormatado] não existe no DTO."_, conforme é exibido no _.gif_ abaixo:

![Erro: Atributo  ProtocoloProcedimentoFormatado  não existe no DTO](https://github.com/pengovbr/mod-sei-pen/assets/87980947/dff98d63-096f-4119-afc9-769e4494cb38)

**Comment by michael-ferreira2022** [comment]
@davidnascimento1618 corrigido e evidenciado.

https://github.com/pengovbr/mod-sei-pen/assets/121502868/22b036e6-f89b-41e4-abbb-e3b95eed7827

**Comment by davidnascimento1618** [comment]
@euviniciusmendonca, conforme teste funcional realizado, a solicitação de melhoria encontra-se implementada segundo o requisito descrito. Abaixo segue um _.gif_ da evidência:

![Mensagem de Erro na tentativa de novo trâmite para processo com trâmite em andamento (reteste)](https://github.com/pengovbr/mod-sei-pen/assets/87980947/14be0b08-3b60-4a7a-9bff-f4370bdeb9c3)
