### ISSUE TITLE
Recusa por Hipótese Legal não encontrada.

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#275]
**Descreva o erro**
A mensagem está muito objetiva e impede que o gestor de protocolo da origem entenda o motivo da recusa.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Duas Instâncias;
3. Na instância de origem criar um processo de nível de acesso restrito sem hipótese legal( Por exemplo: Controle Interno) presente no destino;
4. No destino excluir o tipo de hipótese legal mapeado na Hipótese Legal Padrão (Por exemplo: Controle Interno). A combo ficará vazia;
5.  Mandar o processo da origem para o destino;
6. Aguardar a recusa.

-----

**Comportamento esperado**
Tratar a mensagem de recusa:

O Administrador do Sistema de Destino não definiu uma hipótese legal padrão para o recebimento de trâmites por meio do Tramita.GOV.BR. Por esse motivo, o trâmite foi recusado.

-----

**Screenshots**
![image](https://user-images.githubusercontent.com/60577185/236055169-c02d27c2-5ee0-430a-b3b4-c2f91b42fac4.png)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: N/A
 - Navegador: N/A
 - Perfil do Usuário: N/A
 - Banco de dados: N/A
-----

**Informações adicionais**
N/A

-----

**Log de Erros**
N/A

**Comment by euviniciusmendonca** [comment]
Solicita-se um ajuste no texto de recusa, a seguir, a nova proposta:

O Administrador do Sistema de Destino não definiu uma hipótese legal padrão para o recebimento de trâmites por meio do Tramita.GOV.BR. Por esse motivo, o trâmite foi recusado.

**Comment by MatheusMarques80** [comment]
https://github.com/supergovbr/mod-sei-pen/assets/13146046/f9d2bb92-6078-42f0-a87a-093e03f7b4cc

**Comment by MatheusMarques80** [comment]
Removido a mensagem do core do super e adicionado no modulo pen.

**Comment by davidnascimento1618** [comment]
Prezado, @euviniciusmendonca, conforme teste funcional realizado, a solicitação de melhoria encontra-se implementada segundo o requisito descrito.
