### ISSUE TITLE
Melhoria da Mensagem - Alteração de Unidade de Mapeamento

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#277]
**Descreva o erro**
Ao alterar um mapeamento já existente para alguma unidade mapeada anteriormente acontece um erro no momento de salvar( veja o vídeo abaixo): Já existe um registro com a 'Unidade RH' para o código 151860.

-----

**Comportamento esperado**

Alterar a mensagem para deixar mais claro para o usuário o que está ocorrendo:

A unidade [Nome da Unidade] do sistema já está mapeada a unidade [Nome da Unidade] do Portal de Administração.

-----

**Screenshots**

https://user-images.githubusercontent.com/60577185/236710555-5d85a641-f02e-4814-ba59-23f9f78c8d8d.mp4

**Comment by mrglaydson** [comment]
Video teste:

https://github.com/supergovbr/mod-sei-pen/assets/11926294/500fb7a6-96f1-4f29-bde4-dbe0600e5d0e

**Comment by caduvieira** [comment]
@gicastephanou  qual o PR relacionado a essa issue?

**Comment by gicastephanou** [comment]
@caduvieira, realmente, a issue está sem uma PR relacionada. Já solicitei ao desenvolvedor e devolvi para ajustes necessários. Vou validar novamente após a associação.

**Comment by mrglaydson** [comment]
@gicastephanou relacionei o PR com a issue

**Comment by sergioadao** [comment]
@euviniciusmendonca , @allyson-barros e @mrglaydson : Ajuste de mensagem realizada com sucesso conforme print abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/6781f02e-dffa-4ed0-ba02-e1c52889a411)

**Comment by sergioadao** [comment]
@yuribitu Issue movida da Sprint 24 para Sprint 26;

**Comment by mateussbh** [comment]
Movido da sprint 26 para a 27.

**Comment by yurioliveiramgi** [comment]
> Video teste:
> issue.mp4

Pessoal, fiquei na dúvida entre a mensagem atual e a apresentada no vídeo.
No caso, deveria aparecer o nome da unidade e da unidade a quem ela está mapeada, correto? Conforme no vídeo.
A mensagem atual traz apenas o texto: "A unidade TESTE_1_1 do sistema já está mapeada com a unidade do Portal de Administração." Conforme 

> @euviniciusmendonca , @allyson-barros e @mrglaydson : Ajuste de mensagem realizada com sucesso conforme print abaixo:
> 
> ![image](https://user-images.githubusercontent.com/87815724/272997014-6781f02e-dffa-4ed0-ba02-e1c52889a411.png)

Seria isso, ou estou esquecendo algum detalhe definido nas reuniões?

**Comment by yurioliveiramgi** [comment]
@euviniciusmendonca, a mensagem apresentada informa o ID da unidade e não o nome. Vide imagens abaixo. Solicitar correção ou podemos deixar dessa forma?

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/7fafc06c-02f7-46f7-bfa3-fc5f5d7fb23b)

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/99a3ec4d-7e1a-4723-8a59-632678a4b1d7)

**Comment by yurioliveiramgi** [comment]
Em nova reunião, ficou definido que a issue #238 passa a compor a release, que será atualizada para 3.4.0. Com isso a mensagem necessitará fornecer os nomes das unidades e não mais os ID.

@euviniciusmendonca
