### ISSUE TITLE
Problema Hash - Inclusão de Nova Assinatura após Trâmite de Processo

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#285]
**Descreva o erro**
A inclusão de nova assinatura após um processo tramitar para outro órgão/ entidade.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1.  Um processo foi tramitado de A para B;
2.  Posteriormente, esse processo foi tramitado de B para A;
3.  No órgão A, um novo usuário assinou um documento tramitado anteriormente;
4. Ao tentrar tramitar novamente para B, gera-se um erro de hash.
-----

**Comportamento esperado**
Tratar to erro de modo permitir que o trâmite seja realizado com sucesso.

-----

**Screenshots**
N/A

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
N/A
-----

**Informações adicionais**
N/A
-----
**Log de Erros**
N/A

**Comment by yuribitu** [comment]
Issue duplicada com a Issue #289. Favor fecha-la

**Comment by MatheusMarques80** [comment]
@euviniciusmendonca fiz os passos mencionados na demanda e o processo foi tramitado normalmente.

Segue o passo a passo detalhado de como foi feito o teste:

1° Um processo foi tramitado de A para B com o **usuário x**;

2° Posteriormente, esse processo foi tramitado de B para A;

3° No órgão A, um novo usuário assinou um documento tramitado anteriormente **usuário y**;

4° Realizado o tramite novamente para B com o **usuário y**

**Comment by euviniciusmendonca** [comment]
Duplicada com a #289 ?

**Comment by MatheusMarques80** [comment]
@euviniciusmendonca dei uma olhada na issue mencionada pelo @yuribitu e o mesmo não tem referência com esse card.

Pode desconsiderar o comentário do Yuri.

**Comment by gicastephanou** [comment]
@MatheusMarques80 
Bom dia, tens um vídeo da reprodução dos passos mencionados na demanda, demonstrando que o processo foi tramitado normalmente?

**Comment by davidnascimento1618** [comment]
_Link_ da reunião explicando o problema e apresentando uma possível solução, junto ao PO: https://mtegovbr-my.sharepoint.com/:v:/g/personal/vinicius_mendonca_gestao_gov_br/Eb8p2YKcOXpCiaXiFptwyQMBHaD2534zhjIyCYEqWkGuYg

**Comment by gicastephanou** [comment]
Bom dia a todos,
Também fiz os passos mencionados na demanda e o processo foi tramitado normalmente.

**Comment by mateussbh** [comment]
Não houve alteração de código? Favor incluir o teste funcional validando a regra negocial, e a ausência do erro de hash.

**Comment by mateussbh** [comment]
Não foi feito nada nessa issue. A regra negocial da issue foi alterada para impedir que ocorram novas assinaturas em um mesmo documento após a tramitação do processo. Foi criada a issue [333 ](https://github.com/pengovbr/mod-sei-pen/issues/333) para implementar essa regra alterada, deixando essa issue 285 sem objeto. Assim, conforme alinhamento interno, vou concluir essa issue.

**Comment by mateussbh** [comment]
Movido da sprint 21 pra a 26.

**Comment by caduvieira** [comment]
Provavelmente o erro existia antes do 3.2.0. A partir da 3.2.0 é enviado o arquivo que deu sucesso. Alterações de assinatura eram ignoradas no segundo envio.
