### ISSUE TITLE
Criação da entrada Tramita.GOV.BR no menu principal

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#286]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
A melhoria está relacionada a necessidade negocial de centralizar todas as funcionalidades do Tramita.GOV.BR em uma única entrada do Menu Principal chamada Tramita.GOV.BR.

-----

**Descreva a solução que você gostaria**
Centralizar as duas funcionalidades abaixo nesse menu Tramita.GOV.BR e permitir que novas funcionalidades sejam incluídas no futuro.

![image](https://github.com/supergovbr/mod-sei-pen/assets/60577185/35cf194b-ae3b-400b-9e4b-933e0dc2f4f8)

-----

**Descreva alternativas que você considerou**
N/A

-----

**Contexto adicional**
N/A

**Comment by yuribitu** [comment]
Issue repetida com a #290.

**Comment by yurioliveiramgi** [comment]
Issue repetida com a #289 . 
Concluída e fechada.
