### ISSUE TITLE
Agrupar funcionalidades do Tramita.gov.br em um único item de menu

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#289]

**Comment by gledson-sousa** [comment]
Vídeo da implementação 
https://www.loom.com/share/ff75b0cad0ec4b68ada4186f2a4a5415

**Comment by mrglaydson** [comment]
Atividade concentrada na issue https://github.com/pengovbr/mod-sei-pen/issues/292 e resolvida no Pr https://github.com/pengovbr/mod-sei-pen/pull/418

**Comment by mateussbh** [comment]
Funcionalidade do bloco externa finalizada e testada com sucesso nas versões sei 4.0.12.15, 4.0.12 e 3.1.7, nos BDs mysql, oracle e sqlserver. 

Comentários foram majoritariamente centralizados nas issues 306 e 292.  O PR com os arquivos da funcionalidade (pré-release) é o https://github.com/pengovbr/mod-sei-pen/pull/424.
