### ISSUE TITLE
Criar novo perfil "Tramitador de Processos em Bloco"

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#290]

**Comment by gledson-sousa** [comment]
Vídeo da implementação 
https://www.loom.com/share/ff75b0cad0ec4b68ada4186f2a4a5415

**Comment by mrglaydson** [comment]
Atividade concentrada na issue #292 e resolvida no Pr https://github.com/pengovbr/mod-sei-pen/pull/418

**Comment by mateussbh** [comment]
Após levantamento do histórico, ficou suspensa esta criação deste perfil para a funcionalidade  de Bloco externo.
