### ISSUE TITLE
Adicionar situação Recusado para os processos individualmente enviados em Bloco

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#291]

**Comment by Mauro1706** [comment]
Segue evidência da funcionalidade

https://github.com/supergovbr/mod-sei-pen/assets/83025710/920f3987-f273-468e-8e78-7efa1acd5b47

**Comment by mateussbh** [comment]
Conforme alinhamento entre o PO e a equipe de qualidade, apesar de incomum, será habilitado o envio de somente um processo em um bloco externo. Portanto, a issue perde seu propósito.
