### ISSUE TITLE
Testes automatizados para Cadastro de Bloco de Trâmite Externo

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#292]
Teste está relacionado a issue #306

**Comment by euviniciusmendonca** [comment]
![ícone-em-aberto 1](https://github.com/pengovbr/mod-sei-pen/assets/60577185/5750227d-4678-4bc3-83c8-dae56aaca89f)
![ícone-em-processamento](https://github.com/pengovbr/mod-sei-pen/assets/60577185/7c7c0dc1-be5e-4dd8-a484-126ec3c42fe0)
![MicrosoftTeams-image (19)](https://github.com/pengovbr/mod-sei-pen/assets/60577185/e95b6fa1-74a6-409d-804a-f5a0c61c91cb)
![MicrosoftTeams-image (20)](https://github.com/pengovbr/mod-sei-pen/assets/60577185/204239c8-863c-4453-b300-3be7cc8c02e9)

Acima, os ícones dos status que estavam sem.

@mrglaydson

**Comment by euviniciusmendonca** [comment]
![ícone-em-aberto-2](https://github.com/pengovbr/mod-sei-pen/assets/60577185/3638262a-4634-40cc-9b4f-f221f716e740)
![MicrosoftTeams-image (21)](https://github.com/pengovbr/mod-sei-pen/assets/60577185/059933f3-0878-4d6f-be06-b7be3b97decd)

@mrglaydson, estou mudando o ícone de não iniciado.

**Comment by sergioadao** [comment]
@euviniciusmendonca @mateussbh .......Vinícius, segue sugestão e mensagem sobre número máximo de processos por bloco.


![Image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/94bd9446-cb28-4985-9390-9df59bfed1be)

**Comment by mateussbh** [comment]
Prezado @mrglaydson, favor prosseguir com a atualização dos ícones e ajuste no comportamento a seguir: "Ao receber um processo via bloco, no destinatário, ao incluir esse processo em novo bloco, ele já inicia na lista herdando o metadado "unidade destino" do tramite anterior, quando deveria zerar, pois trata-se de novo bloco de um processo já recebido."

**Comment by sergioadao** [comment]
@mrglaydson , @euviniciusmendonca e @mateussbh ....Após a realização de vários testes com a tentativa de trâmite de bloco de processos contendo processos RESTRITOS e PÚBLICOS, verificou-se que, independentemente da ordem na qual o processo do tipo RESTRITO aparece, nenhum processo do bloco é transmitido. Também percebi que a mensagem de erro trás apenas o número do processo. Mas, no caso de muitos processos em um bloco, um sequencial de ordem ajudaria a localização do processo.

**Comment by mateussbh** [comment]
Favor resolver o conflito do PR 418, @mrglaydson . OBrigado.

**Comment by mateussbh** [comment]
@mrglaydson , conforme alinhado, favor corrigir o título e alt do ícone de "em aberto", bem como corrigir o teste funcional de envio de processo no bloco (limitação de processos e carga). Obrigado.

**Comment by mateussbh** [comment]
Funcionalidade do bloco externa finalizada e testada com sucesso nas versões sei 4.0.12.15, 4.0.12 e 3.1.7, nos BDs mysql, oracle e sqlserver. 

Comentários foram majoritariamente centralizados nas issues 306 e 292.  O PR com os arquivos da funcionalidade (pré-release) é o https://github.com/pengovbr/mod-sei-pen/pull/424.
