### ISSUE TITLE
Atualização do ícone de Envio Externo

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#296]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Sempre fico frustrado quando [...]

-----

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você deseja que aconteça.

-----

**Descreva alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by davidnascimento1618** [comment]
Segue abaixo (em arquivo _.svg_) o ícone referente tanto ao 'Envio Externo de Processo', quanto para o 'Reenvio Externo de Processo', ficou definido que o mesmo servirá para as duas funcionalidades.

![envio_reenvio_externo_de_processo](https://github.com/supergovbr/mod-sei-pen/assets/87980947/0834c1dc-a41c-4f34-bfaa-93897c779e71)

**Comment by MatheusMarques80** [comment]
PR: https://github.com/supergovbr/mod-sei-pen/pull/312

**Comment by MatheusMarques80** [comment]
Closes: #312
