### ISSUE TITLE
Atualização do ícone do Cancelamento de Envio Externo

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#297]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Sempre fico frustrado quando [...]

-----

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você deseja que aconteça.

-----

**Descreva alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by davidnascimento1618** [comment]
Segue abaixo (em arquivo _.svg_) o ícone referente à funcionalidade: 'Cancelar de Trâmite Externo'.

![cancelar_tramitacao_externa](https://github.com/supergovbr/mod-sei-pen/assets/87980947/2b1512b9-c9c3-4cb9-950d-9efe15e60b6d)

**Comment by davidnascimento1618** [comment]
Testado em ambiente local e verificado que a melhoria em questão foi de fato implementada, conforme o _.gif_ abaixo:

![Atualização do ícone do Cancelamento de Envio Externo](https://github.com/supergovbr/mod-sei-pen/assets/87980947/bfb53d52-c6ea-458c-ae26-6086159fc303)


Obrigado
