### ISSUE TITLE
Módulo não é compatível com a versão 4.0.11 do SEI. 

### ISSUE THREAD

**Issue by ljsts01** [pengovbr/mod-sei-pen#304]
Ao executar o arquivo `verifica_instalacao_modulo_pen.php` após a instalação, recebi o erro abaixo:

```
PHP Fatal error:  Uncaught M▒dulo Integra▒▒o Processo Eletr▒nico Nacional - PEN (vers▒o 3.3.0) n▒o ▒ compat▒vel com a vers▒o 4.0.11 do SEI.
```

Aparentemente a versão 3.3.0 do módulo não é compatível com SEI 4.0.11.
Há alguma previsão de implementar essa compatibilidade ?

**Comment by euviniciusmendonca** [comment]
@caduvieira estou colocando na sprint atual.  O objetivo dessa issue é verificar a compatibilidade do módulo do Tramita.GOV.BR com a versão 4.0.11 do SEI.

**Comment by caduvieira** [comment]
- [ ] É preciso realizar os testes funcionais para todas as três bases de dados na versão 4.0.11.
- [ ] É preciso corrigir o testes ou o código conforme análise dos eventuais erros encontrados no teste acima.
- [ ] Uma vez corrigido é preciso realizar os testes funcionais para todas as três bases de dados na versão 3.1.7

**Comment by MatheusMarques80** [comment]
@caduvieira Foram feitos os testes e falharam somente 3 e dos três que falharam é necessário um terceiro certificado configurado. como é tratado os casos de unidades secundarias para os testes?

Hoje no mapeamento de unidades eu não consigo associar duas unidades para a mesma estrutura organizacional.

Em três testes que falharam é necessário o seguinte cenário: 
1° Protocolo tramitado da unidade TESTE do órgão A para o órgão B;
2° Recebimento do protocolo tramitado anteriormente na unidade TESTE do órgão B;
3° Tramitar do órgão B para a unidade TESTE 1.

Nesse caso eu não irei receber o tramite no órgão A na unidade TESTE 1 pois eu não tenho uma estrutura organizacional cadastrada.

**Comment by MatheusMarques80** [comment]
Depois de atualizado o phpunit.xml com a unidade secundaria devidamente cadastrada todos os testes foram executados com sucesso:



![Image](https://github.com/supergovbr/mod-sei-pen/assets/13146046/936e65b2-6a27-4070-abc0-e82c98348b59)



Vídeo de uma parte da execução dos testes:




https://github.com/supergovbr/mod-sei-pen/assets/13146046/76ea6ac7-88c4-44be-b0ea-b61025aae154
