### ISSUE TITLE
Atualização do ícone de 'Consultar Recibos'.

### ISSUE THREAD

**Issue by davidnascimento1618** [pengovbr/mod-sei-pen#308]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Atualização do ícone de 'Consultar Recibos', para manter o padrão do Tramita, com os demais ícones do _menu_ superior da tela de criação de processo.

-----

**Descreva a solução que você gostaria**

Ícone deve ter como base a logo do Tramita (duas setinhas em direções contrárias).

-----

**Comment by davidnascimento1618** [comment]
Segue abaixo (em arquivo _.svg_) o ícone referente à funcionalidade: 'Consultar Recibos'.

![consultar_recibos](https://github.com/supergovbr/mod-sei-pen/assets/87980947/e12936d2-d9f8-42ca-bbff-f46e2c544bed)

**Comment by MatheusMarques80** [comment]
PR: https://github.com/supergovbr/mod-sei-pen/pull/313
