### ISSUE TITLE
undefined method BancoSip::setBolScript()

### ISSUE THREAD

**Issue by soldate** [pengovbr/mod-sei-pen#315]
No SEI 4.1 o BancoSip.php não tem mais o método setBolScript() e o script de atualização do PEN (sip) 3.3.0 espera que tenha..

PHP Fatal error:  Uncaught Error: Call to undefined method BancoSip::setBolScript() in /opt/sip/scripts/mod-pen/sip_atualizar_versao_modulo_pen.php:1826

**Comment by caduvieira** [comment]
Não há, no momento, suporte para a versão do SEI 4.1

**Comment by gsdiniz** [comment]
há previsão de compatibilidade de versão 4.1?

**Comment by caduvieira** [comment]
A versão 3.6.1 do módulo é compatível com o 4.1.1
