### ISSUE TITLE
Erro 'cabecalho.propriedadesAdicionais[0].valor' não pode ser vazio

### ISSUE THREAD

**Issue by caduvieira** [pengovbr/mod-sei-pen#328]
**Descreva o erro**
Erro 'cabecalho.propriedadesAdicionais[0].valor' não pode ser vazio Erro 'cabecalho.propriedadesAdicionais[5].valor' não pode ser vazio. Isso ocorre pois o htmlspecialchars retorna uma string vazia caso encontre um caractere com encoding errado.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Com um processo com um assunto com caractere inválido.
2. Tente enviar o processo
3. Veja o erro

-----

**Comportamento esperado**
Envio do processo com sucesso.

-----

**Screenshots**
![image](https://github.com/supergovbr/mod-sei-pen/assets/3831408/086361c5-1b00-40a1-af0c-6dd8af13fbc3)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: 3.3.0
 - Navegador: qualquer
 - Perfil do Usuário: qualquer
 - Banco de dados: Qualquer
-----

**Informações adicionais**

-----
**Log de Erros**
Não aparece

**Comment by Mauro1706** [comment]
@caduvieira poderia melhorar a descrição da tarefa de como chegar no erro, qual o caracter especial e o assunto se e o campo Tipos de Assunto?

**Comment by caduvieira** [comment]
Mauro já tem um PR associado que mandei. A solução não deu certo?

**Comment by gicastephanou** [comment]
@Mauro1706, reiterando a mensagem do Cadu, O PR associado não deu certo?

**Comment by Mauro1706** [comment]
@gicastephanou  @caduvieira foi perguntado (aqui)[https://github.com/pengovbr/mod-sei-pen/issues/328#issuecomment-1671478569] mais informações pois não consegui gerar o erro descrito depois disso foi realizado a implementação pelo @caduvieira e foi pedido para colocar a issue em revisão, portanto não sei dizer se está funcionalidade foi corrida ou não!

**Comment by gicastephanou** [comment]
Boa tarde @Mauro1706, vamos precisar, então, fazer o debug e forçar esse char errado do assunto. Vou tentar debugar também.

**Comment by Mauro1706** [comment]
Boa, tarde @gicastephanou fiz teste com praticamente todos os caracteres especiais e o código passou, creio que o problema foi solucionado com o PR do @caduvieira

**Comment by mateussbh** [comment]
Erro simulado e solução testada. 
![Screenshot from 2024-05-09 20-01-38](https://github.com/pengovbr/mod-sei-pen/assets/3789823/f5dbee7d-bbfe-4795-9b5a-bb9ba391b0e8)

Após aplicação da solução, o erro não apareceu novamente no teste de um processo com texto da descrição do processo grande, e com caracteres especiais.
![Screenshot from 2024-05-09 20-22-01](https://github.com/pengovbr/mod-sei-pen/assets/3789823/7ea74524-c8ed-4f44-9842-e1736f76f854)
