### ISSUE TITLE
O modulo não consegue tramitar um processo muito grande

### ISSUE THREAD

**Issue by dhiego28** [pengovbr/mod-sei-pen#331]
**Erro**
-----

O módulo não consegue tramitar um processo com diversos documentos e de um tamanho de processo grande. 
-----

**Contexto da falha:**
 - Versão do sistema: Módulo PEN versão 3.3.0
 - Banco de dados: Oracle

-----
**Log de Erros**
00015 - [25/07/2023 11:01:02] (22) [MONITORAMENTO] Timeout de monitoramento de 300 segundos do serviço de pendências alcançado
00016 - [25/07/2023 11:01:02] (22) [MONITORAMENTO] Reiniciando monitoramento de pendências em 30 segundos
2023-07-25 11:01:05,285 INFO exited: processamento_tarefas_pen_00 (exit status 0; expected)
2023-07-25 11:01:06,288 INFO spawned: 'processamento_tarefas_pen_00' with pid 27

**Comment by yurioliveiramgi** [comment]
Issue concluída, pois o problema relatado pode facilmente ser resolvido através do aumento do Timeout pelo administrador do sistema. Além disso, através da funcionalidade de envio parcial de trâmite.
