### ISSUE TITLE
Melhoria de Mensagem: Transação não autorizada, pois o sistema não é responsável pela estrutura organizacional remetente

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#332]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
A mensagem Transação não autorizada, pois o sistema não é responsável pela estrutura organizacional remetente não está clara e dificulta a análise pelo Gestor de Protocolo. 

Qual é o cenário para geração do erro?

Um Gestor do órgão A utilizar unidades de outro órgão no Mapeamento de Unidades ou de outro repositório. Depois do mapeamento errado, realizar uma tentativa de trâmite. 

-----

**Descreva a solução que você gostaria**
Nova Proposta de Mensagem:

Por favor, observe o seguinte procedimento para realizar o mapeamento adequado: Acesse a funcionalidade Administração, em seguida selecione Tramita.GOV.BR e, por fim, proceda ao mapeamento utilizando somente as unidades pertinentes ao seu órgão/entidade na funcionalidade Mapeamento de Unidades. Certifique-se de seguir esse processo para garantir a correta execução do mapeamento.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by MatheusMarques80** [comment]
https://github.com/supergovbr/mod-sei-pen/assets/13146046/76859375-d83e-4f77-9439-01abf3111987

**Comment by caduvieira** [comment]
@euviniciusmendonca  essa mensagem original vem do Tramita.gov.br e não é mensagem do módulo do tramita.

O Matheus resolveu capturando o erro que vem do tramita e alterando a mensagem. Mas isso não corrige para todos os casos e se essa mensagem for alterada no tramita esse comportamento vai ser quebrado. 

Não seria melhor trocar no próprio tramita.gov.br?

**Comment by sergioadao** [comment]
@MatheusMarques80, favor corrigir o que está descrito no [comentário](https://github.com/pengovbr/mod-sei-pen/pull/334#pullrequestreview-1656164210) do PR em questão.

**Comment by sergioadao** [comment]
@MatheusMarques80 , favor corrigir o que está descrito no [comentário](https://github.com/pengovbr/mod-sei-pen/pull/334#pullrequestreview-1661873755) do PR em questão.

**Comment by sergioadao** [comment]
@mrglaydson  Mensagem implementada com sucesso. [Verificar aqui](https://github.com/pengovbr/mod-sei-pen/pull/334#pullrequestreview-1699725127).

**Comment by mateussbh** [comment]
Movido da sprint 21 para a 27.

**Comment by yurioliveiramgi** [comment]
Olá pessoal, na verificação realizada foi possível identificar a necessidade de uma correção pontual.
Acredito que seja bem simples e esteja relacionada à ordenação (hierarquia) das validações.
No vídeo em anexo a unidade utilizada (pertencente ao órgão5) foi mapeada três vezes:
1. Mapeada para o órgão6 (tempo 0:18 no vídeo)
2. Mapeada para Secretaria Teste (tempo 1:41 no vídeo)
3. Mapeada para o órgão6 (tempo 3:10 no vídeo)

Em todas as tentativas de trâmite externo o processo foi remetido para órgão diferente do órgão5. 
Nas situações 2 e 3, a mensagem esperada foi apresentada em tela. Contudo, na situação 1 a mensagem de erro referente ao trâmite de processos dentro da mesma estrutura organizacional prevaleceu em relação à mensagem esperada (tempo 1:13 do vídeo). 

Acontece que na situação 1, por mais que a unidade esteja mapeada para o órgão6, e o órgão de destino seja o órgão6, o mapeamento foi realizado erroneamente por meio do órgão5, de forma que a mensagem esperada seria de transação autorizada motivada pelo assunto dessa issue, e não como se fosse o órgão6 tentando tramitar o processo internamente para ele mesmo.

A tempo, comunico que na mensagem, como o portal ainda não foi atualizado, deve ser alterado no texto a parte "Tramita GOV.BR" para "Processo Eletrônico Nacional".

Espero ter pontuado de forma satisfatória essa questão.
Dúvidas, sigo à disposição.

Vídeo: https://mtegovbr-my.sharepoint.com/:v:/g/personal/yuri_rodrigues_gestao_gov_br/EaC_r-k6bQ1GsW2zlgqh4VYBudeMd8lvc7J8DViFyq18Hw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=8FaQS5

**Comment by caduvieira** [comment]
> Acontece que na situação 1, por mais que a unidade esteja mapeada para o órgão6, e o órgão de destino seja o órgão6, o mapeamento foi realizado erroneamente por meio do órgão5, de forma que a mensagem esperada seria de transação autorizada motivada pelo assunto dessa issue, e não como se fosse o órgão6 tentando tramitar o processo internamente para ele mesmo.
Nesse caso seria outra issue.

**Comment by yurioliveiramgi** [comment]
Certo, vou abrir aqui então. Citarei essa como referência para não ter que justificar toda a lógica.
Nesse sentido, @euviniciusmendonca , estou concluindo essa issue.
