### ISSUE TITLE
Processo Desatualizado - Ausência de Assinatura

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#333]
**Descreva o erro**

No destino, o documento fica desatualizado sem a inclusão da nova assinatura no cenário abaixo:

Ao enviar novamente um processo por meio da plataforma, caso uma nova assinatura seja incluída no documento.

-----

**Para reproduzir**

Passos para reproduzir o comportamento:

1.  Enviar um processo de A para B (com um documento assinado por usuário X);
2.  Depois devolver o processo de B para A;
3.  No órgão A, um novo usuário (usuário Y), deverá assinar este mesmo documento, já tramitado pela plataforma e, reenviar o processo para o órgão B;
4.  Ao receber o processo em B, verifica-se que o documento não possui a nova assinatura (do usuário Y), ou seja, em cada órgão o documento possui quantidade de assinaturas diferentes.

-----

**Comportamento esperado**

Identificar a melhor maneira de atualizar o documento no destino.

-----

**Screenshots**

**Assinatura no org-1 (órgão A):**

![Assinatura órgão A](https://github.com/pengovbr/mod-sei-pen/assets/87980947/b8953acb-e28e-48df-81ee-7d6bf9005397)

**Assinatura no org-2 (órgão B):**

![Assinatura órgão B](https://github.com/pengovbr/mod-sei-pen/assets/87980947/fc76bdca-e0d9-448c-a3b7-240a0a89e2a6)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
Não se aplica.
-----

**Informações adicionais**
Não se aplica.

-----
**Log de Erros**
Não se aplica.

**Comment by MatheusMarques80** [comment]
Ao tentar tramitar o documento que contem novas assinaturas está ocorrendo um erro de hash por parte do barramento.

@caduvieira e @davidnascimento1618 podemos fazer um alinhamento técnico referente a esse erro?

![Image](https://github.com/pengovbr/mod-sei-pen/assets/13146046/b4264368-97d0-4275-b74c-6c6822bee4e4)

**Comment by MatheusMarques80** [comment]
Em conversa com @caduvieira e @euviniciusmendonca foi acordado em deixar essa issue para uma nova análise.

**Comment by caduvieira** [comment]
@euviniciusmendonca eu sugiro bloquear a assinatura em documentos já tramitados usando os dois pontos de extensão prepararAssinaturaDocumento e assinarDocumento. O prepararAssinaturaDocumento é usado quando há outros tipos de assinatura como certificado digital. O assinarDocumento para a assinatura com a senha. Mas o prepararAssinaturaDocumento só está presente depois da 4.0.2. Então até a 4.0.2 as pessoas podem 'enganar' esse bloqueio de assinatura se usarem um certificado digital para assinar.

**Comment by euviniciusmendonca** [comment]
@caduvieira após alinhamento interno realizado por meio de uma reunião, vamos impedir a inclusão de novas assinaturas em *documentos anteriormente tramitados*.

**Comment by MatheusMarques80** [comment]
Após um alinhamento juntamente com o @caduvieira não será mais necessário a alteração na regra do super.

Será utilizado os dois pontos de extensões mencionados para a tratativa de impedimento de novas assinaturas em documentos anteriormente tramitados.

**Comment by caduvieira** [comment]
Não há necessidade mapeada de alterar regra no SEI.

**Comment by MatheusMarques80** [comment]
Em documentos que foram tramitados anteriormente não será permitida a assinatura de novos usuários.

Segue vídeo com a implementação

https://github.com/pengovbr/mod-sei-pen/assets/13146046/70dcb395-734e-4187-a276-6d96939f9466


Teste:  make teste=TramiteProcessoContendoDocumentoExternoAssinadoTest test-functional


![Image](https://github.com/pengovbr/mod-sei-pen/assets/13146046/afe045c6-8727-427c-9b12-1d858b60bba5)

**Comment by caduvieira** [comment]
@gicastephanou favor verificar a mensagem no PR

**Comment by carlosevmelo** [comment]
Prezados, bom dia.

Adicionando na presente Issue, o comentário realizado no PR #352  [PR #352](https://github.com/pengovbr/mod-sei-pen/pull/352) e acrescentando o pedido de corrigir o conflito encontrado pelo PHP_CodeSniffer:

![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/ef43fc9b-25c9-4dbb-a00a-aa3b1a4d43fd)


Após análise do código fonte dos testes, foi identificado que existem querys SQL, conforme figura abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/31a192db-a6b8-476d-a442-dd5afe887462)


Por gentileza, adotar como boas práticas a utilização dos Fixtures existentes, ou se necessário, criar novos conforme figura abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/d6c917df-af28-42cd-b92a-7cbee81ac1b6)

**Comment by yurioliveiramgi** [comment]
Em reunião realizada na data de hoje ficou decidido que:
- [ ] Não será permitida a inclusão de uma nova assinatura em documentos já tramitados via Tramita GOB.BR;
- [ ] Ao tentar assinar um documento já tramitado externamente, o usuário deverá ser informado que essa ação não é permitida conforme mensagem que segue:
"Prezado(a) usuário(a) esse documento já foi tramitado externamente via Tramita GOV.BR. Por esse motivo, este documento não pode receber uma nova assinatura."
- [ ] A mensagem deverá aparecer ao usuário após clicar em "assinar".


Para conhecimento e validação @euviniciusmendonca , @mateussbh , @caduvieira , @Mauro1706

**Comment by Mauro1706** [comment]
Resolvido no Pull Request https://github.com/pengovbr/mod-sei-pen/pull/445

https://github.com/pengovbr/mod-sei-pen/assets/83025710/a6670b23-fb02-46c8-99a2-588f83415d9f

**Comment by euviniciusmendonca** [comment]
@mateussbh @caduvieira eu não consegui simular o novo comportamento na versão 3.6.0. Foi confirmada a presença dessa issue na release?

**Comment by mateussbh** [comment]
> @mateussbh @caduvieira eu não consegui simular o novo comportamento na versão 3.6.0. Foi confirmada a presença dessa issue na release?

@euviniciusmendonca Apesar de testada e validada na 3.6.0, ela ficou de fora do merge, pois o merge dos PRs foi refeito e faltou incluir ela. Estou incluindo ela no pacote da 3.7.0.
