### ISSUE TITLE
Melhoria da Mensagem - Unidade [Estrutura: XXXXXX] não configurada para receber processos externos no sistema de destino.

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#337]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Ao enviar um processo de um órgão para outro, o mesmo pode ser recusado pelo seguinte motivo:

Unidade [Estrutura: XXXX] não configurada para receber processos externos no sistema de destino.

Ocorre quando a unidade destino não está configurada para receber processos (configuração realizada no Mapeamento de Unidade do módulo).

-----

**Descreva a solução que você gostaria**
Tratar a mensagem para deixar claro qual é a unidade:

<s>O processo/documento avulso foi recusado:</s> A Unidade [Nome da Unidade cadastrada no Portal de Administração] não está configurada para receber processos/documentos avulsos por meio da plataforma. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by Mauro1706** [comment]
Segue evidência de funcionalidade:

https://github.com/supergovbr/mod-sei-pen/assets/83025710/bb037de9-3aea-4f4f-a03b-d607e626db3f

**Comment by mateussbh** [comment]
Movido da sprint 22 para a 26.

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, favor realizar os [ajustes elencados](https://github.com/pengovbr/mod-sei-pen/pull/345#pullrequestreview-1666261714) no _pull request_ relacionado.

**Comment by davidnascimento1618** [comment]
@Mauro1706,

Realizar os seguintes ajustes no texto da mensagem: 

**1.** Ajustar a barra que separa processo de documento avulso, posicionando-a junta da palavra documento, ou seja, _"O processo/documento avulso"..._. ao invés de:  _..."O processo/ documento avulso"..._;

**2.** Ajustar a barra que separa processo de documento avulso, posicionando-a junta da palavra documento, ou seja, _..."receber processos/documentos avulsos"..._. ao invés de:  _..." receber processos/ documentos avulsos"..._;

**3.** Colocar um ponto final no final do último período da mensagem, ou seja, _..."Portanto, não é um erro."_, ao invés de: _..."Portanto, não é um erro"_

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/e7ae6376-d269-47f8-8b4f-0992a07f6bb6)

**Comment by Mauro1706** [comment]
@davidnascimento1618 ajustes realizados para essa solicitação https://github.com/pengovbr/mod-sei-pen/issues/337#issuecomment-1780449413
![image](https://github.com/pengovbr/mod-sei-pen/assets/83025710/a8296b20-9f45-4400-9e40-51198c9fbc3d)

**Comment by davidnascimento1618** [comment]
Prezados @euviniciusmendonca e @yurioliveiramgi, foi verificado que, tanto na versão mais atual, como nas versões do SEI 3 e SEI 4, a nova mensagem já está sendo exibida, conforme a apresentada no requisito:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/cdd53bbd-6e8e-4679-89d6-149a9e94a131)
