### ISSUE TITLE
Melhoria da Mensagem - Processo recusado devido a existência de documento em formato teste não permitido pelo sistema.

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#338]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Ao enviar um processo de um órgão para outro, o mesmo pode ser recusado pelo seguinte motivo:

Processo recusado devido a existência de documento em formato [Nome do Formato4] não permitido pelo sistema.

Lembre-se que cada Administrador do SEI pode definir quais formatos são aceitos no sistema(ver Administração --> Extensões de Arquivos Permitidas
).

-----

**Descreva a solução que você gostaria**

Tratar a mensagem para deixar claro:

<s>O processo/ documento avulso foi recusado:</s> O formato [Nome do Formato] não é permitido pelo sistema de destino. Lembre-se que cada órgão/ entidade tem autonomia na definição de quantos e quais formatos de arquivo são aceitos pelo seu sistema. OBS: A recusa é um das três formas de conclusão de trâmite. Portanto, não é um erro.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by mrglaydson** [comment]
Vídeo evidencia: 
https://drive.google.com/file/d/1hRYcihuD2tp9mBiMGSIw4DBuQ_DEhY78/view?usp=sharing

**Comment by davidnascimento1618** [comment]
_Issue_ movida da _sprint_ 22 para a 26, no intuito de ser revalidada.

**Comment by davidnascimento1618** [comment]
Prezado @euviniciusmendonca, foi verificado que tanto no SUPER, como no SEI 3 e SEI 4, a nova mensagem já está sendo exibida, conforme a ilustração abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/2775e6c4-c11b-4511-926c-f1ff22396430)

**Comment by davidnascimento1618** [comment]
Prezados @euviniciusmendonca e @yurioliveiramgi, foi verificado que, tanto na versão mais atual, como nas versões do SEI 3 e SEI 4, a nova mensagem já está sendo exibida, conforme a que foi apresentada no requisito:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/5b8b0541-e375-4f57-839d-38460e87e810)

**Comment by mateussbh** [comment]
Movido da sprint 22 para a 27.

**Comment by yurioliveiramgi** [comment]
Corrigir ortografia na mensagem apresentada conforme evidência abaixo.

Na terceira linha, onde se lê " A recusa é **um** das três formas...", corrija-se para "A recusa é **uma** das três formas..."

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/5cfc5538-b1e9-4c52-8e38-64f5f1df9636)

**Comment by yurioliveiramgi** [comment]
Apontamento corrigido.
