### ISSUE TITLE
Melhoria da Mensagem - Já existe um processo utilizando o número de protocolo XXXXXX.XXXXXX/XXXXXX -XX.

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#339]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Ao enviar um processo de um órgão para outro, o mesmo pode ser recusado pelo seguinte motivo:

Já existe um processo utilizando o número de protocolo XXXXXX.XXXXXX/XXXXXX -XX.

Ocorre quando o órgão destino recebe porn meio da plataforma um processo com a mesma numeração e no qual foi cadastrado manualmente no sistema ou não foi enviado anteriormente por meio da plataforma.

-----

**Descreva a solução que você gostaria**
Tratar a mensagem para deixar claro qual é a unidade:

<s>O processo/ documento avulso foi recusado:</s> Um processo com o número de protocolo XXXXXX.XXXXXX/XXXXXX -XX já existe no sistema de destino. OBS: A recusa é um das três formas de conclusão de trâmite. Portanto, não é um erro.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by michael-ferreira2022** [comment]
Mensagem alterada. Porém o arquivo onde encontra-se essa mensagem está no projeto SEI. É possível fazer o PR para o projeto ao qual pertence esta mensagem? Trata-se apenas de uma atualização na mensagem que já existia. @davidnascimento1618

**Comment by sergioadao** [comment]
@michael-ferreira2022, favor corrigir o conflito conforme este comentário [aqui](https://github.com/pengovbr/mod-sei-pen/pull/356#pullrequestreview-1658274497).

**Comment by sergioadao** [comment]
@yuribitu issue movida da Sprint 22 para Sprint 26;

**Comment by sergioadao** [comment]
Solicitação ainda pendente conforme [comentário](https://github.com/pengovbr/mod-sei-pen/pull/356#pullrequestreview-1685856676).

**Comment by sergioadao** [comment]
@mrglaydson, mensagem solicitada não implementada:

O processo/ documento avulso foi recusado: Um processo com o número de protocolo XXXXXX.XXXXXX/XXXXXX -XX já existe no sistema de destino. OBS: A recusa é um das três formas de conclusão de trâmite. Portanto, não é um erro.

Segue [comentário](https://github.com/pengovbr/mod-sei-pen/pull/356#pullrequestreview-1697982235).

**Comment by Mauro1706** [comment]
resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/390
