### ISSUE TITLE
Melhoria da Mensagem - O tamanho máximo permitido para arquivos XXXXX é XXXMb.

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#340]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Ao enviar um processo de um órgão para outro, o mesmo pode ser recusado pelo seguinte motivo:

O tamanho máximo permitido para arquivos XXXXXXX é XXXMb

O sistema de destino define o tamanho máximo de um documento de um processo. No caso do SEI é definido em Administração --> Extensões de Arquivos Permitidas.

**Descreva a solução que você gostaria**
Tratar a mensagem para deixar mais clara:

<s>O processo/ documento avulso foi recusado:</s> O tamanho máximo permitido para arquivo XXXXX é XXXMb. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by mrglaydson** [comment]
@davidnascimento1618  esse card está atrelado ao módulo sei-pen, porém essa validação em especifico, é feita no core do Super/Sei. No arquivo DocumentoINT.php



![Image](https://github.com/supergovbr/mod-sei-pen/assets/11926294/8f8b831e-89d4-495e-a411-ab681993e768)

**Comment by davidnascimento1618** [comment]
> @davidnascimento1618 esse card está atrelado ao módulo sei-pen, porém essa validação em especifico, é feita no core do Super/Sei. No arquivo DocumentoINT.php
> 
> ![Image](https://user-images.githubusercontent.com/11926294/259413551-8f8b831e-89d4-495e-a411-ab681993e768.png)

@caduvieira e @higodf, podemos marcar uma agenda para orientar melhor a _First_ sobre esta alteração das mensagens? 
Lembrando que há também outra _issue_ que está sendo impactada além desta, que seria a #339.

**Comment by caduvieira** [comment]
Pode marcar

**Comment by mateussbh** [comment]
Movido da sprint 22 para a 26.

**Comment by mateussbh** [comment]
Prezado, a mensagem permanece a mesma. Foi incluído um PR que se trata da issue 343 (sobre tamanho máximo geral permitido para documentos externos) e não sobre anexos de um  tipo X, limitados a Y Mb .  Favor atualizar o PR, por favor.

**Comment by mateussbh** [comment]
Prezado, a mensagem ainda não está conforme a solicitação. 

Como foi solicitada:
O processo/documento avulso foi recusado: O tamanho máximo permitido para arquivo XXXXX é XXXMb. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

Como a msg está:
O processo foi recusado pelo orgão [órgão] pelo seguinte motivo: O tamanho máximo permitido para arquivos xxxx é xxxx Mb. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

Favor atualizar a primeira parte da msg, para que fique conforme o solicitado.

![image](https://github.com/pengovbr/mod-sei-pen/assets/3789823/d5eb8464-425c-497a-94a0-aaa938c2577c)

**Comment by mrglaydson** [comment]
@euviniciusmendonca @mateussbh 

O padrão de recusa de processo do modulo mod-sei-pen, segue essa estrutura: "_O Processo foi recusado pelo o órgão [NOME_ORGÃO_DESTINATÁRIO] pelo o seguinte motivo: [...]_"

Onde [...] é a mensagem personalizada para a edição.

Então a mensagem final para esse card ficou :

Como foi solicitada:
**O processo/documento avulso foi recusado:** O tamanho máximo permitido para arquivo XXXXX é XXXMb. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

Como a msg está:
**O processo foi recusado pelo orgão [órgão] pelo seguinte motivo:** O tamanho máximo permitido para arquivos xxxx é xxxx Mb. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

@euviniciusmendonca a mensagem pode ficar dessa forma ?

Obs: É possível deixar a mensagem 100% como solicitada, o texto em negrito a base no padrão do modulo para tratamento de recusa.

**Comment by mateussbh** [comment]
Conforme informado [aqui](https://github.com/pengovbr/mod-sei-pen/pull/376#issuecomment-1781784875), houve um alinhamento para que permanecesse a msg padrão de recusa e fosse atualizada/customizada a mensagem após os dois pontos.

Mensagem validada:
![image](https://github.com/pengovbr/mod-sei-pen/assets/3789823/c9ab9b52-4aad-426d-8357-4b3690f6839b)
