### ISSUE TITLE
Melhoria da Mensagem - Documento do tipo XXXXX  não está mapeado

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#342]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Ao enviar um processo de um órgão para outro, o mesmo pode ser recusado pelo seguinte motivo:

Documento do tipo XXXXX  não está mapeado

A ausência de mapeamento do tipo de documento na funcionalidade Administração --> Processo Eletrônico Nacional --> Mapeamento de Tipos de Documentos --> Recebimento.

-----

**Descreva a solução que você gostaria**

Tratar a mensagem para deixar mais clara:

<s>O processo/ documento avulso foi recusado:</s> O Documento do tipo XXXXX  não está mapeado para recebimento no sistema de destino. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by gicastephanou** [comment]
Boa tarde @mrglaydson,

Podes anexar o vídeo evidência da solução?

**Comment by mrglaydson** [comment]
@gicastephanou segue link do vídeo
[(https://drive.google.com/file/d/1NkPclCpZmNxe6QijWzbwVcOeXz8gsqMZ/view?usp=sharing)**](https://drive.google.com/file/d/1NkPclCpZmNxe6QijWzbwVcOeXz8gsqMZ/view?usp=sharing)

**Comment by davidnascimento1618** [comment]
_Issue_ movida da _sprint_ 22 para a 26, no intuito de ser revalidada.

**Comment by davidnascimento1618** [comment]
Prezado @euviniciusmendonca, foi verificado que, tanto no SUPER, como no SEI 3 e SEI 4, a nova mensagem já está sendo exibida, conforme a ilustração abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/c1bc96ed-2662-40e8-af04-db12a38af9fa)

**Comment by davidnascimento1618** [comment]
Prezados @euviniciusmendonca e @yurioliveiramgi, foi verificado que, tanto na versão mais atual, como nas versões do SEI 3 e SEI 4, a nova mensagem já está sendo exibida, conforme a que foi apresentada no requisito:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/dac26dc7-eeeb-4936-bf94-c14d6e5686a8)

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/5b2a57ac-40ed-4a22-912c-dd6695bb8c3e)

**Comment by mateussbh** [comment]
Movido da sprint 24 para a 27.

**Comment by yurioliveiramgi** [comment]
Corrigir ortografia na mensagem apresentada conforme evidência abaixo.

Na terceira linha, onde se lê " A recusa é **um** das três formas...", corrija-se para "A recusa é **uma** das três formas..."

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/5cfc5538-b1e9-4c52-8e38-64f5f1df9636)
