### ISSUE TITLE
Melhoria da Mensagem - O tamanho máximo geral permitido para documentos externos é XXXX Mb.

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#343]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Ao enviar um processo de um órgão para outro, o mesmo pode ser recusado pelo seguinte motivo:

O tamanho máximo geral permitido para documentos externos é XXXX Mb.

O administradores do SEI definem o tamanho máximo de um documento por meio de um parâmetro: SEI_TAM_MB_DOC_EXTERNO.
O parâmetro é acessado por meio de Infra --> Parâmetros.

-----

**Descreva a solução que você gostaria**

Tratar a mensagem para deixar mais clara:

<s>O processo/ documento avulso foi recusado:</s> O tamanho máximo geral permitido para documentos externos é XXXX Mb. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by mrglaydson** [comment]
Vídeo evidencia:

https://drive.google.com/file/d/1RLMxI5_H9MQcxsqqT1R-PpF57ZbxuaFO/view?usp=sharing

**Comment by sergioadao** [comment]
Prezado @mrglaydson, verificar o comentário descrito [aqui](https://github.com/pengovbr/mod-sei-pen/pull/353#pullrequestreview-1658476379).

**Comment by sergioadao** [comment]
@yuribitu issue movida da Sprint 22 para Sprint 26;

**Comment by sergioadao** [comment]
@mrglaydson , mensagem solicitada ainda não implementada: 

O processo/ documento avulso foi recusado: O tamanho máximo geral permitido para documentos externos é XXXX Mb. OBS: A recusa é uma das três formas de conclusão de trâmite. Portanto, não é um erro.

Segue [comentário](https://github.com/pengovbr/mod-sei-pen/pull/353#pullrequestreview-1697322074).

**Comment by sergioadao** [comment]
@mrglaydson.....Mensagem implementada conforme solicitado....para visualizar [clique aqui.](https://github.com/pengovbr/mod-sei-pen/pull/353#pullrequestreview-1701796189)

**Comment by yurioliveiramgi** [comment]
A mensagem apresentada não apresenta a observação no texto, conforme evidência a seguir.

É necessário que haja a inserção do texto "OBS: A recusa é uma das três formas de conclusão do trâmite. Portanto, não é uma recusa."

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/5a62a9b4-24bf-48fc-8eb0-50489292488e)

**Comment by yurioliveiramgi** [comment]
Apontamento corrigido.
