### ISSUE TITLE
Nova Funcionalidade - Mapeamento de Envio Parcial

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#344]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Atualmente, a configuração do envio parcial é realizado diretamente no arquivo de configuração do módulo( https://github.com/supergovbr/mod-sei-pen/blob/master/src/config/ConfiguracaoModPEN.exemplo.php#L96). A seguir, um exemplo:

  // "EnviarApenasComponentesDigitaisPendentes" => array(
              //     "1" => array(   // 1 = Poder Executivo Federal
              //         "1500330",  // Id de estrutura de unidade X do Poder Executivo Federal
              //         "1500440"   // Id de estrutura de unidade Y do Poder Executivo Federal
              //     ),
              //     "21" => array(   // 21 = Poder Legislativo Federal
              //         "4600330",   // Id de estrutura de unidade X do Poder Legislativo Federal
              //         "4600440"    // Id de estrutura de unidade Y do Poder Legislativo Federal
              //     )
              // )
          )

Caso o gestor tenha a necessidade do cadastro de nova unidade para envio parcial é preciso entrar em contato com a TI e realizar a alteração diretamente no arquivo de configuração.

-----

**Descreva a solução que você gostaria**
A criação da Nova Funcionalidade Mapeamento de Envio Parcial( Semelhante a funcionalidade Mapeamento de Unidades):
Cadastrar
Listar

O Cadastro é composto dos seguintes campos: Repositório(Combo) e Campo livre para escolher a unidade permitindo a busca por vários padrões de ocorrência.

O listar é semelhante ao listar do Mapeamento de Unidades. Na tabela exibir ID do Repositório, Nome do Repositório, ID da Unidade e Nome da Unidade.

O objetivo do mapeamento é facilitar a configuração do envio parcial e deixar os gestores independentes da área de TI.

-----

**Descreva alternativas que você considerou**
Não se aplica.
-----

**Contexto adicional**
Não se aplica.

**Comment by caduvieira** [comment]
Isso não pode ficar em um só nó da máquina. Deve ficar em todos os nós

**Comment by gicastephanou** [comment]
Olá @Mauro1706, vi que foi a criado o PR 351, mas não foi associado a issue 344.

**Comment by Mauro1706** [comment]
Olá @gicastephanou tentei vincular o PR a issue mais não consegui da forma que foi indicado com comentário closes, poderia fazer esse vinculo direto na tarefa?

![image](https://github.com/pengovbr/mod-sei-pen/assets/83025710/bbe7f97c-fdb7-432f-b43c-0e8854bb6f5b)

**Comment by gicastephanou** [comment]
#351

**Comment by gicastephanou** [comment]
Bom dia,
Não estamos conseguindo associar a issue 344 com o PR #351

**Comment by Mauro1706** [comment]
Boa noite @euviniciusmendonca 
Vai funcionar independente de quantos nos tenha, o cadastro e feito por unidade,
Em ambiente que já existem a configuração terá o seguinte comportamento:
1. Primeiro verificar se a versão e maior ou igual a da instalação da nova funcionalidade
   = Se for vai buscar se foi mapeado alguma coisa validar a configuração
   = Se for e não tiver nada configurado, vai seguir e realizar a consulta na funcionalidade que já existe
   = Se não for segue o fluxo normal

**Comment by davidnascimento1618** [comment]
_Issue_ movida da _sprint_ 25 para a 26 no intuito de ser revalidada.

**Comment by Mauro1706** [comment]
@davidnascimento1618 sobre os itens https://github.com/pengovbr/mod-sei-pen/issues/344#issuecomment-1753411465
o Item 4 não consegui identificar o erro o video 2 e igual ao primeiro;
O item 9 não e possível por o campo onde e guardado o nome na tabela e um varchar(50) e não suporta a quantidade de caracteres

**Comment by davidnascimento1618** [comment]
> @davidnascimento1618 sobre os itens [#344 (comment)](https://github.com/pengovbr/mod-sei-pen/issues/344#issuecomment-1753411465) o Item 4 não consegui identificar o erro o video 2 e igual ao primeiro; O item 9 não e possível por o campo onde e guardado o nome na tabela e um varchar(50) e não suporta a quantidade de caracteres

@Mauro1706, com relação ao item **4**, fiz novamente o _upload_ do vídeo demonstrativo que evidencia os problemas relatados tanto no item **4**, quanto nos itens: **5**, **6** e **7**, o fato é que eu tinha subido o vídeo pertinente à _part. I_ ao invés da _part. II_.

Com relação ao item **9**, poderia então colocar o mesmo título que está descrito no título desta própria _issue_ (assim como o que foi descrito na seção '**Descreva a solução que você gostaria**'), ou seja, o próprio nome da funcionalidade: _"Mapeamento de Envio Parcial"_, nesse caso, teria que também alterar os títulos das telas de edição, visualização e listagem, mas se foi um sugestão do próprio _product owner_ deixar dessa forma, desconsidere meu comentário e mantenha o que foi acordado, só não esquecendo de ajustar o título do _sub menu_ lateral de: _"Restrição Envio Componentes Digitais"_ para: _"Restrição de Envio de Componentes Digitais"_.

Outro ponto preponderante, seria com relação ao que foi mencionando na seção de ['Descreva a solução que você gostaria'](https://github.com/pengovbr/mod-sei-pen/issues/344#issue-1840046328), mais precisamente no que se diz respeito ao que o @euviniciusmendonca, descreve:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/847e2eff-17f6-49f4-8149-b41cda29d250)

Pelo o que entendi, seria uma mesma funcionalidade, mas em telas distintas, análoga à funcionalidade atual de _"Mapeamento de Unidades"_, contudo, mais uma vez reitero, que se foi um sugestão do próprio _PO_, deixar dessa forma, desconsiderando assim meu comentário e partindo do princípio do que foi acordado.

**Comment by davidnascimento1618** [comment]
@Mauro1706, favor verificar os pontos elencados [aqui](https://github.com/pengovbr/mod-sei-pen/pull/351#pullrequestreview-1665025793) e corrigi-los.

**Comment by davidnascimento1618** [comment]
Prezados, @Mauro1706, favor corrigir o item **8** dessa [lista](https://github.com/pengovbr/mod-sei-pen/issues/344#issuecomment-1753411465), uma vez que testando na versão **3** do SEI, está persistindo o problema, conforme mostra no _.gif_ abaixo:

![Sistema está retornando todos os registros, ao digitar o valor  0  (que não consta em parte dos textos dos órgãos), utilizando os filtros de pesquisa nos campos: 'Repositório de Estruturas Organizacionais' e 'Órgão'](https://github.com/pengovbr/mod-sei-pen/assets/87980947/acfb00fb-7f2b-4038-965e-0825e724d2db)

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706,

Favor corrigir os seguintes itens:

- [ ] **1.** Alterar o título do 1º campo de pesquisa de 'Nome Estrutura Organizacional:' para 'Nome do Repositório:' (que é o mesmo que consta na 2ª coluna da tabela da listagem);

- [ ] **2.** Alterar o título do 2º campo de pesquisa de 'Nome Unidade:' para 'Nome da Unidade:' (que é o mesmo que consta na 4ª coluna da tabela da listagem);

- [ ] **3.** Na coluna 'Ações', remover o ícone de 'Consultar Mapeamento', haja vista que não há necessidade de realizar a ação de visualizar um mapeamento, pois essa visão já é exibida na própria listagem em si e também ao editar um mapeamento (comportamento análogo à listagem de Mapeamento de Unidades);

- [ ] **3.** Adicionar também o botão de 'Pesquisar', na parte inferior da tela, para ficar igual aos mesmos botões que são exibidos na parte superior: 'Pesquisar', 'Novo', 'Excluir' e 'Imprimir', nesta ordem.

No vídeo abaixo é evidenciado cada ponto supracitado:

https://github.com/pengovbr/mod-sei-pen/assets/87980947/fb23a03b-4089-4422-b297-f9b6810fbd00

**Comment by carlosevmelo** [comment]
> Prezado @Mauro1706,
> 
> Favor corrigir os seguintes itens:
> 
>     * [ ]  **1.** Alterar o título do 1º campo de pesquisa de 'Nome Estrutura Organizacional:' para 'Nome do Repositório:' (que é o mesmo que consta na 2ª coluna da tabela da listagem);
> 
>     * [ ]  **2.** Alterar o título do 2º campo de pesquisa de 'Nome Unidade:' para 'Nome da Unidade:' (que é o mesmo que consta na 4ª coluna da tabela da listagem);
> 
>     * [ ]  **3.** Na coluna 'Ações', remover o ícone de 'Consultar Mapeamento', haja vista que não há necessidade de realizar a ação de visualizar um mapeamento, pois essa visão já é exibida na própria listagem em si e também ao editar um mapeamento (comportamento análogo à listagem de Mapeamento de Unidades);
> 
>     * [ ]  **4.** Adicionar também o botão de 'Pesquisar', na parte inferior da tela, para ficar igual aos mesmos botões que são exibidos na parte superior: 'Pesquisar', 'Novo', 'Excluir' e 'Imprimir', nesta ordem.
> 
> 
> No vídeo abaixo é evidenciado cada ponto supracitado:
> Pontos.a.serem.corrigidos.na.issue.344.mp4

Prezado @davidnascimento1618, bom dia.

Segue evidência de implementação dos itens 1 a 4.

![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/d610d593-3960-426c-8a03-fcb121289dba)

Por gentileza, deixe me saber se posso ajudar em algo mais.

Obirgado.

**Comment by carlosevmelo** [comment]
Prezados @yurioliveiramgi e @euviniciusmendonca, bom dia.

O @caduvieira perguntou se o título que é exibido na tela deverá ser "Lista dos Mapeamentos de Restrição de Envio de Componentes Digitais" ou se seria melhor "Lista de Unidades para Envio Parcial" ou algo do tipo.
![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/aa254dd8-97dd-4b9c-8c99-5a3b409483d3)

Além disto, por gentileza, qual deverá ser o nome exibido no item de menu da aludida funcionalidade?
![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/c1342bad-8453-4753-b3c3-2c903d308e3c)


Obrigado.

**Comment by yurioliveiramgi** [comment]
Em resposta ao comentário do @carlosevmelo, para fins de registro:
- [ ] Não há necessidade de manter o menu e submenu. Apenas o menu principal com "Mapeamento de Envio Parcial";
- [ ] O Título da tela será "Mapeamento de Envio Parcial", seguindo os "padrões" de outras telas já existente.

Obrigado!

@euviniciusmendonca , para ciência, conforme discutido.

**Comment by carlosevmelo** [comment]
movido da sprint 34 para sprint 35

**Comment by carlosevmelo** [comment]
movido da sprint 35 para sprint 36

**Comment by carlosevmelo** [comment]
Prezados, bom dia.

Seguem evidências de testes do Envio Parcial na release 3.6.0.

Obs: Ainda não consegui subir localmente o ambiente SEI 4.1 para realizar os testes.

### Evidências de testes manuais em vídeos:

[release 3.6.0][sei] MapeamentoEnvioParcial
[[release 3.6.0][sei] MapeamentoEnvioParcial.webm](https://github.com/pengovbr/mod-sei-pen/assets/15729050/d1980506-d8e0-4913-88ac-b6b3e84960f7)

[release 3.6.0][sei4] MapeamentoEnvioParcial
[[release 3.6.0][sei4] MapeamentoEnvioParcial.webm](https://github.com/pengovbr/mod-sei-pen/assets/15729050/0a1c760b-847d-43b5-8396-1e06fa6c86e7)

[release 3.6.0][sei3] MapeamentoEnvioParcial
[[release 3.6.0][sei3] MapeamentoEnvioParcial.webm](https://github.com/pengovbr/mod-sei-pen/assets/15729050/025cba44-0b49-49cf-9654-41b064529b99)

### Evidências de testes automatizados:

[release 3.6.0][sei-mysql] MapeamentoEnvioParcialTest
![release 3 6 0 sei-mysql  MapeamentoEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/5fe492fc-1469-46aa-b8c0-f63ef78601d0)

[release 3.6.0][sei-sqlserver] MapeamentoEnvioParcialTest
![release 3 6 0 sei-sqlserver  MapeamentoEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/4512ac11-501c-4861-b1c3-34a7153b1a23)

[release 3.6.0][sei-oracle] MapeamentoEnvioParcialTest
![release 3 6 0 sei-oracle  MapeamentoEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/e3bdee58-c9a0-44f0-ad42-962094cf6b98)

[release 3.6.0][sei4-mysql] MapeamentoEnvioParcialTest
![release 3 6 0 sei4-mysql  MapeamentoEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/318d3c4a-4545-4bb3-bfdb-7a4e4f5e0366)

[release 3.6.0][sei4-sqlserver] MapeamentoEnvioParcialTest
![release 3 6 0 sei4-sqlserver  MapeamentoEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/33530874-e029-4e07-b646-04f8ce804fe2)

[release 3.6.0][sei4-oracle] MapeamentoEnvioParcialTest
![release 3 6 0 sei4-oracle  MapeamentoEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/48db6936-efa1-4491-a4ea-70e3861b63be)

[release 3.6.0][sei3-mysql] MapeamentoEnvioParcialTest
![release 3 6 0 sei3-mysql  MapeamentoEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/8d81c8f5-e453-45d4-82e6-3fe9bfdc436c)

Agradeço e fico à disposição.

**Comment by carlosevmelo** [comment]
Prezados, boa tarde.

Seguem evidências do novo testes Automatizado de Trâmite de Processo com o Envio Parcial mapeado na release 3.6.0.

[release 3.6.0][sei4.1.1-mysql] TramiteEnvioParcialTest:
![release 3 6 0 sei4 1 1-mysql  TramiteEnvioParcialTest ](https://github.com/pengovbr/mod-sei-pen/assets/15729050/fc3e2576-66c6-4d4d-beb1-2daf810efebe)


[release 3.6.0][sei4.1.1-sqlserver] TramiteEnvioParcialTest:
![release 3 6 0 sei4 1 1-sqlserver  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/cec44550-60e9-408c-b63d-8fcc97766825)


[release 3.6.0][sei4.1.1-oracle] TramiteEnvioParcialTest:
![release 3 6 0 sei4 1 1-oracle  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/45dfe7e5-e068-4bef-a757-b0367b208405)


[release 3.6.0][sei4.0.12.15-mysql] TramiteEnvioParcialTest:
![release 3 6 0 sei4 0 12 15-mysql  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/71e94d01-6e76-4601-a135-51dd4e60b7eb)


[release 3.6.0][sei4.0.12.15-sqlserver] TramiteEnvioParcialTest:
![release 3 6 0 sei4 0 12 15-sqlserver  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/73a01c74-3fd6-44c5-ae04-58fb6d109153)


[release 3.6.0][sei4.0.12.15-oracle] TramiteEnvioParcialTest:
![release 3 6 0 sei4 0 12 15-oracle  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/3d3ccea4-4312-4e5f-9ed2-c39fca8be412)


[release 3.6.0][sei4.0.12-mysql] TramiteEnvioParcialTest:
![release 3 6 0 sei4 0 12-mysql  TramiteEnvioParcialTest ](https://github.com/pengovbr/mod-sei-pen/assets/15729050/279061e8-048c-422d-9c72-56f4f0b0dac2)


[release 3.6.0][sei4.0.12-sqlserver] TramiteEnvioParcialTest:
![release 3 6 0 sei4 0 12-sqlserver  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/88f61b38-efa5-4927-9334-ee90eb97e117)


[release 3.6.0][sei4.0.12-oracle] TramiteEnvioParcialTest:
![release 3 6 0 sei4 0 12-oracle  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/2d36ee18-63f1-4b36-b71b-ed16b6d2e209)


[release 3.6.0][sei3.1.7-mysql] TramiteEnvioParcialTest:
![release 3 6 0 sei3 1 7-mysql  TramiteEnvioParcialTest](https://github.com/pengovbr/mod-sei-pen/assets/15729050/4b81b1b6-9f92-4fb4-9f9b-fea0c6d9512c)


Agradeço e fico à disposição.

**Comment by carlosevmelo** [comment]
Prezados, boa tarde.

Seguem evidências da Instalação do mod-sei-pen com o Envio Parcial mapeado pelo arquivo de configuração ConfiguracaoModPEN.php

[release 3.6.0][sei4.1.1] Instalação do mod-sei-pen com Mapeamento de Envio Parcial
https://github.com/pengovbr/mod-sei-pen/assets/15729050/afc3e8fb-302a-496d-b884-0c70d065c954


[release 3.6.0][sei4.0.12.15] Instalação do mod-sei-pen com Mapeamento de Envio Parcial
https://github.com/pengovbr/mod-sei-pen/assets/15729050/340a4ddb-0ca9-4800-890a-cda829c68576


[release 3.6.0][sei4.0.12] Instalação do mod-sei-pen com Mapeamento de Envio Parcial
https://github.com/pengovbr/mod-sei-pen/assets/15729050/ccf7fd6d-7948-47a3-8a21-489b46003a02


[release 3.6.0][sei3.1.7] Instalação do mod-sei-pen com Mapeamento de Envio Parcial
https://github.com/pengovbr/mod-sei-pen/assets/15729050/9c4515d7-7c31-4cc3-aa43-6425a7696b53


Agradeço e fico à disposição.
