### ISSUE TITLE
Sistema não está aplicando os filtros de pesquisa da tela de mapeamento de unidades.

### ISSUE THREAD

**Issue by davidnascimento1618** [pengovbr/mod-sei-pen#347]
**Descrição do erro**

Foi verificado que na tela de mapeamento de unidades, o sistema não está obedecendo a pesquisa através dos campos 'Sigla' e 'Descrição'.

---

**Para reproduzir**

Passos para reproduzir o comportamento:

1. Vá para 'Administração' -> 'Processo Eletrônico Nacional' -> 'Mapeamento de unidades' -> 'Listar';
2. Digite quaisquer valores dentro dos campos 'Sigla' e/ou 'Descrição';
3. Clique sobre o botão de 'Pesquisar';
4. Verifique que o sistema não obedece a pesquisa realizada no _step_ anterior.

---

**Comportamento esperado**

Sistema deveria realizar a consulta das unidades conforme os critérios de pesquisa realizados nos respectivos filtros.

---

**Screenshots**

![Sistema não está aplicando os filtros de pesquisa da tela de mapeamento de unidades](https://github.com/supergovbr/super/assets/87980947/abd538a4-dc0e-4c25-bfb9-9eac3423c5bf)

---

**Contexto da falha:**

Ambiente: [localhost](http://org1-http:8000/sei/)
Versão do sistema SEI: 4.0.9.13
Versão do módulo do Tramita: 3.2.4
Navegador: Google Chrome versão 113.0.5672.92
Perfil do usuário utilizado no teste: 'ADMINISTRADOR';
Usuário utilizado no teste:  'TESTE';
URL do ambiente: http://org1-http:8000/sei

---

**Comment by mrglaydson** [comment]
Vídeo realizado após a correção:
https://drive.google.com/file/d/1hVO9zErpwznBZN5uofcr76sA2SolcV6Z/view?usp=sharing

**Comment by davidnascimento1618** [comment]
Foi verificado que o sistema está retornando todos os registros ao digitar o valor "0" (que não consta em parte dos textos das unidades), utilizando os filtros de pesquisa nos campos: 'Sigla' e/ou 'Descrição', como é exibido no _.gif_ abaixo:

https://github.com/pengovbr/mod-sei-pen/assets/87980947/05352d74-b5ff-4c4d-ab19-057335030b81

**Comment by MatheusMarques80** [comment]
Implementado os testes funcionais da funcionalidade de listagem do mapeamento de unidade.

https://github.com/pengovbr/mod-sei-pen/assets/13146046/6b88f5a5-e371-4e3c-9a3d-5e1fdbc7d2e7

**Comment by mateussbh** [comment]
Movido da sprint 24 para a 27.
