### ISSUE TITLE
Criar críticas para impedir Desativar ou Excluir Tipos de Hipóteses Legais utilizados na Administração do Módulo.

### ISSUE THREAD

**Issue by davidnascimento1618** [pengovbr/mod-sei-pen#348]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

O módulo não está utilizando eventos de bloqueio da API de módulos para impedir Desativações e Exclusões de Tipos de Hipóteses Legais, utilizadas nas diversas telas de Administração do Módulo PEN, o que acaba gerando erros no uso do módulo com mapeamentos feitos com registros desativados ou excluídos, onde na prática, acaba ocasionando erros que são difíceis de descobrir.

-----

**Descreva a solução que você gostaria**

O módulo PEN tem que implementar mensagens de crítica utilizando eventos de bloqueio da API de módulos para impedir Desativar ou Excluir Tipos de Hipóteses Legais e de Restrição Padrão utilizadas nas diversas telas de Administração do Módulo PEN.

Desativar:
- [x] Hipóteses Legais 

Excluir:
- [x] Hipóteses Legais

-----

**Comment by NinetiesPaul** [comment]
https://github.com/pengovbr/mod-sei-pen/assets/36829911/ce29e633-f24d-4082-aca3-109c6f82275f

Evidencia do bloqueio em ação, travando a exclusão ou desativação de uma hipotese legal em uso

**Comment by Mauro1706** [comment]
Após analise no PR creio que a implementação foi feita de maneira correta,
Feito no Core do SEI a implementação dos pontos de extensão para hipóteses legais e e a correção do método de exclusão para chamar o módulo para validar o mesmo!

**Comment by sergioadao** [comment]
@NinetiesPaul , @mateussbh ... Boa tarde Paul.....a problema de apresentação de mensagem de quebra da aplicação durante o processo de exclusão de hipótese legal em uso persiste.. ISSUE 153  PR 430....Ambiente de teste SEI-OFICIAL/MySql...Segue evidência:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/e1a8636a-ad37-475b-a6be-88bf706106d2

**Comment by sergioadao** [comment]
Bom dia @NinetiesPaul ...realizei a aplicação do PR 359 no SEI-OFICIAL/MYSQL...No diretório SEI rodei o 

# make up e coreu tudo certo:

$ make up
docker-compose up -d
Starting sei-401215_solr_1      ... done
Starting sei-401215_jod_1       ... done
Starting sei-401215_memcached_1 ... done
Starting sei-401215_smtp_1      ... done
Starting sei-401215_database_1  ... done
sei-401215_httpd_1 is up-to-date
make check-sei-isalive


Aguardando inicialização do ambiente de desenvolvimento...
Tentativa 1/15
Tentativa 2/15
Página de login carregada!
make[1]: Saindo do diretório '/home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-4.0.12.15'

Mas, quando tento subir o módulo do TRAMITA (mod-sei-pen) ocorre o erro que segue:

$ make destroy; make up; make install
Stopping funcional_org2-database_1  ... done
Stopping funcional_org1-database_1  ... done
Stopping funcional_org2-memcached_1 ... done
Stopping funcional_org1-memcached_1 ... done
Removing funcional_org2-database_1  ... done
Removing funcional_php-test-unit_1  ... done
Removing funcional_smtp_1           ... done
Removing funcional_org1-database_1  ... done
Removing funcional_org2-memcached_1 ... done
Removing funcional_org1-memcached_1 ... done
Removing network funcional_default
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env up -d
Creating network "funcional_default" with the default driver
Creating funcional_org2-memcached_1 ... 
Creating funcional_org1-memcached_1 ... 
Creating funcional_php-test-unit_1  ... 
Creating funcional_smtp_1           ... 
Creating funcional_org2-memcached_1 ... done
Creating funcional_org1-memcached_1 ... done
Creating funcional_php-test-unit_1  ... done

Creating funcional_org2-database_1  ... done
Creating funcional_org1-database_1  ... done

ERROR: for smtp  Cannot start service smtp: driver failed programming external connectivity on endpoint funcional_smtp_1 (1352456853ee1cd47d9d3678812ffcaef7c8ab2b92733ddd84d2daaa2b096e9a): Bind for 0.0.0.0:1080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:164: up] Erro 1

Testando se a pagina de login responde para o org1...
Tentativa 1/15
Tentativa 2/15
Tentativa 3/15
Tentativa 4/15
Tentativa 5/15
Tentativa 6/15
Tentativa 7/15
Tentativa 8/15
Tentativa 9/15
Tentativa 10/15
Tentativa 11/15
Tentativa 12/15
Tentativa 13/15
Tentativa 14/15
Tentativa 15/15
Pagina de login do org1 nao encontrada. Verifique...
make: *** [Makefile:64: check-isalive] Erro 1

Alguma orientação?

**Comment by sergioadao** [comment]
@NinetiesPaul ....Bom dia Paul....fiz um testes utilizando a issue 348 com a PR 430.....está correto? No teste obtive o erro abaixo:


Uploading erro-mapeamento-hipoteses-issue348-pr430.mp4…

**Comment by Mauro1706** [comment]
https://github.com/pengovbr/mod-sei-pen/issues/348#issuecomment-2014904185
@sergioadao foi testado aqui e o ambiente esta subindo normalmente, identifiquei que de u $make up no sei e deu o $make destroy no modulo.
O correto se for subir o sei e subir e derrubar no sei, quando sobe no sei tem container que são específicos no sei dai o modulo não consegue derrubar por conta de nomenclatura.

**Comment by NinetiesPaul** [comment]
Só para titulo de esclarecimento, o procedimento que estou utilizando em meu ambiente é (nessa ordem descrita):

**No Sei**
Fazer checkout na branch 359
Se estivar de pé derrubar com _make destroy_
Executar _make up_ depois _make install_ e por último _make down_

**No Tramita**
Fazer checkout na branch 430
Se estivar de pé derrubar com _make destroy_
Executar _make up_ e por ultimo _make install_

Não sei ao certo se todos os passos são necessários, mas adotei essa ordem pra garantir que o sistema esta executando sempre do 0

**Comment by sergioadao** [comment]
@NinetiesPaul e @mateussbh ....Teste de Hipóteses Legais funcional   ISSUE 348 ...PR SEI 359 e PR MOD-SEI 430...... **Funcionou conforme solicitado**. Segue vidência:

https://github.com/pengovbr/mod-sei-pen/assets/87815724/419c910f-540b-4d39-aa5f-fb83958c4013

**OBS: Trocar item de menu Protocolo Eletrônico Nacional por Tramita GOV.BR.**

**Comment by caduvieira** [comment]
> OBS: Trocar item de menu Protocolo Eletrônico Nacional por Tramita GOV.BR. 

Isso não é tratado nessa issue.

**Comment by sergioadao** [comment]
@NinetiesPaul .....Boa tarde.....Realizando teste de remoção das hipóteses mapeadas...identifiquei que nenhuma hipótese consegue ser removida......segue video da evidência:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/780d6535-1fc0-4273-9a9e-3ed22d57a315

**Comment by sergioadao** [comment]
Boa tarde @NinetiesPaul , @Mauro1706 e @mateussbh ....realizei os testes com a ISSUE 348 PR 430 (mod-sei)/ PR 359 (sei). No mapeamento, hipóteses **inativadas** no TRAMITA estão sendo visualizadas, na tela de mapeamento. Quanto a crítica de exclusão de hipóteses mapeadas está funcionando.Segue evidência:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/58161d9c-a098-42d0-abda-ed814f753652

**Comment by amelquia** [comment]
04/06/24
Card movido para Sprint 43.

**Comment by amelquia** [comment]
10/06/24
Card movido para a Sprint 44.

**Comment by yurioliveiramgi** [comment]
Conforme comentado pelo @caduvieira , essa issue somente ficará disponível nas versões do SEI (4.0.x e 4.1.x) após realização do PR no SEI.
Por hora, a versão main do SEI na esteira de processos, permite que as melhorias sejam visualizadas e validadas, conforme evidência.
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/8cfb23bb-c09e-41a5-aefc-b2176598d241)

**Comment by euviniciusmendonca** [comment]
@amelquia, vamos aguardar o alinhamento com o TRF4 para incluir em uma release do módulo. Qual seria a melhor abordagem para tratar esta issue no momento?

@caduvieira e @higodf para ciência.
