### ISSUE TITLE
Mapeamento Automático de Hipóteses Legais

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#350]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Atualmente, o Administrador do SEI necessita realizar o cadastro manual das hipóteses legais(Administração --> Processo Eletrônico Nacional --> Mapeamento de Hipóteses Legais) tanto para o envio quanto para o recebimento.

![image](https://github.com/pengovbr/mod-sei-pen/assets/60577185/e2019d0b-0e7c-4dbf-9e35-c79d7c006425)

-----

**Descreva a solução que você gostaria**
Utilizar a mesma inteligência do mapeamento automático de documentos na funcionalidade mapeamento de hipóteses legais (Mapeamento das Hipóteses do Tramita com as do Sistemas e vice-versa).

![image](https://github.com/pengovbr/mod-sei-pen/assets/60577185/05c84323-8f7a-4ebd-ba9f-54d138cd9c21)

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by davidnascimento1618** [comment]
A explicação do requisito em questão, encontra-se no tempo compreendido entre 19:42 a 24:51, neste [vídeo](https://mtegovbr-my.sharepoint.com/personal/glaydson_queiroz_economia_gov_br/_layouts/15/stream.aspx?id=%2Fpersonal%2Fglaydson%5Fqueiroz%5Feconomia%5Fgov%5Fbr%2FDocuments%2FGrava%C3%A7%C3%B5es%2F%5BSUPER%5D%20%2D%20Daily%2D20230904%5F114235%2DGrava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o%2Emp4&ga=1).

**Comment by mateussbh** [comment]
Prezado @mrglaydson, poderia incluir o vídeo que foi citado pelo @davidnascimento1618  [neste](https://github.com/pengovbr/mod-sei-pen/issues/350#issuecomment-1705729716) comentário, por favor? A url dele sugere que você tem o controle sobre ele: https://mtegovbr-my.sharepoint.com/personal/glaydson_queiroz_economia_gov_br/_layouts/15/stream.aspx?id=%2Fpersonal%2Fglaydson%5Fqueiroz%5Feconomia%5Fgov%5Fbr%2FDocuments%2FGrava%C3%A7%C3%B5es%2F%5BSUPER%5D%20%2D%20Daily%2D20230904%5F114235%2DGrava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o%2Emp4&ga=1

**Comment by michael-ferreira2022** [comment]
Foi necessário ajustar a verão no script para 3.4.2.

**Comment by yuribitu** [comment]
Necessário análise para entender o Ajuste Necessário!

**Comment by Mauro1706** [comment]
Sobre o assunto eu já pego as Hipôteses que estão ativas. @caduvieira poderia me passar uma orientação sobre o assunto, o que pode estar errado?
![image](https://github.com/pengovbr/mod-sei-pen/assets/83025710/2bfe3b4b-6b22-42ae-9a32-bc57af7b819c)

**Comment by caduvieira** [comment]
O erro não deve estar aí. Coloque link para o código ao invés de printscreen para poder analisar melhor.

**Comment by amelquia** [comment]
12/05/24
Issue não finalizada e migrada para a Sprint 42.

**Comment by amelquia** [comment]
27/05/24
Sprint Planning - Sprint 43 realizada.
Issue transferida para a **Sprint 43** para dar sequencia no fluxo dos status. **Status atual: "Ajustes Necessários."**
Nova estimativa: 2 horas.

**Comment by sergioadao** [comment]
Boa tarde @Mauro1706, @mateussbh, @yurioliveiramgi  e @amelquia, após testes com a issue 350 verificou-se que a mesma apresenta hipóteses inativadas no portal para mapeamento na aplicação. Solicitei ao Yuri verificar no portal o status da hipótese " Apenas um Teste" e a mesma está inativada conforme print abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/1381788e-bdf8-4992-ac37-7705c21622a4)

Abaixo segue evidência do mapeamento com hipóteses inativas:


https://github.com/pengovbr/mod-sei-pen/assets/87815724/483ea0e2-2077-4454-8211-15d659246d98

**Comment by Mauro1706** [comment]
Bom dia, não foi identificado o erro apontado na branch incluida nesse PR, segue evidência

https://github.com/pengovbr/mod-sei-pen/assets/83025710/7caa1a16-0f74-454f-918f-6abb89624c41

**Comment by Mauro1706** [comment]
Resolvido no PR: https://github.com/pengovbr/mod-sei-pen/pull/512

**Comment by euviniciusmendonca** [comment]
@mateussbh @amelquia @yurioliveiramgi 

Conforme informado na reunião de review, o mapeamento automático é apenas realizado quando não existe nenhum mapeamento prévio. Portanto, caso seja identificado algum mapeamento não realizar o mapeamento automático.

**Comment by Mauro1706** [comment]
Bom dia, segue novo PR com atualização.
https://github.com/pengovbr/mod-sei-pen/pull/517

**Comment by amelquia** [comment]
10/06/24
Card movido para a Sprint 44.

**Comment by sergioadao** [comment]
Bom dia @Mauro1706, @mateussbh , @amelquia e @yurioliveiramgi....testes realizados e confirmado a mapeamento de hipóteses legais automaticamente. Segue evidência:

OBS: SEI 4.1.1 branch release/3.7.0



https://github.com/pengovbr/mod-sei-pen/assets/87815724/1fd16de8-b45d-470e-8372-ac19233598cc

**Comment by yurioliveiramgi** [comment]
Considero que há o atendimento do esperado para a issue.

O mapeamento foi realizado de forma automática. Entretanto, algumas hipóteses possuem uma grafia ligeiramente diferentes das existentes no SEI, de forma que o mapeamento não foi realizado automaticamente. 
Creio que não seja necessário um ajuste na issue e sim uma adaptação no portal do Tramita GOV.BR.
A saber, as hipóteses não mapeadas são:

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/4378b6ee-2f66-4f8a-816e-49ead8de6127)

Modificações necessárias:

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/c6d50a94-d840-426a-9d1f-7f62a6020494)



@euviniciusmendonca PSC

**Comment by amelquia** [comment]
21/06/24
Movimento da issue em **Em Análise P.O.** para a Sprint 45 .

**Comment by amelquia** [comment]
24/06/24
Após explicação do @yurioliveiramgi , o card foi movido para **Ajustes Necessários**.

**Comment by amelquia** [comment]
24/06/24
Conforme alinhamento realizado hoje no Planejamento da Sprint 45, foi constatado pelo @yurioliveiramgi  que a issue atende ao que foi solicitado e, o card foi movido para o status **Aceite Negocial**, conforme autorização dele.
