### ISSUE TITLE
Mapeamento de Hipóteses Legais - Não recuperar Hipóteses Legais Inativas na Tela

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#354]
**Descreva o erro**
As hipóteses legais do Tramita.GOV.BR cadastradas no Portal de Administração e INATIVAS são exibidas na tela de mapeamento do módulo de conexão com o SEI.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para Administração --> Processo Eletrônico Nacional --> Mapeamento de Hipóteses Legais;
2. Depois clicar em Cadastrar;
3. Verificar a existência de na combo Hipótese Legal PEN de Apenas um Teste;
4. Depois entrar no Portal de Administração e clicar em Administração --> Hipóteses Legais e procurar pela Hipótese Apenas um Teste com Status Inativo.

-----

**Comportamento esperado**
Exibir apenas hipóteses legais ativos na combo para o mapeamento.

-----

**Screenshots**

A Tela do Mapeamento com Hipóteses Legais Inativos:

![image](https://github.com/pengovbr/mod-sei-pen/assets/60577185/7f9251f5-e79e-47d7-8a2c-6800b9784168)

A Tela de Hipóteses Legais Inativas no Portal de Administração:

![image](https://github.com/pengovbr/mod-sei-pen/assets/60577185/0c2353aa-d147-4c7d-8600-947f74aea1b7)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
Não se aplica.

-----

**Informações adicionais**
Não se aplica.

-----
**Log de Erros**
Não se aplica.

**Comment by davidnascimento1618** [comment]
A explicação do requisito em questão, encontra-se no tempo compreendido entre 26:50 a 35:50, neste [vídeo](https://mtegovbr-my.sharepoint.com/personal/glaydson_queiroz_economia_gov_br/_layouts/15/stream.aspx?id=%2Fpersonal%2Fglaydson%5Fqueiroz%5Feconomia%5Fgov%5Fbr%2FDocuments%2FGrava%C3%A7%C3%B5es%2F%5BSUPER%5D%20%2D%20Daily%2D20230904%5F114235%2DGrava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o%2Emp4&ga=1).

**Comment by euviniciusmendonca** [comment]
@davidnascimento1618 @yuribitu, vamos deixar em standby. Eu coloquei na sprint atual da API do Tramita.GOV.BR a seguinte issue: https://github.com/pengovbr/tramitagovbr/issues/90. 

Atualmente, o endpoint [​/interoperabilidade​/rest​/v3​/hipoteses](https://api.conectagov.processoeletronico.gov.br/swagger/swagger-ui/#/tramite-service-v-3/listarHipotesesUsingGET) não recupera o status da hipótese legal. A previsão de conclusão da sprint do desenvolvimento interno é dia 24 de setembro.

@davidnascimento1618, remover da sprint.

Depois, eu irei verificar a possibilidade de incluir um novo item na atual sprint. 

@fasousa @pedrohpms para seu conhecimento.

**Comment by euviniciusmendonca** [comment]
@davidnascimento1618  @yuribitu @carolfreirer já foi evoluído o endpoint. Podemos retomar o desenvolvimento. É possível incluir no desenvolvimento da atual sprint?

**Comment by euviniciusmendonca** [comment]
Prezados,

Essa funcionalidade ainda não foi desenvolvida. 

O motivo dessa funcionalidade não ter entrado em desenvolvimento era que o endpoint responsável pela recuperação de hipóteses legais retornava todas hipóteses, ativas ou inativas. 

Foi incluído um parâmetro nesse endpoint para possibilitar retornar apenas as hipóteses ativas. Atualizar a tela com o novo comportamento. O funcionamento dessa funcionalidade já foi documentado anteriormente.

**Comment by sergioadao** [comment]
Bom dia @Mauro1706, a tela com apresentação de Hipóteses Legais Inativas .......não é apresentada...conforme [comentário](https://github.com/pengovbr/mod-sei-pen/pull/372#pullrequestreview-1694858894).

**Comment by sergioadao** [comment]
Transferida de sprint 27 para sprint 28.

**Comment by caduvieira** [comment]
Novo parâmetro 'ativo' caso não preenchido traz somente as hipóteses ativas.

**Comment by yurioliveiramgi** [comment]
Necessário ajustes. Mesmo com a hipótese desativada, esta segue apresentada na lista de hipóteses.

Hipótese desativada 17:23
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/06eacc09-b8c6-4612-8205-81661591c06f)
Agendamento executado 17:24
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/3de4b40a-b981-4099-aa2b-195205ff491b)
Hipótese inativada disponível na lista 17:25
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/14daff76-7558-44e1-8f52-54ad3f525487)


Para conhecimento @mateussbh , @amelquia , @euviniciusmendonca , @caduvieira e @Mauro1706

**Comment by amelquia** [comment]
05/06/24
Card movido para a Sprint 43.

**Comment by Mauro1706** [comment]
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/512 para limitar listagem com somente ativas.

**Comment by amelquia** [comment]
10/06/24
Card movido para a Sprint 44.

**Comment by sergioadao** [comment]
Bom dia @Mauro1706, @mateussbh, @yurioliveiramgi  e @amelquia....Issue validada e confirmado o funcionamento conforme solicitado. Segue evidência:

**OBS: Utilizado SEI 4.1.1 e branch release/3.7.0**



https://github.com/pengovbr/mod-sei-pen/assets/87815724/0b6cef12-b7cc-4825-a0bf-3d8a0041de03

**Comment by yurioliveiramgi** [comment]
Foi verificado que hipóteses inicialmente inativadas no momento de criação do ambiente não são listadas na caixa de seleção do mapeamento. Uma vez ativada a hipótese, e executado o agendamento, esta passa a ser visível na caixa de seleção. Entretanto, ao inativar alguma hipótese recentemente ativada, ou que já estava ativa no momento de criação do ambiente, esta não deixa de aparecer na caixa de seleção.

**Atenção aos horários de captura de tela no canto inferior direito**




![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/9b38d340-44dd-4dcd-af4c-0fb30c03ad59)

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/a651d832-4972-4063-9874-dd97ec7fd643)

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/3f5593ef-3524-4548-be79-71f526b28a78)

Nova verificação:

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/268e47c6-730e-41d6-b750-fd8d3ef45237)

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/dc055474-d8ca-40c1-9fc8-be6917b719ee)

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/1c67c6e8-6f96-4dc9-bbdc-395a2c8e5e67)

![Image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/4ebd91dc-da50-4716-8f7f-dabe9cd4a784)

**Comment by caduvieira** [comment]
> Foi verificado que hipóteses inicialmente inativadas no momento de criação do ambiente não são listadas na caixa de seleção do mapeamento. Uma vez ativada a hipótese, e executado o agendamento, esta passa a ser visível na caixa de seleção. Entretanto, ao inativar alguma hipótese recentemente ativada, ou que já estava ativa no momento de criação do ambiente, esta não deixa de aparecer na caixa de seleção.

Foi executado o agendamento depois?

**Comment by amelquia** [comment]
21/06/24
Movimento da issue em **Em Análise P.O.** para a Sprint 45 .

**Comment by amelquia** [comment]
21/06/24
Movimento da issue em **Em Análise P.O.** para a Sprint 45 .

**Comment by amelquia** [comment]
24/06/24
Após as explicações fornecidas pelo @yurioliveiramgi, o card foi movido para "Ajustes Necessários".

**Comment by Mauro1706** [comment]
Resolvido o problema no PR https://github.com/pengovbr/mod-sei-pen/pull/522

**Comment by amelquia** [comment]
27/06/24
Validação técnica a ser realizada pelo Sérgio Adão.

**Comment by sergioadao** [comment]
Bom dia @yurioliveiramgi , @mateussbh e @amelquia ... segue evidência da implementação do mapeamento automático de hipóteses legais.
Ambiente: SEI 4.1.1 / Branch 3.7.0

https://github.com/pengovbr/mod-sei-pen/assets/87815724/27ec30bd-e755-435c-b302-323ad23063b5

**OBS: Contudo, após testes, observou-se que é possível desativar uma hipótese que esteja mapeada sem qualquer aviso ao usuário. Segue evidência:**


https://github.com/pengovbr/mod-sei-pen/assets/87815724/f43e4b65-1bc7-4da5-bf97-b905211f3dec

**Comment by caduvieira** [comment]
> OBS: Contudo, após testes, observou-se que é possível desativar uma hipótese que esteja mapeada sem qualquer aviso ao usuário. Segue evidência:

Não há ponto de extensão no SEI 4.1.1 que bloqueia esse tipo de ação.

**Comment by yurioliveiramgi** [comment]
O assunto da issue em questão está resolvido. O módulo não está mais recuperando hipóteses inativas.
O mapeamento automático está tratado na issue #350 
A questão da inativação está sendo tratada na issue #348 e carece de ponto de extensão no SEI, conforme pontuado pelo Carlos https://github.com/pengovbr/mod-sei-pen/issues/354#issuecomment-2197513575

**Comment by yurioliveiramgi** [comment]
@euviniciusmendonca , @caduvieira , @sergioadao , @amelquia, @mateussbh e @Mauro1706 

Para conhecimento.
