### ISSUE TITLE
Ícone de Cancelar Tramitação Externa Duplicado

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#355]
**Descreva o erro**

Ao enviar um processo por meio do Tramita.GOV.BR, o ícone de cancelamento está ficando duplicado.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para Iniciar Processo e crie um processo na unidade Teste;
2. Após a criação do processo, incluir no mínimo um documento para realizar o trâmite;
3. Clique em Envio Externo de Processo;
4. Verificar que o ícone Cancelar Tramitação Externa Duplicado está duplicado.

-----

**Comportamento esperado**
O ícone deve aparecer apenas uma vez para o usuário.

-----

**Screenshots**
![image](https://github.com/pengovbr/mod-sei-pen/assets/60577185/0e9ad331-52ee-45f1-aa04-ce07b486f339)
-----

**Contexto da falha (Por favor, complete a seguinte informação):**
Não se aplica.

-----

**Informações adicionais**
Não se aplica.

-----
**Log de Erros**
Não se aplica.

**Comment by euviniciusmendonca** [comment]
@caduvieira, o problema acima surgiu com a provável release 3.3.2.

**Comment by caduvieira** [comment]
Ok
