### ISSUE TITLE
Erro "Erro gravando documento"

### ISSUE THREAD

**Issue by dhiego28** [pengovbr/mod-sei-pen#374]
**Descreva o erro**
O pen está dando o seguinte erro com a versão 4.1: 

 [+0,02s]
00024 - [23/10/2023 18:26:58] (4911) [PROCESSAMENTO]  Descrição:
Erro gravando documento.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1.Enviar qualquer processo
-----

**Comportamento esperado**
O processo sendo gravado no SEI

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: 4.1.1
 - Navegador: não se aplica
 - Perfil do Usuário:não se aplica
 - Banco de dados: Oracle 
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
00020 - [23/10/2023 18:26:57] (4911) [PROCESSAMENTO]      Liberando processo concorrente de recebimento de processo ... [+0s]
00021 - [23/10/2023 18:26:58] (4911) [PROCESSAMENTO]          Persistindo/atualizando dados do processo com NRE xxxxxx [+0,44s]
00022 - [23/10/2023 18:26:58] (4911) [PROCESSAMENTO]          Quantidade de documentos para recebimento: 1 [+0,29s]
00023 - [23/10/2023 18:26:58] (4911) [PROCESSAMENTO]  Descrição:
Erro gravando documento.

Mensagem:
Erro gravando documento.

```
Trilha de Processamento:
#0 /opt/sei/web/rn/DocumentoRN.php(31): DocumentoRN->cadastrarRN0003Interno(Object(DocumentoDTO))
#1 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(1706): DocumentoRN->cadastrarRN0003(Object(DocumentoDTO))
#2 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(1095): ReceberProcedimentoRN->atribuirDocumentos(Object(ProcedimentoDTO), Object(stdClass), Object(PenUnidadeDTO), Object(stdClass), '000013493684202...')
#3 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(736): ReceberProcedimentoRN->gerarProcedimento(Object(stdClass), Object(stdClass))
#4 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(147): ReceberProcedimentoRN->registrarProcesso('000013493684202...', 886622, Object(stdClass), Object(stdClass))
#5 /opt/infra/infra_php/InfraRN.php(151): ReceberProcedimentoRN->receberProcedimentoInternoControlado(Object(stdClass))
#6 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(88): InfraRN->__call('receberProcedim...', Array)
#7 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(179): ReceberProcedimentoRN->receberProcedimento(886622)
#8 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(400): ProcessarPendenciasRN->receberProcedimento('886622')
#9 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(370): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
#10 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(95): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
#11 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(30): PendenciasTramiteRN->encaminharPendencias(true, false, true)
#12 {main}
```

**Comment by caduvieira** [comment]
Não há compatibilidade com a versão 4.1.X com o módulo.

**Comment by paradoxdk** [comment]
@caduvieira temos alguma previsão para o mod-sei-pen ser compatível com as versões 4.1.X?
Há alguma forma de fazermos rodar na 4.1.1?

**Comment by caduvieira** [comment]
Não temos previsão e nem forma para rodar no 4.1.1
