### ISSUE TITLE
Assunto do documento não é enviado pelo TramitaGov, somente string "***" é recebida. 

### ISSUE THREAD

**Issue by inacioloy** [pengovbr/mod-sei-pen#375]
Sou Analista de TI no IFRN e utilizamos o sistema SUAP (https://portal.suap.ifrn.edu.br/), percebemos que ao receber trâmites externos oriundos do sistema SEI pelo TramitaGov o atributo referente ao assunto do documento é recebido com a string "***". Gostaríamos de solicitar uma análise/resolução deste problema para que seja enviado o assunto correto de cada documento facilitando a visualização dos documentos no processo. Estamos a disposição para maiores detalhes ou esclarecimentos.

https://github.com/pengovbr/mod-sei-pen/blob/b7ec3557d4e9c0ef8e19a4956ff09e3780e7b96e/src/rn/ExpedirProcedimentoRN.php#L896

**Comment by caduvieira** [comment]
@inacioloy poderia, por favor, preencher o template da issue de melhoria com o passo a passo de reprodução do problema e qual campo gostaria que fosse enviado? Obrigado

**Comment by inacioloy** [comment]
@caduvieira criei a issue https://github.com/pengovbr/mod-sei-pen/issues/377 com o template corretamente e estou fechando esta.
