### ISSUE TITLE
Recusa pelo motivo "Documento não foi recebido pela unidade atual."

### ISSUE THREAD

**Issue by higodf** [pengovbr/mod-sei-pen#379]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Ao tentar devolver um processo onde foram retirados documentos originalmente criados por um determinado órgão o SEI recusa informando que: "Documento não foi recebido pela unidade atual."

A mensagem de recusa ocorre porque ao tentar cancelar os documentos retirados a unidade que esta recebendo o processo não foi a mesma que criou o documento.

-----

**Contexto adicional**
```
`Documento não foi recebido pela unidade atual.

Trilha de Processamento:
#0 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(1880): InfraRN->__call('cancelarDocumen...', Array)
#1 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(1767): ReceberProcedimentoRN->cancelarDocumentosProcesso('15', Array)
#2 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(932): ReceberProcedimentoRN->atribuirDocumentos(Object(ProcedimentoDTO), Object(stdClass), Object(PenUnidadeDTO), Object(stdClass), '000004508009202...')
#3 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(733): ReceberProcedimentoRN->atualizarProcedimento(15, Object(stdClass), Object(stdClass))
#4 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(147): ReceberProcedimentoRN->registrarProcesso('000004508009202...', 138269, Object(stdClass), Object(stdClass))
#5 /opt/infra/infra_php/InfraRN.php(151): ReceberProcedimentoRN->receberProcedimentoInternoControlado(Object(stdClass))
#6 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(88): InfraRN->__call('receberProcedim...', Array)
#7 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(179): ReceberProcedimentoRN->receberProcedimento(138269)
#8 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(400): ProcessarPendenciasRN->receberProcedimento('138269')
#9 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(370): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
#10 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(95): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
#11 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(30): PendenciasTramiteRN->encaminharPendencias(false, false, false)
#12 {main}
`
```

**Comment by carlosevmelo** [comment]
Prezados @higodf e @mateussbh,

criei o caso de teste "TramiteProcessoContendoDocumentoMovidoDestino" para a presente Issue #379 e o PR #381.

Ainda estou com problemas para subir o ambiente SEI 3 e executar o teste completo, assim sendo, até o momento consegui gerar evidências de testes nos seguintes cenários:

SEI 4:

1. 	[tests-sei4][funcional][mysql] TramiteProcessoContendoDocumentoMovidoDestino
2. 	[tests-sei4][funcional][oracle] TramiteProcessoContendoDocumentoMovidoDestino
3. 	[tests-sei4][funcional][sqlserver] TramiteProcessoContendoDocumentoMovidoDestino

SEI:

1. 	[tests-sei][funcional][mysql] TramiteProcessoContendoDocumentoMovidoDestino
2. 	[tests-sei][funcional][oracle] TramiteProcessoContendoDocumentoMovidoDestino
3. 	[tests-sei][funcional][sqlserver] TramiteProcessoContendoDocumentoMovidoDestino


Pendências de testes:
	(ainda estou com problemas pra subir o ambiente de desenvolvimento SEI 3)
	
	(também estou com problemas para ecxecutar o teste completo de todos os casos de testes nas três versões do SEI)

	Obs: Assim que resolver eu atualizo a presente issue com as evidências de teste


Evidências de testes realizados com sucesso:

Telas do SEI:
/home/carlos/Desktop/desenv/379-completo/[tests-sei][funcional][print] TramiteProcessoContendoDocumentoMovidoDestino-1.png

/home/carlos/Desktop/desenv/379-completo/[tests-sei][funcional][print] TramiteProcessoContendoDocumentoMovidoDestino-2.png

/home/carlos/Desktop/desenv/379-completo/[tests-sei][funcional][print] TramiteProcessoContendoDocumentoMovidoDestino-3.png


SEI 4:
	[tests-sei4][funcional][mysql] TramiteProcessoContendoDocumentoMovidoDestino
/home/carlos/Desktop/desenv/379-completo/tests_sei4/funcional/evidencias/[tests-sei4][funcional][mysql] TramiteProcessoContendoDocumentoMovidoDestino.png

	[tests-sei4][funcional][oracle] TramiteProcessoContendoDocumentoMovidoDestino
/home/carlos/Desktop/desenv/379-completo/tests_sei4/funcional/evidencias/[tests-sei4][funcional][oracle] TramiteProcessoContendoDocumentoMovidoDestino.png

	[tests-sei4][funcional][sqlserver] TramiteProcessoContendoDocumentoMovidoDestino
/home/carlos/Desktop/desenv/379-completo/tests_sei4/funcional/evidencias/[tests-sei4][funcional][sqlserver] TramiteProcessoContendoDocumentoMovidoDestino.png



SEI:
	[tests-sei][funcional][mysql] TramiteProcessoContendoDocumentoMovidoDestino
/home/carlos/Desktop/desenv/379-completo/tests_sei/funcional/evidencias/[tests-sei][funcional][mysql] TramiteProcessoContendoDocumentoMovidoDestino.png

	[tests-sei][funcional][oracle] TramiteProcessoContendoDocumentoMovidoDestino
/home/carlos/Desktop/desenv/379-completo/tests_sei/funcional/evidencias/[tests-sei][funcional][oracle] TramiteProcessoContendoDocumentoMovidoDestino.png

	[tests-sei][funcional][sqlserver] TramiteProcessoContendoDocumentoMovidoDestino
/home/carlos/Desktop/desenv/379-completo/tests_sei/funcional/evidencias/[tests-sei][funcional][sqlserver] TramiteProcessoContendoDocumentoMovidoDestino.png

**Comment by carlosevmelo** [comment]
Prezados @higodf @caduvieira e @mateussbh,

Consegui subir o ambiente do SEI3 e estou incluíndo a evidência de teste no SEI3 MySQL.

Obs: ainda está com erro para subir os ambintes:
-SEI3 Oracle
-SEI3 SQLServer

Execução dos testes:

SEI 3:
[tests-sei3][funcional][mysql] TramiteProcessoContendoDocumentoMovidoDestino
![tests-sei3 funcional mysql  TramiteProcessoContendoDocumentoMovidoDestino](https://github.com/pengovbr/mod-sei-pen/assets/15729050/38bb1298-f152-4491-bf6d-e210b1306b63)
