### ISSUE TITLE
Mapeamento de Tipos de Processo: Exclusão de Tipos de Processos Mapeados

### ISSUE THREAD

**Issue by yurioliveiramgi** [pengovbr/mod-sei-pen#384]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Atualmente a página de mapeamento de Tipos de Processo não possui uma funcionalidade que possibilite a exclusão dos tipos de processos já mapeados.

-----

**Descreva a solução que você gostaria**
É solicitado que seja incluído um botão com a funcionalidade _Excluir_, similar aos demais já existentes na página, localizado entre os botões _Salvar_ e _Fechar_.
A forma de funcionamento do botão deve ser similar ao botão excluir existente na página de listagem dos _**Tipos de Processo**_, exigindo do usuário uma confirmação de exclusão.
Também deve ser incluída na listagem dos tipos de processos já mapeados, uma _check-box_ que permita a seleção individual de cada tipo de processo ou a seleção de todos os tipos de processos listados de uma única vez. Da mesma forma que é feito na página de listagem dos **_Tipos de Processo_**. 

A navegação na página deve seguir os mesmos padrões, exibindo quantidades limitadas de itens, assim como na página de listagem dos **_Tipos de Processo_**.

**Visualização da situação esperada**
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/ade73def-46ed-41e8-95bb-b6e62e28a4ff)

**Comment by euviniciusmendonca** [comment]
@yurioliveiramgi aprovado.

@yuribitu @davidnascimento1618 @sergioadao @higodf

**Comment by davidnascimento1618** [comment]
_Issue_ movida da _sprint_ 28 para a 29 para validação.

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, foi encontrado os seguintes itens:

- [ ] <s>**1.** O sistema está desmarcando os _checkboxes_ dos tipos de processo que foram marcados para exclusão, caso o usuário mude de página;</s>
- [ ] <s>**2.** Botão de excluir está sendo exibido mesmo com nenhum _checkbox_ marcado (deveria ser exibido se pelo menos um item for selecionado);</s>
- [ ] **3.** O sistema está apresentando o seguinte erro: _"Ação '' não reconhecida pelo controlador."_, caso seja selecionado um ou mais tipos de processo via botão de 'Excluir'.

Abaixo segue um _.gif_ reproduzindo o erro encontrado no item **3**:

![O sistema está apresentando o seguinte erro:  Ação '' não reconhecida pelo controlador , caso seja selecionado um ou mais tipos de processo via botão de 'Excluir'](https://github.com/pengovbr/mod-sei-pen/assets/87980947/7811c6da-1b31-4d00-ab1c-b1974056b930)


**OBS.:** os itens **1** e **2** foram desconsiderados, uma vez que nas outras telas do SEI esse comportamento já existe.

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, corrigir os [pontos elencados](https://github.com/pengovbr/mod-sei-pen/pull/391#pullrequestreview-1734743196) nos testes funcionais automatizados do _pull request_ em questão.

**Comment by Mauro1706** [comment]
Movida da sprint 28 para 29

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, o erro apresentado no item **3** deste [_comment_](https://github.com/pengovbr/mod-sei-pen/issues/384#issuecomment-1814624087) ainda continua.

**Comment by Mauro1706** [comment]
tarefa movida de sprint 29 para sprint 30

**Comment by mateussbh** [comment]
Funcionalidade testada com sucesso nas versões sei-oficial (antigo super), nos bancos mysql, oracle e sqlserver, no sei 4, versões de banco mysql, oracle e sqlserver, e sei3, versão de banco mysql.

Foi seguido um roteiro de testes, conforme documento (https://mtegovbr.sharepoint.com/:o:/s/Super.br/EtqPl3ipk2xOpTesIG25hwcBk1YxDoLax5bhcRBH18-b9w?e=uy8UtN), para registrar os casos de testes testados, e em quais versões do sistema e banco de dados.


Issues que fazem parte do pacote da funcionalidade "mapeamento de tipo de processo":

**Mapeamento de Tipos de Processos: Cadastro de Relacionamento entre Órgãos**
	https://github.com/pengovbr/mod-sei-pen/issues/250 
	
**Mapeamento de Tipos de Processos: Relacionamento entre Órgãos**
	https://github.com/pengovbr/mod-sei-pen/issues/251 

**Mapeamento de Tipos de Processos: Mapeamento de Tipo de Processo - [Nome do órgão origem]**
	https://github.com/pengovbr/mod-sei-pen/issues/324 
	
**Mapeamento de Tipos de Processos: Ação Reativar o mapeamento de órgão externo**
	https://github.com/pengovbr/mod-sei-pen/issues/253 

~~**Mapeamento de Tipos de Processos: Importar Tipos de Processos para mapeamento**
	https://github.com/pengovbr/mod-sei-pen/issues/257~~ [DUPLICADA]
	
**Mapeamento de Tipos de Processos: Importar no destinatário o arquivo com Tipos de Processo do remetente**
	https://github.com/pengovbr/mod-sei-pen/issues/254 

~~**Mapeamento de Tipos de Processos: Exportar Tipos de processos em arquivo**
	https://github.com/pengovbr/mod-sei-pen/issues/256~~  [DUPLICADA]
	
**Mapeamento de Tipos de Processos: Exportar Tipos de Processo do órgão remetente**
	https://github.com/pengovbr/mod-sei-pen/issues/252 

**Mapeamento de Tipos de Processo: Exclusão de Tipos de Processos Mapeados**
	https://github.com/pengovbr/mod-sei-pen/issues/384 

**Mapeamento de Tipos de Processos: Aplicar mapeamento automático de t. processo no recebimento**
	https://github.com/pengovbr/mod-sei-pen/issues/255

**Comment by euviniciusmendonca** [comment]
Após a validação negocial, a DIVIN liberou a release da versão 3.5.0 na qual está incluída a funcionalidade Mapeamento de Tipo de Processos.
