### ISSUE TITLE
Caracteres inválidos no nome da espécie no produtor

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-pen#39]
O nome da espécie documento informada pelo produtor está sendo armazenada em banco de dados com encode errado, o que gera caracteres errados em letras acentuadas. Este problema não é crítico pois esta informação atualmente não é apresentada na interface do SEI.

**Comment by michael-ferreira2022** [comment]
Após gerar registro no banco de dados através do mod-sei-pen foi verificado que o registro na base de dados não apresentou nenhum erro. Poderia detalhar melhor como este problema está ocorrendo afim de que possamos replicá-lo?
