### ISSUE TITLE
Integração do módulo com a base de dados em PostgreSQL do sistema SEI

### ISSUE THREAD

**Issue by pnehme** [pengovbr/mod-sei-pen#395]
Promover as devidas alterações para que o módulo seja integrado ao sistema SEI, usando a base de dados em PostgreSQL.

**Comment by santosleonardo** [comment]
#366 Pode ser útil.

**Comment by caduvieira** [comment]
@santosleonardo caso haja necessidade de uso rápido do módulo e seja possível a alteração do banco use o MySQL.

**Comment by marvdias** [comment]
Teste full sei oficial

![Image](https://github.com/pengovbr/mod-sei-pen/assets/31357298/4063abde-1c7e-4d2c-99b1-ac14b03abb88)

**Comment by marvdias** [comment]
Testes full sei 4

![Image](https://github.com/pengovbr/mod-sei-pen/assets/31357298/e1b7e3af-e70b-4555-a736-77e51f3288b1)

**Comment by marvdias** [comment]
Resultados do phpcs + phpcbf

![Image](https://github.com/pengovbr/mod-sei-pen/assets/31357298/cdc0ad4c-b5c4-4dad-a658-0da040bda601)

**Comment by marvdias** [comment]
[Video funcionamento](https://drive.google.com/file/d/1CoQtdnRDzJmweg-PLEAO2SrlyJjG1cPj/view?usp=sharing)
