### ISSUE TITLE
Falha de hash. Doc gerado com hash diferente do que o barramento espera

### ISSUE THREAD

**Issue by soldate** [pengovbr/mod-sei-pen#411]
Olá pessoal, sou do TJDFT e estou enfrentando problemas de hash.

vi essa issue https://github.com/pengovbr/mod-sei-pen/issues/285

e estou enfrentando algo parecido.

Verifiquei que no ExpedirProcedimentoRN.php, método "obterDadosArquivo", tem o tratamento "pra evitar falhas de hash" (comentário no código!).

Pelo que entendi, se o documento foi gerado no editor do SEI, ele (re)gera o documento, aí se tiver alguma mudança (ex: o modelo usa algum valor da INFRA_PARAMETRO que tenha alterado), aí não tem mais como gerar exatamente o mesmo documento e dá falhas de hash.

Estou com processos parados no TJDFT pra enviar ao GDF, pois não sei como regerar o documento com o mesmo hash que o barramento espera.

Esse problema precisa ser melhor debatido, não dá pra proibir a pessoa de assinar um documento.. creio que o barramento deveria permitir os hashes não baterem e só mostrar um alerta, algo assim.

Pode ser que eu não esteja entendendo direito o problema, mas enfim, estou precisando de ajuda.. Obrigado!

**Comment by caduvieira** [comment]
Abra um chamado no https://portaldeservicos.economia.gov.br/ com versão do SEI, versão do módulo, infra log e printscreen. 

Sem saber mais informações informo que na versão 3.3.0+ pode ser habilitado o envio parcial do processo e, caso o destino esteja habilitado para receber parcial, esse erro de hash é superado.
