### ISSUE TITLE
Inclusão da Alteração do Tipo de Processo no Andamento do Processo

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#416]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Ao receber um processo por meio do Tramita dependendo do tipo de processo, esse poderá ser reclassificado de acordo com as regras de recebimento. O recomendado é a inclusão dessa alteração no andamento do processo.

-----

**Descreva a solução que você gostaria**
Se o processo receber um novo tipo de processo, incluir a alteração no momento do recebimento no andamento do processo.

<img width="797" alt="image" src="https://github.com/pengovbr/mod-sei-pen/assets/60577185/ab43e461-4063-4da5-842b-f1e61c5623a5">

-----

**Descreva alternativas que você considerou**
Não se aplica.
-----

**Contexto adicional**
Não se aplica.

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @mateussbh, teste realizado com a versão 3.1.7......não é apresentado, ao consultar andamento do processo a alteração via mapeamento.....segue evidência em 2 vídeos.....

https://github.com/pengovbr/mod-sei-pen/assets/87815724/5d839c5f-f808-4fc8-bb13-946da04d20bd


https://github.com/pengovbr/mod-sei-pen/assets/87815724/a6f029a7-2443-47f9-9ca7-d532f5e457f4

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @mateussbh, teste realizado com a versão **4.0.12**......não é apresentado, ao consultar andamento a alteração do processo via mapeamento.....segue evidência em 2 vídeos.....PR422


https://github.com/pengovbr/mod-sei-pen/assets/87815724/102d47c6-32e0-4972-9e8f-513a1992823c


https://github.com/pengovbr/mod-sei-pen/assets/87815724/2a30db19-bc90-47f1-9c6b-ba7fc2195368

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @mateussbh, teste realizado com a versão **4.0.12.15** ......não é apresentado, ao consultar andamento a alteração do processo via mapeamento.....segue evidência em 2 vídeos.....PR422


https://github.com/pengovbr/mod-sei-pen/assets/87815724/818dc3a2-c692-4444-9615-0e2c2af439f0


https://github.com/pengovbr/mod-sei-pen/assets/87815724/4b063984-1f51-41e1-b05d-0ffef4d3142b

**Comment by sergioadao** [comment]
Boa tarde @Mauro1706 e @mateussbh, teste realizado com a versão 4.0.12.15......testada e valida ...implementação funcional.....segue evidência em 2 vídeos.....PR422

https://github.com/pengovbr/mod-sei-pen/assets/87815724/b7e2ee9d-6489-4d4b-8ee9-0d16bb9ef249


https://github.com/pengovbr/mod-sei-pen/assets/87815724/992b4af2-529d-4aa1-b157-0cd24804c2cd

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @mateussbh, teste realizado com a versão **3.1.7**......testada e valida ...implementação funcional.....segue evidência em 2 vídeos.....PR422



https://github.com/pengovbr/mod-sei-pen/assets/87815724/89ab163e-929a-4550-b5a4-7a4225a06b72



https://github.com/pengovbr/mod-sei-pen/assets/87815724/9c8e5c62-e8b1-46ff-9d55-d89f8313ca8d

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 e @mateussbh, teste realizado com a versão **4.0.12**.....testada e valida ...implementação funcional.....segue evidência em 2 vídeos.....PR422


https://github.com/pengovbr/mod-sei-pen/assets/87815724/9e679ed8-27a4-4444-8957-ea2e3b3f6bdc


https://github.com/pengovbr/mod-sei-pen/assets/87815724/92e6c30a-12c4-49d5-aaa3-4209ff36de11

**Comment by mateussbh** [comment]
Prezados, após alinhamento interno, ficou estabelecida a necessidade de se retirar as condições e novos códigos de dentro do método gerarProcedimento, e passar para um método apartado, de modo que este já existente não fique muito complexo e grande demais, bem como incluir o teste funcional e o teste unitário do método novo.

**Comment by sergioadao** [comment]
@mrglaydson ....boa tarde......Glaydson, fui construir a imagem docker da ISSUE 416 - PR 422 e deu o erro abaixo (ambiente SEI4/MYSQL) :

toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-4.0.12.15/src/sei/web/modulos/mod-sei-pen$ make destroy; make up; make install
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env down --volumes
Removing network funcional_default
WARNING: Network funcional_default not found.
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env up -d
Creating network "funcional_default" with the default driver
Pulling smtp (processoeletronico/vagrant_super4_mailcatcher:9.8)...
**ERROR: manifest for processoeletronico/vagrant_super4_mailcatcher:9.8 not found: manifest unknown: manifest unknown**
make: *** [Makefile:155: up] Erro 1

Testando se a pagina de login responde para o org1...
Tentativa 1/15
^Cmake: *** [Makefile:55: check-isalive] Interrupção

**Comment by sergioadao** [comment]
@Mauro1706 ....Bom dia....Refiz o teste da ISSUE 416 com a PR 422 a linha que indica alteração do tipo de processo....que já aparecia.....não aparece mais.....segue evidência:

https://github.com/pengovbr/mod-sei-pen/assets/87815724/e7af96c8-d44b-4ded-bd8f-b6890ca64bcb


https://github.com/pengovbr/mod-sei-pen/assets/87815724/77846edd-5654-4f38-b443-80a68f526aaa

**Comment by amelquia** [comment]
20/05/24
Priorização no momento, é finalizar o módulo de Gestão Documental.

**Comment by amelquia** [comment]
21/05/24
Removendo a issue da sprint atual, uma vez que o foco encontra-se direcionado para a entrega das issues do módulo Gestão Documental.

**Comment by sergioadao** [comment]
Bom dia @Mauro1706, @mateussbh , @amelquia e @yurioliveiramgi ....testes realizados com a issue e confirmada a inclusão da observação de troca do nome do processo. Segue evidência:

OBS: SEI 4.1.1 branch release/3.7.0



https://github.com/pengovbr/mod-sei-pen/assets/87815724/7b677ed8-04d1-466a-9666-c6e11b5fdd63

https://github.com/pengovbr/mod-sei-pen/assets/87815724/accd4070-88c2-40b3-9a59-b1718fe16cad

**Comment by amelquia** [comment]
21/06/24
Movimento da issue em **Em Análise P.O.** para a Sprint 45 .

**Comment by amelquia** [comment]
24/06/24
Issue testada e validada pelo @yurioliveiramgi  e, com autorização do mesmo, estou movendo o card para **"Aceite Negocial".**
