### ISSUE TITLE
Refatoração de testes funcionais usando Fixtures. TramiteProcessoAnexadoComDevolucaoTest e TramiteProcessoAnexadoTest

### ISSUE THREAD

**Issue by mateussbh** [pengovbr/mod-sei-pen#420]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Hoje muitos testes estão demorando demasiado tempo para concluírem e estão muito verbosos, prejudicando a execução tempestiva do teste automatizado completo e piorando sua eficiência. Alguns chegam a demorar 5 a 10 minutos somente para chegar no ponto que efetivamente ocorreria o teste da funcionalidade em questão.

-----

**Descreva a solução que você gostaria**
Faz-se necessário começarmos a refatoração dos testes funcionais, de modo que esses passem a usar classes de fixtures e DTOs, e para que o teste gaste tempo prioritariamente testando o que está proposto no escopo, e deixando a cargo das Fixtures a inclusão de dados e a montagem do cenário  que antecede ao teste em si da funcionalidade, objetivando testes mais limpos e fáceis de entender.

Para esta issue, foram selecionados inicialmente 2 testes a serem refatorados, são eles:
- [x] TramiteProcessoAnexadoComDevolucaoTest
- [x] TramiteProcessoAnexadoTest

-----

**Descreva alternativas que você considerou**
N/A

-----

**Contexto adicional**
Favor realizar a entrega dos códigos nas pastas das versões do SEI-Oficial (antigo super), SEI 4 e SEI3, e testá-los para as respectivas versões.

Obrigado.

**Comment by marvdias** [comment]
Segue evidência da refatoração dos testes: [TramiteProcessoAnexadoComDevolucaoTest](https://drive.google.com/file/d/17vfCm4qcU-QU0J84VlTiZQzBcilIhCPj/view?usp=drive_link)  e  [TramiteProcessoAnexadoTest](https://drive.google.com/file/d/1T_uQgWHAtnXxwlmX99r-N4XaNNCI2Bja/view?usp=drive_link)

**Comment by mateussbh** [comment]
Prezado, favor implementar os testes para a versão 3 e 4 do SEI.

**Comment by marvdias** [comment]
Segue evidência da refatoração dos testes para o sei3 e sei4: [TramiteProcessoAnexadoComDevolucaoTest_sei4](https://drive.google.com/file/d/1LOwjHQaGlb-UspU0_M4LOpTadpDNqam2/view?usp=sharing)  , [TramiteProcessoAnexadoTest_sei4](https://drive.google.com/file/d/19-9zswFtzfPOeInOE6NmHU0GZLrlZUkv/view?usp=sharing) , [TramiteProcessoAnexadoComDevolucaoTest_sei3](https://drive.google.com/file/d/1PhexEIAhqRkmFcff6Oa_pXDosHIyoO2M/view?usp=sharing)  , [TramiteProcessoAnexadoTest_sei3](https://drive.google.com/file/d/17kSSIN7XCJ-Drd6EzT0s23IHpBMqibMf/view?usp=sharing)

**Comment by mateussbh** [comment]
Prezado @marvdias , conforme alinhamento com a coordenação na data de ontem, solicitamos que sejam transferidos as fixtures comuns (que serão usados também por testes de outros módulos) para dentro da estrutura do SEI, deixando na estrutura do Módulo do Tramita somente as fixtures e arquivos específicos para serem usado unicamente nos testes do Tramita. Obrigado.

**Comment by marvdias** [comment]
@mateussbh, conforme foi acertado, removi as fixtures que correspondem ao SEI deste PR, e realizei as modificações para que as fixtures utilizadas sejam as do SEI.
Notar que o .env deve ser modificado nos campos 
ORG1_DATABASE_HOST=org1-database  
ORG2_DATABASE_HOST=org2-database

**Comment by mateussbh** [comment]
Prezado, conforme alinhamento, tendo em vista a release 3.6.0 também mexerá na forma de usar fixtures e na estrutura de arquivos dos testes, vamos esperar a release citada ir pra master, para depois fazer o rebase com essa, incluindo somente o que for necessário, para evitar conflitos com merge. Desta forma, vou colocar esta issue interna momentaneamente como suspensa.

**Comment by mateussbh** [comment]
Prezado, favor criar novo PR, baseado na branch release 3.6.0, tendo em vista que nesta pré-release foi estabilizada a estrutura de teste usando Fixtures, e evitando alguns conflitos observados em merges recentes. Obrigado.

**Comment by mateussbh** [comment]
Prezado, conforme alinhamento, precisamos limpar esse PR, tendo em vista que os arquivos alterados da fixture já estão na master (e na branch release/3.7.0). Desta forma, peço que deixe somente os arquivos relacionados à refatoração dos respectivos testes.

**Comment by marvdias** [comment]
Rebase efetuado no PR https://github.com/pengovbr/mod-sei-pen/pull/484
