### ISSUE TITLE
Ausência de data nas informações do bloco interno após atualização do Sei 3.1.15 para 4.0.

### ISSUE THREAD

**Issue by FeeeeelipeR** [pengovbr/mod-sei-pen#432]
**Descreva o erro**

Faço parte do Suporte SEI no órgão da Agência Nacional do Cinema - ANCINE.
Percebemos que a informação DATA não está presente na nova atualização da versão 4.0 e também não consta na aba de configuração.

-----

**Para reproduzir**

Passos para reproduzir o comportamento:
1. Vá para 'Bloco Interno'
2. Clicar no número do bloco criado
3. Verificar as informações contidas no Bloco Interno
-----

**Comportamento esperado**
Aparecer as informações como constava na versão 3.1.15.

**Screenshots**

Versão 3.1.15
![image](https://github.com/pengovbr/mod-sei-pen/assets/137176465/59ce8ce7-dd17-484e-bd03-afea9f234510)

Versão 4.0
![image](https://github.com/pengovbr/mod-sei-pen/assets/137176465/fe1b8ba3-ffac-47c9-b9ed-e3bd0e0b989e)

**Comment by caduvieira** [comment]
Essa issue não é do módulo do tramita. Ela é do SEI. Favor abrir no repositório do SEI.
