### ISSUE TITLE
Execução de rodadas de testes completos referentes do blocos de tramite externo

### ISSUE THREAD

**Issue by yurioliveiramgi** [pengovbr/mod-sei-pen#433]
Para fins de registro, foi solicitado à equipe de desenvolvimento ação conjunta na execução, correção e validação dos testes completos referentes à issue #306 e suas correlacionadas.

Para suas complementações @mateussbh, @Mauro1706, @carlosevmelo e @mrglaydson

**Comment by caduvieira** [comment]
Está cadastrado como ação. @Mauro1706  por favor adicionar os erros encontrados nos testes, caso existam, e evidências dos testes executados.

**Comment by Mauro1706** [comment]
Evidência para sei-oficial = mysql
[teste-sei-oficial-mysql.txt](https://github.com/pengovbr/mod-sei-pen/files/14607471/teste-sei-oficial-mysql.txt)

**Comment by Mauro1706** [comment]
[teste full - bloco externo.zip](https://github.com/pengovbr/mod-sei-pen/files/14615979/teste.full.-.bloco.externo.zip)

**Comment by mateussbh** [comment]
Funcionalidade do bloco externa finalizada e testada com sucesso nas versões sei 4.0.12.15, 4.0.12 e 3.1.7, nos BDs mysql, oracle e sqlserver. 

Comentários foram majoritariamente centralizados nas issues 306 e 292.  O PR com os arquivos da funcionalidade (pré-release) é o https://github.com/pengovbr/mod-sei-pen/pull/424.
