### ISSUE TITLE
Alterar mensagem de Envio em Lote

### ISSUE THREAD

**Issue by marlinhares** [pengovbr/mod-sei-pen#435]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Atualmente ao enviar processo(s) pela funcionalidade Bloco de Envio Externo, aparece a mensagem:

<img width="607" alt="image" src="https://github.com/pengovbr/mod-sei-pen/assets/60577185/b25acabc-ac47-4ba0-a270-c9cc214164ed">

Essa mensagem leva o user a conclusões incorretas pois o processo ainda não foi tramitado. Foi apenas encaminhado para a fila de envio.

-----

**Descreva a solução que você gostaria**

Para evitar dúvidas, a mensagem deve ser algo como:

- Processo(s) aguardando envio. Acompanhar tramitação através da funcionalidade: "Processos Tramitados em Bloco"

Mudar a label da Modal:

- Cadastro de processos em Bloco.

-----

**Descreva alternativas que você considerou**

-----

**Contexto adicional**

**Comment by marlinhares** [comment]
@higodf criada a issue aqui.
@caduvieira esse problema de interpretação é recorrente entre os users

**Comment by euviniciusmendonca** [comment]
A issue precisa ser ajustada. O Envio em Lote foi descontinuado. A partir do momento, referir tudo como Bloco de Envio Externo.

**Comment by caduvieira** [comment]
Sim. Isso pode trazer confusão para o usuário @marlinhares. Provavelmente será necessário alterar o componente UI de envio.

**Comment by mateussbh** [comment]
@Mauro1706 , 

Após alinhamento com o PO, peço para alterar a mensagem para:

Processo(s) aguardando envio. Favor acompanhar a tramitação por meio do bloco, na funcionalidade "Blocos de Trâmite Externo".

Obrigado.

**Comment by mateussbh** [comment]
Validada. 

![image](https://github.com/pengovbr/mod-sei-pen/assets/3789823/e6331077-f8a0-4875-ab92-c26d75cdabf1)

**Comment by amelquia** [comment]
14/05/24
Issue movida para a sprint 42 para dar sequencia ao fluxo (próximo passo : Concluído).
