### ISSUE TITLE
Refatoração do teste TramiteProcessoComDevolucaoAnexadoOutroTest

### ISSUE THREAD

**Issue by mateussbh** [pengovbr/mod-sei-pen#442]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Prezados, favor refatorar o teste **TramiteProcessoComDevolucaoAnexadoOutroTest**, se baseando na estrutura de arquivos atualizada para usar as fixtures.

-----

**Descreva a solução que você gostaria**
Exemplo de PR que contém a nova estrutura de fixtures: https://github.com/pengovbr/mod-sei-pen/pull/424, para inspiração.

-----

**Descreva alternativas que você considerou**
N/A

-----

**Comment by mateussbh** [comment]
Vamos aguardar o pacote de funcionalidades (que contém hoje o PR 424) ir para master, para poderem fazer o rebase e aprovarmos essa issue, e a issue 420, para evitar muitos conflitos, tendo em vista que o PR 424 está testado e estes testes refatorados mexem em muitos arquivos que a 424 mexeu.

**Comment by marvdias** [comment]
Teste refatorado utilizando fixtures, PR no aguardo da nova release para fazer rebase. Segue evidencia de teste a seguir:

![Image](https://github.com/pengovbr/mod-sei-pen/assets/31357298/cf93613e-4734-452a-ace8-65c477b8040c)

**Comment by mateussbh** [comment]
Prezado, favor criar novo PR, baseado na branch release 3.6.0, tendo em vista que nesta pré-release foi estabilizada a estrutura de teste usando Fixtures, e evitando alguns conflitos observados em merges recentes. Obrigado.

**Comment by marvdias** [comment]
Videos de evidência dos testes funcionais do teste TramiteProcessoComDevolucaoAnexoOutroTest para o [sei 4](https://drive.google.com/file/d/1kBB4yzf295vomp0IfVh5r1gLbGVkK4uF/view?usp=sharing) e [sei oficial](https://drive.google.com/file/d/1BGWOQM8zO_Sd2HywjlRbmnozSE-LbgnQ/view?usp=sharing)

**Comment by mateussbh** [comment]
Prezado, conforme alinhamento, precisamos limpar esse PR, tendo em vista que os arquivos alterados da fixture já estão na master (e na branch release/3.7.0). Desta forma, peço que deixe somente os arquivos relacionados à refatoração dos respectivos testes. Ou senão criar novo PR baseado na 3.7.0, somente com os arquivos que de fato são os alterados de testes.

**Comment by marvdias** [comment]
Rebase efetuado no PR https://github.com/pengovbr/mod-sei-pen/pull/484
