### ISSUE TITLE
Evolução da Funcionalidade Processos Tramitados em Bloco

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#475]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Após a descontinuação das funcionalidades relacionadas ao Envio em Lote, bem como renomeação da tela de Processos Tramitados em Lote para Processos Tramitados em Bloco, é preciso analisar o impacto nessa funcionalidade acessada por meio de Tramita GOV.BR --> Processos Tramitados em Bloco.

-----

**Descreva a solução que você gostaria**

1) Alterar na tabela o nome da coluna de ID Lote para ID bloco e verificar a possibilidade de ao clicar o ID, o usuário ser redirecionado ao Bloco;
2) Incluir nessa tela também os processos recusados num envio em Bloco;
3) Adequar situações de um processo enviado em Bloco.

-----

**Descreva alternativas que você considerou**
Não se aplica.

-----

**Contexto adicional**
Não se aplica.

**Comment by euviniciusmendonca** [comment]
@yurioliveiramgi para documentação.

**Comment by euviniciusmendonca** [comment]
@mateussbh @yurioliveiramgi 

Alguma novidade a respeito da remoção da funcionalidade Processos Tramitados em Bloco?

**Comment by yurioliveiramgi** [comment]
Em reunião realizada na data de hoje, ficou estabelecido que, diante da eminência de elaboração de uma issue para tratar da refatoração das situações dos trâmites realizados em bloco:
- [ ] o item do Menu "Processos Tramitados em Bloco" deve ser omitido da barra de navegação, tornando assim a tela inacessível ao usuário. (ATENÇÃO! A tela deve ser omitida e não excluída);
- [ ] o item do Menu "Processos Tramitados Externamente" bem como o título da sua tela devem ser renomeados para "Processos em Tramitação Externa".
- [ ] na tabela de resultados exibida na tela "Processos em Tramitação Externa" devem ser incluídos setas de ordenação dos campos "Usuário", "Data do Envio" e "Unidade Destino"

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/c848ea39-df05-41cc-bb01-a15451f44fee)


@euviniciusmendonca e @mateussbh

**Comment by sergioadao** [comment]
Boa tarde @marvdias e @mateussbh ....após testes realizados com a ISSUE 475 - PR 498... foi confirmado que o que foi solicitado foi implementado.
Segue evidência:
**OBS: Foi utilizada a branch release/3.7.0**

https://github.com/pengovbr/mod-sei-pen/assets/87815724/cff6ba9a-f3ad-41c9-a899-d85043d701da


https://github.com/pengovbr/mod-sei-pen/assets/87815724/db87a8fb-1a15-418f-8a5a-5832adbb0bdd
