### ISSUE TITLE
Tratamento de Mensagem pelo Módulo - A unidade [Nome da Unidade]([ID da Unidade]) foi mapeada de forma errada. Desse modo, entre em contato com os Gestores do seu órgão e informe que o mapeamento não está correto.

### ISSUE THREAD

**Issue by euviniciusmendonca** [pengovbr/mod-sei-pen#481]
**Descreva o erro**
Após a evolução de uma mensagem da API, o módulo foi impactado. Anteriormente, era emitida uma mensagem tratada pelo módulo e não a mensagem emitida pela API.

A mensagem originalmente emitida pela API:

**Transação não autorizada, pois o sistema não é responsável pela estrutura organizacional remetente**

A nova mensagem:

**A unidade [Nome da Unidade]([ID da Unidade]) foi mapeada de forma errada. Desse modo, entre em contato com os Gestores do seu órgão e informe que o mapeamento não está correto.**

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. No seu ambiente, configure em Tramita GOV.BR --> Mapeamento de unidades, um mapeamento utilizando a unidade de um órgão que não faça parte do órgão vinculado ao seu sistema no Portal de Administração. Por exemplo: utilizar uma unidade do Ministério da Saúde, sendo que o sistema é vinculado ao Ministério da Educação.
2.  Tente realizar um trâmite na unidade do sistema que foi relacionada a essa unidade errada e uma mensagem é exibida, informando que não é possível realizar o trâmite.
 
-----

**Comportamento esperado**
O código fonte do módulo atualizado para emitir a mensagem da API.

-----

**Screenshots**
Não se aplica.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
Não se aplica.

-----

**Informações adicionais**
Não se aplica.

-----
**Log de Erros**
Não se aplica.

**Comment by caduvieira** [comment]
Vai ser exibido o erro que vier da API. Deve-se retirar o tratamento específico para essa antiga mensagem. Caso a mensagem da API sofra nova alteração a mensagem exibida vai ser a nova.

**Comment by mateussbh** [comment]
Validada a retirada do código e a msg vinda direto da API.
![Screenshot from 2024-04-19 14-27-44](https://github.com/pengovbr/mod-sei-pen/assets/3789823/d16b1524-eef5-4f14-bc33-8b0a7fe9fda7)

**Comment by yurioliveiramgi** [comment]
@amelquia , sabe informar qual o débito técnico que está relacionado à esta issue?

**Comment by yurioliveiramgi** [comment]
@amelquia , vamos manter a tag de "débito técnico" nesta issue?

**Comment by mateussbh** [comment]
> @amelquia , sabe informar qual o débito técnico que está relacionado à esta issue?

Ela foi considerada por si só um débito técnico no momento da sua concepção. Não teriam outros débitos relacionados a essa issue.

**Comment by caduvieira** [comment]
Essa mensagem vem do Tramita? Nem todo SPE usao conceito de mapeamento. O SAPIENS, pelo que o pessoal dos correios comentaram, não usa.
