### ISSUE TITLE
Compatibilidade com a versão 4.1.2

### ISSUE THREAD

**Issue by gsdiniz** [pengovbr/mod-sei-pen#488]
Baseado no documento do sei 4.1.2
[SEI-v4.1.2.pdf](https://github.com/pengovbr/mod-sei-pen/files/15012455/SEI-v4.1.2.pdf)

que indica correção de erros, os desenvolvedores acreditam ser possível o uso do módulo nessa versão do SEI?

**Comment by caduvieira** [comment]
Refs #485
