### ISSUE TITLE
Remoção do botão Incluir Processo no Bloco de Trâmite para processos concluídos

### ISSUE THREAD

**Issue by yurioliveiramgi** [pengovbr/mod-sei-pen#496]
Atualmente, mesmo após a conclusão do processo no SEI, a ação de "Incluir Processo no Bloco de Trâmite".

-----
Ao concluir um processo, o botão de ação "Incluir Processo no Bloco de Trâmite" ![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/36b71ba3-2cef-42bb-81b3-36a598f711cb) não deve ser exibido. 

Atualmente:

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/6ee108ff-be35-45e9-8d0a-42741aa725cb)

Depois do ajuste:

![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/458fe89d-b721-40cf-8640-107efaaf75cc)

**Atividades a serem executadas:**
- [] Ocultar botão de ação "Incluir Proceso no Bloco de Trâmite" sempre que o processo se encontrar concluído.

**Comment by euviniciusmendonca** [comment]
@yurioliveiramgi ajustado.

@mateussbh para conhecimento.

O botão foi ocultado após alinhamento com a equipe de arquivistas da CGESP. Posteriormente, vamos tratar o envio de processos concluídos por outra forma - necessidade futura.
