### ISSUE TITLE
Sempre apresenta o botão "Incluir Processo no Bloco de Trâmite" no menu do processo

### ISSUE THREAD

**Issue by neijobson** [pengovbr/mod-sei-pen#523]
**Descreva o erro**
Na versão 3.6.2 do módulo PEN o botão novo sobre processo "Incluir Processo no Bloco de Trâmite" associado ao recurso "pen_incluir_processo_em_bloco_tramite" está sem validações prévia para só exibir o botão QUANDO o usuário logado tenha perfil com o Recurso mencionado.

Daí, o botão é exibido para todos os Usuários Internos, dando estouro na tela aberta em seguida nos casos de usuários com perfil que não tenha o recurso "pen_incluir_processo_em_bloco_tramite".

Os demais botões sobre processo do módulo já validam esse comportamento, para nem montar o botão quando não tem o recurso associado. Apenas nesse novo botão que ficou sem essa validação prévia.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para qualquer processo, em Unidade na qual o Usuário não tenha perfil com o recurso "pen_incluir_processo_em_bloco_tramite".
2. Clique em no botão sobre o processo "Incluir Processo no Bloco de Trâmite".
3. O estouro ocorre pela natural falta do recurso.

-----

**Comportamento esperado**
Sequer deveria apresentar o botão QUANDO o usuário não tenha perfil com o o recurso "pen_incluir_processo_em_bloco_tramite".

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.
![image](https://github.com/pengovbr/mod-sei-pen/assets/49068090/3b9a3ac7-8092-4025-a7ea-023e2916b41c)

![image](https://github.com/pengovbr/mod-sei-pen/assets/49068090/307bccd6-4de1-48e5-a54f-9283d88594ec)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: 4.0.12
 - Navegador: EDGE
 - Perfil do Usuário: Perfil sem o recurso "pen_incluir_processo_em_bloco_tramite "
 - Banco de dados: MySQL
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log
`Acesso negado a este recurso nesta unidade (pen_incluir_processo_em_bloco_tramite / GIIB).
Trilha de Processamento:
0 /opt/appsei/sei/web/modulos/pen/pen_tramite_processo_em_bloco_cadastrar.php(39): InfraSessao->validarPermissao('')
1 /opt/appsei/sei/web/modulos/pen/PENIntegracao.php(705): require_once('')
2 /opt/appsei/sei/web/SeiIntegracao.php(123): PENIntegracao->processarControlador('')
3 /opt/appsei/sei/web/controlador.php(1702): SeiIntegracao->executar('', '')
4 {main}`

**Comment by caduvieira** [comment]
Verificar se podemos lançar no 3.7.0

**Comment by Mauro1706** [comment]
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/531

**Comment by amelquia** [comment]
08/07/24
Planning realizada. 
Card movido para a **Sprint46**.

**Comment by sergioadao** [comment]
@Mauro1706 e @amelquia ..... erro encontrado na execução do SEI 4.1.3 ....segue evidência:

**OBS: Confirmar se o PR 531 foi mergeada na branch release/3.7.0.**


https://github.com/pengovbr/mod-sei-pen/assets/87815724/c12488cf-eb1e-49b7-a531-148985b1f088


https://github.com/pengovbr/mod-sei-pen/assets/87815724/a9d6acea-5ee2-41fd-8b95-b97d6da25563

**Comment by sergioadao** [comment]
@amelquia  e @Mauro1706, após o merge, confirmou-se o manutenção do comportamento da apresentação do botão e menu Trâmite de Bloco que está associado a perfil Básico e atribuído ao usuário.
**OBS: Ambiente SEI 4.1.3 / Branch release/3.7.0**

Segue evidência:

https://github.com/pengovbr/mod-sei-pen/assets/87815724/a364fd22-8560-450a-83cf-ddfbd79bd4f6

**Comment by sergioadao** [comment]
@yurioliveiramgi, @amelquia e @Mauro1706.... Verificou-se que quando o recurso **pen_incluir_processo_em_bloco_tramite** é **desabilitado** no **SIP** o ícone de BLOCO não é visualizado. Porém, a opção do menu TRÂMITE DO BLOCO permanece visível.

Ambiente: SEI 4.1.3 / release 3.7.0


https://github.com/pengovbr/mod-sei-pen/assets/87815724/5c23f389-25a5-4e46-998c-f13ed972079c

https://github.com/pengovbr/mod-sei-pen/assets/87815724/8e6d2fb0-ab3f-4939-82f4-9a80a729ccc0

**Comment by caduvieira** [comment]
Essa issue não tratou do Menu.

**Comment by yurioliveiramgi** [comment]
Bom dia, ainda possuo minhas dúvidas quanto ao "tipo de perfil" que não possuirá acesso ao botão.

De qualquer forma, há um ajuste a ser feito, e este foi repassado ao @marvdias na daily de hoje:
- [ ] O botão ainda está sendo apresentado no menu "interno" do processo, para isso é necessário que sejam respeitadas dois condicionantes:
1. O botão deve possuir comportamento semelhante ao do botão "Envio Externo de Processo", sendo exibido somente nos casos em que a unidade esteja devidamente mapeada;
2. Uma vez que a unidade esteja mapeada, é necessário que o perfil do usuário esteja habilitado para "visualizar" o botão;

Sobre o que já está desenvolvido, para que o comportamento esperado seja observado (com exceção do botão no "menu interno" do processo oculto) é necessário:
1. Configurar um perfil específico no SIP (fiz um clone do perfil básico);
2. Para ocultar o botão "Incluir Processo no Bloco de Trâmite", desabilitar o recurso "pen_expedir_bloco";
3. Para ocultar o item do Menu "Tramita GOV.BR -> Blocos de Trâmite Externo", desabilitar os recursos "md_pen_tramita_em_bloco_excluir" e "md_pen_tramita_em_bloco";

Seguem evidências da configuração do perfil no SIP e da tela exibida no SEI.
![image](https://github.com/user-attachments/assets/03bc6d7e-b77f-432f-a875-8c7086396a4f)

![image](https://github.com/user-attachments/assets/ebbd3002-e3e3-47b1-bbf1-9a440cfa99e1)

@sergioadao , @mateussbh , @euviniciusmendonca e @amelquia , PSC.

**Comment by Mauro1706** [comment]
Foi realizado uma agenda com o @marvdias e o item informado foi tratado na tarefa, onde o validado os recurso de maneira correta
Tarefa: #542

**Comment by yurioliveiramgi** [comment]
@marvdias , PSC
Essa mensagem é exibida logo após criar o processo, e salvar as informações para inclusão de documentos. Acontece para o perfil com os seguintes recursos desabilitados:
1. pen_expedir_bloco
2. md_pen_tramita_em_bloco_excluir
3. md_pen_tramita_em_bloco
Tela 01
![image](https://github.com/user-attachments/assets/df7a75a2-b5f2-46eb-bea5-063322f5c4e8)
Tela 02
![image](https://github.com/user-attachments/assets/b8a25f9c-1375-4f53-acec-a2d5f9f42fdc)
