### ISSUE TITLE
Atualização versão 3.4.0 para a 3.6.2

### ISSUE THREAD

**Issue by dudamark** [pengovbr/mod-sei-pen#532]
Bom dia,
Preciso de uma orientação. 
Posso fazer a atualização da versão do módulo 3.4.0 direto para a versão 3.6.2?
Ou a melhor alternativa é atualizar em ordem: 3.5.0, 3.6.0, 3.6.1 e depois atualizar para a versão 3.6.2.

**Comment by dudamark** [comment]
Fiz um teste e está me retornando os seguintes erros:

"Erro
Ação 'pen_parametros_configuracao' não reconhecida pelo controlador.
Trilha de Processamento:
0 {main}

Erro
Ação 'pen_map_tipo_documento_envio_listar' não reconhecida pelo controlador.
Trilha de Processamento:
0 {main}"

Só que no processo de instalação não ocorreram erros.
![tramita362](https://github.com/pengovbr/mod-sei-pen/assets/75796280/ff516c42-d5aa-477a-8c6a-931205cfb9a2)

**Comment by caduvieira** [comment]
> Fiz um teste e está me retornando os seguintes erros

Não ficou claro o que você fez. Você só disse que fez um teste e deu problema. Você não incluiu o infralog nem o resultado do upgrade. Abra chamado nonportal de serviços caso tenha necessidade ainda. E o upgrade é direto. Não há necessidade de passar um por um
