### ISSUE TITLE
Criar regra de restrição de criação de Blocos de Trâmite Externo

### ISSUE THREAD

**Issue by yurioliveiramgi** [pengovbr/mod-sei-pen#536]
Essa issue decorre do chamado Nº 9311543.

Atualmente a visualização e acesso de Blocos de Trâmite Externo criados em um órgão pode ser visualizado por todas as unidades. De forma que qualquer usuário pode fazer a inserção de processos abertos em sua unidade em quaisquer blocos abertos.
Isso gera um problema operacional na hora de enviar o Bloco de Trâmite Externo. Uma vez que, não necessariamente, todos os processos inseridos no bloco possuirão andamentos abertos na unidade que realiza o envio do bloco. Dessa forma algumas mensagens irão ser exibidas e o trâmite não será realizado.

-----

**Descreva a solução que você gostaria**
A solução pensada para a resolução dessa questão é que os Blocos de Trâmite Externos fiquem acessíveis apenas dentro das unidades em que foram criados. Impossibilitando assim, que usuários de outras unidades façam a inclusão de processos em blocos criados em outras unidades.
- [x] A numeração será iniciada por Unidade, ou seja, cada Unidade terá sua numeração própria e sequencial;
1. O bloco Legado (criado conforme issue #506) será visível para todas as unidades do sistema e receberá a numeração 0;
2. Para as Unidades que já possuem blocos criados, será necessário realizar uma renumeração dos blocos existentes, de forma a manter a numeração sequencial (vide exemplo);
![image](https://github.com/user-attachments/assets/56754d2f-8f84-430e-bd90-5e8ab715fe7e)

- [x] Os blocos não poderão ser movimentados ou disponibilizados para outras unidades;
- [x] Inclusão de processos nos blocos, fica limitada apenas à unidade em que este foi criado;
- [x] Para os blocos já existentes (sistemas que estão atualmente utilizando versões 3.6.1 ou 3.6.2) os blocos 
      já criados não serão visíveis para Unidades que não os criaram;
- [x] Para os processos já incluídos em um bloco, é necessário implementar uma "atualização":
1. O processo ao ser inserido em um bloco de Trâmite Externo, passa a exibir (por meio de uma atualização de tela) no lugar do botão "Incluir Processo no Bloco de Trâmite", um novo botão nomeado "Remover Processo do Bloco de Trâmite" (Vide Evidência)
![image](https://github.com/user-attachments/assets/072b3e03-76b6-4672-bc17-70b2a8b88111)

3. Esse botão irá remover o processo apenas do bloco em que se encontra aberto (mesma regra de exclusão estabelecida no comentário https://github.com/pengovbr/mod-sei-pen/issues/306#issuecomment-2009969351)

**Refinamento Funcional e Técnico**
**Data: 15/07/24**

**Critérios de Aceite**
- [x] Atender todos os itens mencionados acima no item **Descreva a solução que você gostaria**

**Definição de Pronto (D.O.R. - Definition of Ready)**

- [x] Time de desenvolvimento ciente do trabalho que precisa ser realizado.

**Definição de Feito (D.O.D.Definition of Done)**

- [x] Evidências dos testes realizados.
- [x] Documentação técnica.

**Comment by yurioliveiramgi** [comment]
@euviniciusmendonca PSC

**Comment by yurioliveiramgi** [comment]
@amelquia , @marvdias , @mateussbh e @euviniciusmendonca , PSC.

Segue o ícone a ser inserido conforme descrição da issue. 

Aproveito para solicitar a alteração dos ícones (exibidos na situação do trâmite, dentro do bloco de tramitação externa) de recusa processual e concluído. Atualmente estes são reaproveitados do SEI e com baixa resolução.

![icone-concluido](https://github.com/user-attachments/assets/abb3069d-e7bb-4c78-88e2-f019cee2b039)
![icone-recura](https://github.com/user-attachments/assets/c43bc827-0928-414b-88ac-1e8e2094a12c)
![icone-tramita](https://github.com/user-attachments/assets/86520240-6352-4bb7-b3b4-eeb6f6eb8777)

**Comment by amelquia** [comment]
22/07 - Planejamento da Sprint 47.
Issue transferida com status "Validação Técnica para a sprint 47, porém, foi acordado que o time de negócios no papel do @yurioliveiramgi  também iniciará as validações.

**Comment by yurioliveiramgi** [comment]
@marvdias e @Mauro1706 , irei realizar novos testes, mas a priori, o botão continua sendo exibido na tela "Controle de Processos" mesmo sem nenhum bloco criado. Vide evidência.

https://mtegovbr-my.sharepoint.com/:v:/g/personal/yuri_rodrigues_gestao_gov_br/EZZmutIpTXVDsq2C097VORABkvbOHYxYkBx7BcUabKs7Mg?e=l4zi1a&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

**Comment by yurioliveiramgi** [comment]
@marvdias , @amelquia , @mateussbh e @euviniciusmendonca , sobre a validação da issue, alguns itens ainda precisam de subir um novo ambiente com a última PR para fazer validação:

- [ ] Exibição do botão "Incluir Processo em Bloco de Trâmite Externo" somente para unidades mapeadas;
     - [ ] Na página "Gerenciamento de Processos";
     - [ ] No menu interno do processo.
- [ ] Numeração dos blocos iniciada em cada unidade;
- [ ] Existindo blocos criados, a reordenação é feita conforme a numeração das unidades em que estes foram criados;
- [ ] Não existindo processos tramitados em lote, não é criado o bloco genérico (numeração 0 e visível para todas as unidades);
- [ ] Existindo processos tramitados em lote, é criado um bloco genérico (numeração ) e visível para todas as unidades);
- [ ] Cada unidade visualiza apenas os blocos criados nela;
- [ ] Blocos não podem ser movidos internamente;
- [ ] Ao incluir processo em bloco, serem listados apenas os blocos criados na unidade;
- [ ] Ao inserir o processo no bloco, o botão ser atualizado para "remover processo do bloco...";

    - [ ] Ajuste: O ícone "consultar recibos" deve ser o último exibido na lista de ícones (vide evidência);
    **Antes:**  
    ![image](https://github.com/user-attachments/assets/d05ac85d-ad57-4e1c-9b3a-b64e6dba3a77)
    **Depois:**
    ![image](https://github.com/user-attachments/assets/17cf5437-b57e-489c-94f1-5980c08342c0)

    - [ ] Ajuste: Para evitar que o processo seja tramitado individualmente, estando inserido em um bloco (o que gera uma sequência de erros no funcionamento dos blocos), uma vez que o processo for inserido no bloco, o botão "Envio de Trâmite Externo" será ocultado.
    **Antes:**
    ![image](https://github.com/user-attachments/assets/506461a4-bddc-4240-b73e-9bcd52b98a1e)
    ![image](https://github.com/user-attachments/assets/1b3ec5a6-306a-4da4-8339-8821594f9c25)
    **Depois:**
    ![image](https://github.com/user-attachments/assets/34f36b6f-9a81-4a74-a8ef-09d96d9be226)
    ![image](https://github.com/user-attachments/assets/6c4d06a7-4a01-412a-b1fe-f6c9d17768bf)
    
    - [ ] Ajuste: Após realizar a inserção no bloco, ao clicar em "Ok", a página deve ser atualizada.
    ![image](https://github.com/user-attachments/assets/d7172cf2-d2c4-494c-b7cf-463c4b5605c6)

- [ ] Funcionamento do botão de "remover processo do bloco";
    - [ ] Ajuste: Ao clicar no botão, exibir modal com mensagem de confirmação "Confirma a remoção do processo do bloco de trâmite externo?" Opções "Sim" e "Não";
    - [ ] Ajuste: Alterar a mensagem para "O processo [Nº do Processo] foi removido com sucesso do bloco de trâmite externo";
    - [ ] Ajuste: Após clicar em "remover processo...", ao clicar em "Ok", a página deve ser atualizada.
    ![image](https://github.com/user-attachments/assets/7d74283b-7e33-4e84-ae67-f719cef67ac2)
- [ ] Aplicação dos ícones:
    - [ ] Ícone de recusa;
    - [ ] Ícone de sucesso;
    - [ ] Ícone de "Remover Processo do Bloco de Trâmite Externo".

**Comment by amelquia** [comment]
12/08/24
Planejamento da Sprint 48
Issue em validação técnica transferida para a sprint 48.

**Comment by sergioadao** [comment]
Bom dia @Mauro1706, @mateussbh  e @amelquia....seguem evidências confirmando a correção dos problemas encontrados anteriormente (envio individual de processos inclusos em blocos)....

OBS: Ambiente SEI 4.1.3 / Branch 3.7.0 / Banco Mysql


![Image](https://github.com/user-attachments/assets/a695b0c6-1125-433c-9a33-45232a3bed9d)

![Image](https://github.com/user-attachments/assets/0bd3ce2a-e85b-4646-a80d-83d4f20f48c7)

![Image](https://github.com/user-attachments/assets/1eeb1716-15d0-4038-871c-cf71909dc6ae)

![Image](https://github.com/user-attachments/assets/dd3741cb-abd0-4920-9cc4-c085a805c7c8)

Realizarei os mesmos testes com os bancos SQLServer e Oracle....

**Comment by yurioliveiramgi** [comment]
Foi identificado a necessidade de ajuste no código para o seguinte cenário:
1. Bloco com status "concluído parcialmente" que possui processos "concluído", "recusado" e "aguardando processamento" (processos cancelados no portal e que estão aguardando o cancelamento do trâmite no SEI);
2. Excluindo somente os processos "recusados" o status do bloco é alterado de "concluído parcialmente" para "aguardando processamento";
3. Nessa situação, ao tentar incluir um processo concluído (deste bloco) em outro bloco, é exibido uma mensagem de que o processo não pode ser inserido pois já encontra-se em um outro bloco;
4. Ao mesmo tempo, o processo que está "aguardando processamento" não consegue ter o trâmite cancelado no SEI, pois acusa registro em duplicidade;
5. A situação identificada decorre do fato de que, para processos inseridos em blocos com status "aguardando processamento" o código já bloqueia a inserção em novos blocos, ainda que estes constem com status "concluído".
6. A solução encontrada foi que a validação de inclusão de processos pertencentes a blocos com status "aguardando processamento" fosse feita da mesma forma que para os blocos com status "concluído parcialmente".

Imagens:
Blocos:
![image](https://github.com/user-attachments/assets/00dddf15-ee13-4fa5-a36e-cf0e1b5b8d75)
Processos nos blocos:
![image](https://github.com/user-attachments/assets/1cab770f-eb4c-4f60-bac2-b9ec02a3f82f)
![image](https://github.com/user-attachments/assets/a568caff-49c2-4609-9848-187f0e56d6e4)

**Comment by mrglaydson** [comment]
@yurioliveiramgi @mateussbh feito!

**Comment by amelquia** [comment]
02/09/24
Issues transferidas para a próxima sprint (Sprint 49) aguardando validação técnica.

**Comment by yurioliveiramgi** [comment]
Issue movida para aceito negocial.

Considerando o aceito técnico, e esgotados os possíveis cenários de testes, e não sendo evidenciada nenhuma situação de inconsistência que pode ser reproduzida, pela parte negocial. Considero que as atribuições estabelecidas nesta e na issue #506 foram atendidas. Podendo considerar a validação do aceite negocial.
A nível de conhecimento cenários avaliados foram reproduzidos nas três situações abaixo descritas:
1. Migração entre versões 3.5.0 para 3.7.0;
2. Migração entre versões 3.6.2 para 3.7.0;
3. Execução de cenários na versão 3.7.0 recém instalada.

Cenários:
1. Tramitação envolvendo:
* Processos cancelados;
* Processos cancelados automaticamente (Interrupção do próprio SEI)
* Processos recusados;
* Processos tramitados com sucesso;
* Processos tramitados por bloco;
* Processos tramitados por lote;
* Processos tramitados individualmente;
* Processos restritos com documentos públicos;
* Processos restritos com documentos restritos;
* Processos públicos com documentos restritos;
* Processos públicos com documentos públicos;
* Processos contento documentos externos;
* Processos devolvidos;
* Processos em anexo;
* Processos relacionados;
* Blocos compostos somente por processos criados na mesma unidade em que o bloco foi criado;
* Blocos compostos somente por processos criados em outra unidade em que o bloco foi criado;
* Blocos compostos por processos criados na mesma unidade e em outra unidade em que o bloco foi criado;
* Blocos com estado "em aberto";
* Blocos com estado "concluído";
* Blocos com estado "concluído parcialmente";
* Blocos com estado "aguardando processamento";
* Blocos herdados da versão 3.6.2;
* Blocos criados na versão 3.7.0;
2. Tentativas de tramitação envolvendo:
* Processos com andamentos abertos em mais de uma unidade;
* Processos sem andamento aberto na unidade;
* Processos com documentos sem assinatura;
* Blocos com processos sem andamento aberto na unidade;
* Blocos com processos com andamentos abertos em mais de uma unidade;
* Blocos com processos com documentos sem assinatura;
3. Validação de regras envolvendo:
* Exclusão de processos com situação "concluído" dos blocos;
* Inclusão de processos em mais de um bloco;
* Inclusão de processos com mais de um andamento aberto em blocos;
* Inclusão de processos bloqueados em bloco;
* Inclusão de documentos em processos já inseridos em blocos;
* Alteração de tipo de processo;
* Exclusão de processos dos blocos por meio do botão de ação "Excluir";
* Exclusão de processos dos blocos por meio do ícone "Excluir";
* Exclusão de processos dos blocos por meio do botão "Remover Processo do Bloco";
* Exibição do botão "Incluir Processo em Bloco";
* Exibição do botão "Remover Processo em Bloco";
* Exibição do botão "Envio Externo de Processo";
* Criação de blocos;
* Atualização de estado do bloco;
* Atualização de situação do processo em bloco;
* Exclusão de blocos;
* Reordenação de blocos migrados da 3.6.2;
* Renumeração de blocos migrados da 3.6.2;
* Limitação de acesso aos blocos por outras unidades;
* Atualização de situação de processo incluído em blocos criados por outras unidades;
* Exclusão de processos de blocos criados por outras unidades;
* Exibição de botões de inclusão de processo em bloco, para unidades mapeadas;
* Exibição de funcionalidades para usuário com perfil básico;
* Exibição de funcionalidades para usuário com perfil administrador;
* Unidades diferentes das geradas automaticamente (teste);



Reforço que as mais diversas combinações que contemplem os cenários e as situações descritas acima, foram reproduzidos, testados mais de uma vez. Sempre que uma situação que exigia correção, as combinações eram novamente criadas e validadas, na tentativa de garantir que as mudanças recentes não haviam afetado as validações previamente realizadas.

Durante o período de testes, observou-se que a manutenção do bloco legado, herdado dos trâmites em lote, configurava um gasto de recursos desproporcional à sua funcionalidade, conforme explicitado no comentário https://github.com/pengovbr/mod-sei-pen/issues/506#issuecomment-2305538461. Dessa forma, após a remoção da criação e manutenção do bloco legado relacionado aos trâmites por lote, os testes de validação ganharam uma redução significativa em sua complexidade, além de um ganho bastante robusto no tempo de validação.

Reforço que identificadas modificações relacionadas aos testes automatizados que possam implicar em alterações no funcionamento de eventuais regras negociais, é necessário verificar se alguma destas foram afetadas.

@amelquia , @higodf , @Mauro1706 , @euviniciusmendonca , @mateussbh , @sergioadao , @mrglaydson , PSC.

**Comment by mateussbh** [comment]
Conforme alinhamento entre as áreas, foi atualizada a regra de migração, de modo que não haverá a movimentação de blocos criados na release 3.6.2 para a 3.7.0. O registro deste alinhamento pode ser observado na issue #629, com maiores detalhes.
