### ISSUE TITLE
Ocultar o botão organograma na tela "Envio Externo de Processo"

### ISSUE THREAD

**Issue by yurioliveiramgi** [pengovbr/mod-sei-pen#540]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Como alinhado na reunião realizada na Daily 11/07/2024, o que foi documentado na [ issue 196 ](https://github.com/pengovbr/mod-sei-pen/issues/196#issuecomment-2222854076), bem como após a identificação de que consiste em um bug relacionado a algumas versões do SEI (posteriores à 4.0.12), ficou definido que **por hora esse botão deverá ser ocultado.**

-----

**Descreva a solução que você gostaria**

O botão do organograma será ocultado.

Antes
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/c5b23831-a397-4274-a910-21e580891b57)

Depois
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/f11a8380-4811-47d3-a0a7-803638307d8c)

-----

PSC @euviniciusmendonca

**Comment by euviniciusmendonca** [comment]
@yurioliveiramgi, de acordo.

@amelquia, para tratativa.

**Comment by Mauro1706** [comment]
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/543

**Comment by yurioliveiramgi** [comment]
16/07/24 - Desenvolvimento de acordo com o solicitado. Issue movida para Aceito Negocial.
