### ISSUE TITLE
Alteração de atribuição de acesso ao menu "Tramita GOV.BR"

### ISSUE THREAD

**Issue by yurioliveiramgi** [pengovbr/mod-sei-pen#542]
**Descreva o erro**
Ao executar o script de atualização do SIP, o menu "Tramita GOV.BR" (externo, que é composto pelos menus "Blocos de Trâmite Externo" e "Processos em Tramitação Externa") é atribuído ao perfil _Administrador_, quando na verdade deveria estar atribuído ao perfil _Básico_.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Crie um usuário no SIP
2. Atribua o perfil básico
3. Acesse o SEI com esse usuário
4. O menu Tramita GOV.BR não será exibido

Tela atual para o perfil Básico:
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/49478cff-c2f4-4a29-b05c-67f094bb1dac)
-----

**Comportamento esperado**
É esperado que, para os usuários que possuam atribuição de perfil Básico, a tela exibida seja a seguinte:
![image](https://github.com/pengovbr/mod-sei-pen/assets/145995845/0dc32954-ebc3-4a0f-a5f1-97f1ee880657)

-----

@euviniciusmendonca PSC

**Comment by euviniciusmendonca** [comment]
De acordo.

@mateussbh @amelquia @yurioliveiramgi

**Comment by yurioliveiramgi** [comment]
Em avaliação, ficou constatado que o Menu está atribuído para o perfil básico, conforme esperado. Contudo o botão "Incluir Processo no Bloco de Trâmite" não aparece na tela _Controle de Processos_ (vide evidência)

![image](https://github.com/user-attachments/assets/cfc0e92d-c11e-4aea-82bb-9a39c4f4acf9)


@mateussbh, @amelquia, @marvdias e @euviniciusmendonca, PSC

**Comment by yurioliveiramgi** [comment]
Mais um ponto passivo de alteração observado @marvdias. O referido recurso necessita estar atribuído ao perfil básico.

![image](https://github.com/user-attachments/assets/71d4e2cf-03d6-42ab-8ddf-e571db701149)

**Comment by euviniciusmendonca** [comment]
@yurioliveiramgi, por favor, terminar a avaliação e se de acordo mudar para o status de Aceite Negocial.

**Comment by yurioliveiramgi** [comment]
Issue validada. O que foi desenvolvido atende ao solicitado.
Segue evidência.

![Image](https://github.com/user-attachments/assets/103fabd3-7bc9-46fa-8664-3bfdf901fe01)
