### ISSUE TITLE
Testes automatizados - Versão 3.7.0

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#600]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.  Testes automatizados referentes à nova versão 3.7.0

-----

**Descreva a solução que você gostaria**
Uma descrição clara e concisa do que você deseja que aconteça.

-----

**Descreva alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by amelquia** [comment]
02/09/24
Issue transferida para a sprint 49 para a continuação dos Testes automatizados.

**Comment by NinetiesPaul** [comment]
Nos dias 29 e 30 de agosto (quinta e sexta) estive atuando na resolução de alguns erros identificados pelo Mateus que houveram na execução completa dos testes automatizados do Tramita. Houveram cerca de 8 erros e 5 falhas ao longo de 8 testes para ser estudados. Logo ao começar porém percebi que alguns testes estavam executando sem apresentar ditos erros, sendo os testes:

TramiteProcessoComDevolucaoAnexadoOutroTest
TramiteProcessoContendoDocumentoCanceladoTest
TramiteProcessoRestritoHipotesePadraoTest
TramiteProcessoRestritoTest

Dos testes restantes, o teste MapeamentoDeUnidadesComLimitacaoDeRepositoriosTest que apresentou o erro "Erro cadastrando registro em md_pen_uni_restr" foi resolvido separadamente por uma alteração na estrutura do banco de dados formulada pelo Glaydson.

O teste MapeamentoEnvioParcialTest apresentou o erro "Erro contando registros de md_pen_envio_comp_digitais", o qual ocorre ao se utilizar um campo CLOB na filtragem WHERE de uma query SQL. Após pesquisas na internet e documentação do Oracle constatou-se que de fato o tipo de coluna CLOB não pode ser utilizado nesse contexto de filtragem, seja em operação de SELECT, UPDATE e DELETE. A solução proposta e aplicada foi recriar as colunas str_estrutura e str_unidade_pen da tabela md_pen_envio_comp_digitais do tipo CLOB para colunas tipo VARCHAR.

**Comment by NinetiesPaul** [comment]
A respeito do erro de timeout que pode ser observado no banco oracle no teste _TramiteEnvioParcialTest::test_criar_documento_processo_recebido_tramitar_destinatario_envio_parcial_, após diminuir a janela de tempo para execução dos agendamentos para intervalos de 1 minuto, o erro de timeout não ocorreu mais, tendo executado o teste 3 vezes em sequencia, e retornando sucesso em todas.

![_TramiteEnvioParcialTest oracle 4 0 12 15 1](https://github.com/user-attachments/assets/79ddce03-122b-458d-8c61-206fbc391777)
![_TramiteEnvioParcialTest oracle 4 0 12 15 2](https://github.com/user-attachments/assets/0b8d34d0-70e9-4b94-8849-148fcf0587c8)
![_TramiteEnvioParcialTest oracle 4 0 12 15 3](https://github.com/user-attachments/assets/e0738f0a-120f-4881-bf8c-dc4472734a0b)

**Comment by amelquia** [comment]
01/10/24
Testes automatizados em execução.
