### ISSUE TITLE
Erro no teste:  TramiteBlocoExternoLimiteTest

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#616]
**Descreva o erro**

Verificar erro no teste TramiteBlocoExternoLimiteTest

Erro: 
..............................F................................  63 / 176 ( 35%)
............................................................... 126 / 176 ( 71%)
..................................................              176 / 176 (100%)
 
Time: 3.19 hours, Memory: 54.00 MB
 
There was 1 failure:
 
1) TramiteBlocoExternoLimiteTest::test_verificar_envio_tramite_em_bloco
ERROR: 255
make: *** [Makefile:195: test-functional] Error 255

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]
 - Banco de dados: [MySQL, SQLServer, Oracle ou PostgreSQL]
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by amelquia** [comment]
10/09/24 - Daily
Revisão de Código: Paul dos Anjos

**Comment by NinetiesPaul** [comment]
Revisão de Código finalizada, o código proposto atende o objetivo da tarefa de forma satisfatória

**Comment by sergioadao** [comment]
@amelquia , @mateussbh e @Mauro1706 ....Teste realizado e confirmado o funcionamento correto. Segue evidência:

toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen$ date
qua 11 set 2024 09:21:41 -03
toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen$ make teste=TramiteBlocoExternoLimiteTest test-functional
docker compose -f tests_sei41/funcional/docker-compose.yml --env-file tests_sei41/funcional/.env up -d
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_sei41/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-3409f95d58fc funcional-php-test-functional-run-f570a8345ef2 funcional-php-test-functional-run-67842d8190ab funcional-php-test-functional-run-82c10f392e81 funcional-php-test-functional-run-32b351904e25 funcional-php-test-functional-run-e539721d069b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 11/11
 ✔ Container funcional-org2-database-1        Running                                                                                                                          0.0s 
 ✔ Container funcional-org1-memcached-1       Running                                                                                                                          0.0s 
 ✔ Container funcional-smtp-1                 Running                                                                                                                          0.0s 
 ✔ Container funcional-org2-memcached-1       Running                                                                                                                          0.0s 
 ✔ Container funcional-org2-http-1            Running                                                                                                                          0.0s 
 ✔ Container funcional-php-test-unit-1        Started                                                                                                                          0.8s 
 ✔ Container funcional-org1-database-1        Running                                                                                                                          0.0s 
 ✔ Container funcional-org1-http-1            Running                                                                                                                          0.0s 
 ✔ Container funcional-proxy-1                Running                                                                                                                          0.0s 
 ✔ Container funcional-selenium-1             Running                                                                                                                          0.0s 
 ✔ Container funcional-php-test-functional-1  Started                                                                                                                          0.9s 
docker compose -f tests_sei41/funcional/docker-compose.yml --env-file tests_sei41/funcional/.env run -w /tests php-test-functional bash -c './composer.phar install'
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_sei41/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-3409f95d58fc funcional-php-test-functional-run-f570a8345ef2 funcional-php-test-functional-run-67842d8190ab funcional-php-test-functional-run-82c10f392e81 funcional-php-test-functional-run-32b351904e25 funcional-php-test-functional-run-e539721d069b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-org1-database-1   Running                                                                                                                               0.0s 
 ✔ Container funcional-org1-memcached-1  Running                                                                                                                               0.0s 
 ✔ Container funcional-org2-database-1   Running                                                                                                                               0.0s 
 ✔ Container funcional-smtp-1            Running                                                                                                                               0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                                                                               0.0s 
 ✔ Container funcional-org2-memcached-1  Running                                                                                                                               0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                                                                               0.0s 
 ✔ Container funcional-proxy-1           Running                                                                                                                               0.0s 
 ✔ Container funcional-selenium-1        Running                                                                                                                               0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Generating autoload files
22 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
docker compose -f tests_sei41/funcional/docker-compose.yml --env-file tests_sei41/funcional/.env run --rm php-test-functional /tests/vendor/bin/phpunit -c /tests/phpunit.xml /tests/tests/TramiteBlocoExternoLimiteTest.php ;
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_sei41/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-c73cd40b90f8 funcional-php-test-functional-run-3409f95d58fc funcional-php-test-functional-run-f570a8345ef2 funcional-php-test-functional-run-67842d8190ab funcional-php-test-functional-run-82c10f392e81 funcional-php-test-functional-run-32b351904e25 funcional-php-test-functional-run-e539721d069b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-smtp-1            Running                                                                             0.0s 
 ✔ Container funcional-org2-database-1   Running                                                                             0.0s 
 ✔ Container funcional-org1-memcached-1  Running                                                                             0.0s 
 ✔ Container funcional-org1-database-1   Running                                                                             0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                             0.0s 
 ✔ Container funcional-org2-memcached-1  Running                                                                             0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                             0.0s 
 ✔ Container funcional-proxy-1           Running                                                                             0.0s 
 ✔ Container funcional-selenium-1        Running                                                                             0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(

**PHPUnit 8.5.39 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

...                                                                 3 / 3 (100%)

Time: 6.56 minutes, Memory: 22.00 MB

OK (3 tests, 4 assertions)**
toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen$ date
qua 11 set 2024 09:29:00 -03
