### ISSUE TITLE
Erros MYSQL -  Versão 4.0.12

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#622]
**Descreva o erro**

erro 4.0.12 / mysql
 
Text
....................................EE.....F...................  63 / 176 ( 35%)
............................................................... 126 / 176 ( 71%)
......................ES..........................              176 / 176 (100%)

Time: 4.74 hours, Memory: 54.00 MB

There were 3 errors:

1) TramiteEnvioParcialTest::test_criar_documento_processo_recebido_tramitar_destinatario_envio_parcial
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/CenarioBaseTestCase.php:391
/tests/tests/TramiteEnvioParcialTest.php:135
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Framework\ExpectationFailedException: Failed asserting that 'Erro\n
O trâmite ainda não foi concluído. Acompanhe no Painel de Controle o andamento da tramitação, antes de realizar uma nova tentativa. NRE: 0000043926712024. Processo: 99990.000025/2024-01.' contains "Trâmite externo do processo finalizado com sucesso!".

/tests/tests/CenarioBaseTestCase.php:376
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/CenarioBaseTestCase.php:391
/tests/tests/TramiteEnvioParcialTest.php:135
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

2) TramiteEnvioParcialTest::test_verificar_processo_recebido_tramitar_remetente_envio_parcial
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteEnvioParcialTest.php:164
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"link text","selector":"99990.000025/2024-01"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:96
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/src/paginas/PaginaControleProcesso.php:95
/tests/tests/TramiteEnvioParcialTest.php:162
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteEnvioParcialTest.php:164
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

3) TramiteProcessoTamanhoAcimaLimiteDestinoTest::test_verificar_origem_processo_tamanho_acima_limite_destino
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteProcessoTamanhoAcimaLimiteDestinoTest.php:100
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Framework\ExpectationFailedException: Failed asserting that 'Processo não possui andamentos abertos.' contains "Processo aberto somente na unidade".

/tests/tests/TramiteProcessoTamanhoAcimaLimiteDestinoTest.php:96
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteProcessoTamanhoAcimaLimiteDestinoTest.php:100
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

--

There was 1 failure:

1) TramiteProcessoAnexadoComDevolucaoTest::test_verificar_devolucao_destino_processo_anexado
Failed asserting that 'arquivo_pequeno_A.pdf' contains "arquivo_pequeno.txt".

/tests/tests/CenarioBaseTestCase.php:548
/tests/tests/TramiteProcessoAnexadoComDevolucaoTest.php:386
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

--

There was 1 skipped test:

1) TramiteProcessoTamanhoAcimaLimiteDestinoTest::test_verificar_destino_processo_tamanho_acima_limite_destino
This test depends on "TramiteProcessoTamanhoAcimaLimiteDestinoTest::test_verificar_origem_processo_tamanho_acima_limite_destino" to pass.

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 176, Assertions: 2761, Errors: 3, Failures: 1, Skipped: 1.
make: *** [Makefile:195: test-functional] Error 2

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]
 - Banco de dados: [MySQL, SQLServer, Oracle ou PostgreSQL]
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by marvdias** [comment]
![image](https://github.com/user-attachments/assets/37417b9a-4c2f-4caf-aa84-e08e85b37289)
TramiteEnvioParcialTest
![image](https://github.com/user-attachments/assets/f14353c3-c6df-4615-a9e8-ed5c320f687f)
TramiteProcessoAnexadoComDevolucaoTest
![image](https://github.com/user-attachments/assets/ecfb91ff-0bb3-4997-ac08-32b3d8e3b691)
TramiteProcessoTamanhoAcimaLimiteDestinoTest

Os testes foram executados individualmente e não apresentaram erros.

**Comment by sergioadao** [comment]
Boa tarde @marvdias, @amelquia e @mateussbh, foi executado localmente o teste:

make teste=TramiteEnvioParcialTest test-functional


E retornou a mensagem abaixo:

**Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

.
.EE                                                                4 / 4 (100%)

Time: 14.58 minutes, Memory: 28.00 MB

There were 2 errors:

1) TramiteEnvioParcialTest::test_criar_documento_processo_recebido_tramitar_destinatario_envio_parcial
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/CenarioBaseTestCase.php:397
/tests/tests/TramiteEnvioParcialTest.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Framework\ExpectationFailedException: Failed asserting that 'Erro\n
O trâmite ainda não foi concluído. Acompanhe no Painel de Controle o andamento da tramitação, antes de realizar uma nova tentativa. NRE: 0000044953692024. Processo: 99990.000001/2024-00.' contains "Trâmite externo do processo finalizado com sucesso!".

/tests/tests/CenarioBaseTestCase.php:382
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/CenarioBaseTestCase.php:397
/tests/tests/TramiteEnvioParcialTest.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

2) TramiteEnvioParcialTest::test_verificar_processo_recebido_tramitar_remetente_envio_parcial
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteEnvioParcialTest.php:170
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"link text","selector":"99990.000001/2024-00"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.15.0-119-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:96
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/src/paginas/PaginaControleProcesso.php:95
/tests/tests/TramiteEnvioParcialTest.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteEnvioParcialTest.php:170
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 4, Assertions: 538, Errors: 2.
make: *** [Makefile:195: test-functional] Erro 2**

A título de informação, verificou-se a criação de um segundo mapeamento de unidade. Segue:

Antes do teste:
![image](https://github.com/user-attachments/assets/4017104f-4038-4bde-a8ac-102c67a7dd43)

![image](https://github.com/user-attachments/assets/42225f8c-967b-4ec3-bb65-c51602ed8c82)

Depois do teste:

![image](https://github.com/user-attachments/assets/ea9ec014-8a96-4219-b162-98b584863336)

![image](https://github.com/user-attachments/assets/245cf9ab-7c1c-4e43-aa8b-8426a76365d5)


**OBS: Não é possível confirmar se este mapeamento contribui para o erro. Mas, fica como observação.**

**Comment by sergioadao** [comment]
Bom dia @amelquia, @marvdias e @mateussbh....testes realizados e funcionarm ok.....

****Ambiente: SEI 4.0.12.15 / MySql
OBS 1: O ambiente não deve estar configurado toda a configuração deve vir do arquivo phpunit.xml (unidade principal e secundária).**
OBS 2: Os testes foram executado em sequência, sem reconstrução do ambiente SEI e MOD-SEI-PEN.**

**teste=TramiteEnvioParcialTest**

toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen$ make teste=TramiteEnvioParcialTest test-functional
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env up -d
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-e13feb978c1e funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 11/11
 ✔ Container funcional-php-test-unit-1        Started                                                                                                        0.6s 
 ✔ Container funcional-org1-memcached-1       Running                                                                                                        0.0s 
 ✔ Container funcional-smtp-1                 Running                                                                                                        0.0s 
 ✔ Container funcional-org2-memcached-1       Running                                                                                                        0.0s 
 ✔ Container funcional-org1-database-1        Running                                                                                                        0.0s 
 ✔ Container funcional-org1-http-1            Running                                                                                                        0.0s 
 ✔ Container funcional-org2-database-1        Running                                                                                                        0.0s 
 ✔ Container funcional-org2-http-1            Running                                                                                                        0.0s 
 ✔ Container funcional-proxy-1                Running                                                                                                        0.0s 
 ✔ Container funcional-selenium-1             Running                                                                                                        0.0s 
 ✔ Container funcional-php-test-functional-1  Started                                                                                                        0.7s 
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run -w /tests php-test-functional bash -c './composer.phar install'
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-e13feb978c1e funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-smtp-1            Running                                                                                                             0.0s 
 ✔ Container funcional-org1-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org1-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-org2-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-org2-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-proxy-1           Running                                                                                                             0.0s 
 ✔ Container funcional-selenium-1        Running                                                                                                             0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Generating autoload files
27 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run --rm php-test-functional /tests/vendor/bin/phpunit -c /tests/phpunit.xml /tests/tests/TramiteEnvioParcialTest.php ;
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-8f5e7d6a5ef2 funcional-php-test-functional-run-e13feb978c1e funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-smtp-1            Running                                                                                                             0.0s 
 ✔ Container funcional-org2-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org2-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-org1-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org1-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-proxy-1           Running                                                                                                             0.0s 
 ✔ Container funcional-selenium-1        Running                                                                                                             0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHPUnit 8.5.38 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

.
...                                                                4 / 4 (100%)

Time: 6.88 minutes, Memory: 20.00 MB

OK (4 tests, 53 assertions)

===========================================================================
**teste=TramiteProcessoAnexadoComDevolucaoTest** 

toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen$ make teste=TramiteProcessoAnexadoComDevolucaoTest test-functional
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env up -d
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-8f5e7d6a5ef2 funcional-php-test-functional-run-e13feb978c1e funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 11/11
 ✔ Container funcional-org1-database-1        Running                                                                                                        0.0s 
 ✔ Container funcional-org2-memcached-1       Running                                                                                                        0.0s 
 ✔ Container funcional-org1-memcached-1       Running                                                                                                        0.0s 
 ✔ Container funcional-smtp-1                 Running                                                                                                        0.0s 
 ✔ Container funcional-org1-http-1            Running                                                                                                        0.0s 
 ✔ Container funcional-php-test-unit-1        Started                                                                                                        0.7s 
 ✔ Container funcional-org2-database-1        Running                                                                                                        0.0s 
 ✔ Container funcional-org2-http-1            Running                                                                                                        0.0s 
 ✔ Container funcional-proxy-1                Running                                                                                                        0.0s 
 ✔ Container funcional-selenium-1             Running                                                                                                        0.0s 
 ✔ Container funcional-php-test-functional-1  Started                                                                                                        0.7s 
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run -w /tests php-test-functional bash -c './composer.phar install'
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-8f5e7d6a5ef2 funcional-php-test-functional-run-e13feb978c1e funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-org2-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org2-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-smtp-1            Running                                                                                                             0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-org1-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-org1-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-proxy-1           Running                                                                                                             0.0s 
 ✔ Container funcional-selenium-1        Running                                                                                                             0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Generating autoload files
27 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run --rm php-test-functional /tests/vendor/bin/phpunit -c /tests/phpunit.xml /tests/tests/TramiteProcessoAnexadoComDevolucaoTest.php ;
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-c4f0b61541db funcional-php-test-functional-run-8f5e7d6a5ef2 funcional-php-test-functional-run-e13feb978c1e funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-org1-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org2-memcached-1  Running                                                                                                             0.0s 
 ✔ Container funcional-org1-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-smtp-1            Running                                                                                                             0.0s 
 ✔ Container funcional-org2-database-1   Running                                                                                                             0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                                                             0.0s 
 ✔ Container funcional-proxy-1           Running                                                                                                             0.0s 
 ✔ Container funcional-selenium-1        Running                                                                                                             0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHPUnit 8.5.38 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

.
.....                                                              6 / 6 (100%)

Time: 11.35 minutes, Memory: 24.00 MB

OK (6 tests, 110 assertions)
