### ISSUE TITLE
Erro - Teste SEI - Versão  4.1.1  - MYSQL

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#623]
**Descreva o erro**

teste=TramiteEnvioParcialTest

Mensagem de erro:
O trÃ¢mite ainda nÃ£o foi concluÃ­do. Acompanhe no Painel de Controle o andamento da tramitaÃ§Ã£o, antes de realizar uma nova tentativa. NRE: 0000044253152024. Processo: 99990.000177/2024-01.

....................................EE.........................  63 / 176 ( 35%)
............................................................... 126 / 176 ( 71%)
..................................................              176 / 176 (100%)

Time: 5 hours, Memory: 54.00 MB

There were 2 errors:

1) TramiteEnvioParcialTest::test_criar_documento_processo_recebido_tramitar_destinatario_envio_parcial
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/CenarioBaseTestCase.php:391
/tests/tests/TramiteEnvioParcialTest.php:135
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Framework\ExpectationFailedException: Failed asserting that 'Erro\n
O trâmite ainda não foi concluído. Acompanhe no Painel de Controle o andamento da tramitação, antes de realizar uma nova tentativa. NRE: 0000044106502024. Processo: 99990.000023/2024-01.' contains "Trâmite externo do processo finalizado com sucesso!".

/tests/tests/CenarioBaseTestCase.php:375
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/CenarioBaseTestCase.php:391
/tests/tests/TramiteEnvioParcialTest.php:135
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

2) TramiteEnvioParcialTest::test_verificar_processo_recebido_tramitar_remetente_envio_parcial
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteEnvioParcialTest.php:164
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"link text","selector":"99990.000023/2024-01"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:96
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/src/paginas/PaginaControleProcesso.php:95
/tests/tests/TramiteEnvioParcialTest.php:162
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteEnvioParcialTest.php:164
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 176, Assertions: 2725, Errors: 2.
make: *** [Makefile:195: test-functional] Error 2

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]
 - Banco de dados: [MySQL, SQLServer, Oracle ou PostgreSQL]
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by sergioadao** [comment]
Bom dia @amelquia , @marvdias e @mateussbh ...testes realizado localmente....funcionou ok.

Ambiente: SEI 4.0.12.15 / MySql
OBS: Ambiente instalado e sem configuração. Configuração proveniente do arquivo phpunit.xml.

Segue evidência:toor@tesla:~/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen$ make teste=TramiteEnvioParcialTest test-functional
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env up -d
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 11/11
 ✔ Container funcional-org2-database-1        Running                                                                               0.0s 
 ✔ Container funcional-org1-memcached-1       Running                                                                               0.0s 
 ✔ Container funcional-org2-memcached-1       Running                                                                               0.0s 
 ✔ Container funcional-php-test-unit-1        Started                                                                               1.0s 
 ✔ Container funcional-org1-database-1        Running                                                                               0.0s 
 ✔ Container funcional-smtp-1                 Running                                                                               0.0s 
 ✔ Container funcional-org1-http-1            Running                                                                               0.0s 
 ✔ Container funcional-org2-http-1            Running                                                                               0.0s 
 ✔ Container funcional-proxy-1                Running                                                                               0.0s 
 ✔ Container funcional-selenium-1             Running                                                                               0.0s 
 ✔ Container funcional-php-test-functional-1  Started                                                                               0.9s 
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run -w /tests php-test-functional bash -c './composer.phar install'
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-org2-database-1   Running                                                                                    0.0s 
 ✔ Container funcional-smtp-1            Running                                                                                    0.0s 
 ✔ Container funcional-org2-memcached-1  Running                                                                                    0.0s 
 ✔ Container funcional-org1-database-1   Running                                                                                    0.0s 
 ✔ Container funcional-org1-memcached-1  Running                                                                                    0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                                    0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                                    0.0s 
 ✔ Container funcional-proxy-1           Running                                                                                    0.0s 
 ✔ Container funcional-selenium-1        Running                                                                                    0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Generating autoload files
27 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
docker compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env run --rm php-test-functional /tests/vendor/bin/phpunit -c /tests/phpunit.xml /tests/tests/TramiteEnvioParcialTest.php ;
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([funcional-php-test-functional-run-e13feb978c1e funcional-php-test-functional-run-d696bf796a3a funcional-php-test-functional-run-36d71d1f245b]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 9/0
 ✔ Container funcional-org1-database-1   Running                                                                                    0.0s 
 ✔ Container funcional-smtp-1            Running                                                                                    0.0s 
 ✔ Container funcional-org1-memcached-1  Running                                                                                    0.0s 
 ✔ Container funcional-org1-http-1       Running                                                                                    0.0s 
 ✔ Container funcional-org2-memcached-1  Running                                                                                    0.0s 
 ✔ Container funcional-org2-database-1   Running                                                                                    0.0s 
 ✔ Container funcional-org2-http-1       Running                                                                                    0.0s 
 ✔ Container funcional-proxy-1           Running                                                                                    0.0s 
 ✔ Container funcional-selenium-1        Running                                                                                    0.0s 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHPUnit 8.5.38 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

.
...                                                                4 / 4 (100%)

Time: 7.29 minutes, Memory: 20.00 MB

OK (4 tests, 46 assertions)
