### ISSUE TITLE
Incluir validações para processo incluído em bloco único.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#629]
**Descreva o erro**

Novas regras pactuadas na presente data:

* No momento da migração vai remover processos que estão com situação diferente de concluído (Aguardando processamento(1,2,3,4,5 ou 8), Aberto, Recusado(9) e Cancelado (7 ou 10), que são de outras unidades, do bloco da unidade atual.
* Não permitir INCLUIR um processo em mais de um bloco, independente da unidade, com exceção se o processo estiver com tramite concluído (entende-se por trâmite concluído todo trâmite com status 6,7 9 ou 10) em outros blocos das outras unidades.
**6**:Concluído (recibo já recebido pelo remetente)
**7**:Cancelado
**9**:Recusado
**10**:Cancelado Automaticamente
* Não permitir TRAMITAR um processo que esteja dentro de outro bloco,  com exceção se o processo estiver com tramite concluído nestes outros blocos.
  - Exibição de mensagem de crítica, informando que o bloco possui processo inserido em mais de um bloco:
"Prezado(a) usuário, o processo [Nº do processo], também está inserido no(s) bloco(s) [Nº do bloco adicional ], [Nº do bloco adicional], etc. Para continuar com esta ação remova o processo do(s) bloco(s) mencionados."

Os BLOCOS possuirão apenas três ESTADOS :

**Aberto**: Quando o trâmite não for iniciado;

**Aguardando Processamento**: Pelo menos um dos processos com status 1, 2, 3, 4, 5 e 8;

**Concluído**: Todos os processos do bloco com status 6, 7, 9 ou 10.

Para os status 7 ou 10, a regra de alteração do estado do bloco permanece como está.

-----

**Comment by yurioliveiramgi** [comment]
PSC @Mauro1706 , @amelquia , @mateussbh , @euviniciusmendonca .

**Ponto para correção:**
1. Atualmente caso um bloco criado na Unidade 2, seja incluído em um Bloco criado na mesma unidade, e na sequência, enviado para a Unidade 1. O processo exibirá o ícone de "Incluir Processo em Bloco de Trâmite" e "Trâmite de Processo Externo".
* Ao tentar inserir o processo em um bloco criado na Unidade 1, a mensagem de impedimento é exibida (Comportamento correto)
* Ao tentar tramitar o processo individualmente, esse segue o fluxo normal sem nenhum impedimento, ainda que inserido no bloco da Unidade 2.

**Solução:** 
* Ao inserir o processo em um bloco, em qualquer unidade, a regra de exibição dos botões "Incluir Processo em Bloco de Trâmite" e "Trâmite de Processo Externo" deve ser aplicada, independentemente de onde o processo se encontre aberto. Exibindo apenas o botão "Remover Processo de Bloco de Trâmite Externo".
* Ao tentar excluir o processo do bloco, deve ser feita a verificação se o bloco pertence à unidade ou não.
* Caso o bloco pertença à unidade que está solicitando a exclusão, o processo deve ser removido do bloco (mediante confirmação de ação);
* Caso o bloco não pertença à unidade que está solicitando a exclusão, uma mensagem de crítica deve ser exibida em tela informando da impossibilidade de continuidade da ação.
"Prezado(a) usuário(a), o processo [Nº do Processo] atualmente encontra-se inserido no bloco - [Nº + Nome do Bloco] da Unidade [Sigla da unidade]. A remoção do processo do bloco mencionado não pode ser executada a partir da unidade atual."

Tela do Controle de Processos da Unidade 2:
![image](https://github.com/user-attachments/assets/ee3a14f6-c938-44bc-b39f-c4220f05f1d6)
Bloco 1 da unidade 2
![image](https://github.com/user-attachments/assets/4a693ab3-0248-4290-b2cd-394d7d515acd)
Processo bloqueado (tramitado com sucesso):
![image](https://github.com/user-attachments/assets/3b749fdd-f809-4aeb-9009-72d71dde0166)
Histórico do Processo:
![image](https://github.com/user-attachments/assets/8969f643-eb13-4191-a4a6-849ad3cde194)

**Comment by amelquia** [comment]
23/09/24 
Issue movida para Sprint 50 para Validação técnica.

**Comment by sergioadao** [comment]
Bom dia @amelquia , @Mauro1706 , @yurioliveiramgi e @mateussbh ....testes realizados...funcionamento de acordo com o solicitado.

Ambiente: SEI 4.1.1 e MySql

Seguem evidencias:


https://github.com/user-attachments/assets/730d11c1-1e4a-4112-92d0-cbef8140e7a6


https://github.com/user-attachments/assets/191aeb67-366e-4033-ba8f-f834170e5804

**Comment by amelquia** [comment]
30/09/24
Voltou para validação técnica para repetir os testes já realizados, a fim de termos mais segurança e assertividade quanto às alterações realizadas.

**Comment by Mauro1706** [comment]
02/10/2024
Validado fluxo relatado com erro de exclusão de processos de bloco e identificado um bug durante a migração. 
Foi necessário mudança no fluxo de migração e atualização de andamentos de processos que vem de versões anteriores a 3.7.0
Aguardando validação do @yurioliveiramgi para a implementação da proposta abordada.

**Comment by yurioliveiramgi** [comment]
Para fins de registro, em reunião realizada no dia 03/10 ficou definido que os blocos criados nas versões 3.6.1 ou 3.6.2 do Módulo não serão recuperados após a atualização para a versão 3.7.0.
Essa decisão tem por base os seguintes pontos:
1. Alteração significativa na lógica de funcionamento dos Blocos de Trâmite Externo, como por exemplo forma de consulta às tabelas do BD, atribuição de Situação ao trâmite dentro do Bloco, etc;
2. Alteração dos Estados dos Blocos de Trâmite Externo, antes representados por quatro classificações distintas, na 3.7.0 passam a ser representados por apenas três classificações (Aberto, Aguardando Processamento, Concluído);
3. Todas as informações relevantes aos trâmites ficam registradas no histórico do processo, não havendo assim nenhuma prejuízo arquivístico;

Dessa forma, as regras negociais referentes à versão 3.7.0 ficam mantidas, removendo qualquer registro da funcionalidade Blocos de Trâmite Externo, de versões anteriores.

Para conferência, validação e complementação.

@mateussbh , @higodf , @amelquia , @euviniciusmendonca e @Mauro1706

**Comment by mateussbh** [comment]
Conforme alinhamento entre as áreas, foi atualizada a regra de migração, de modo que não haverá a movimentação de blocos criados na release 3.6.2 para a 3.7.0. O registro deste alinhamento pode ser observado na issue #629, com maiores detalhes.

**Comment by yurioliveiramgi** [comment]
Em testes realizados de forma individual e em conjunto com a CGSI, ficou evidenciado que todas as regras  e comportamentos definidos nesta issue foram atendidos, de forma que a issue está apta a ser concluída.
