### ISSUE TITLE
Criar teste funcional com trâmite cancelado.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#632]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Não.

-----

**Descreva a solução que você gostaria**
Criar teste funcional com trâmite cancelado.

-----

**Etapas para elaboração do teste**

- [ ] Criar 2 blocos.
- [ ] Incluir 3 processo no bloco 1 (Configurar um processo para recusar).
- [ ] Enviar para o órgão 2.
- [ ] Verificar se foram todos tramitados.
- [ ] Verificar se um foi recusado.
- [ ] Verificar se o bloco está como concluído.
- [ ] Incluir o mesmo processo no bloco 2.
- [ ] Verificar se foi incluído com sucesso.

**Comment by amelquia** [comment]
02/10/24
Issue **temporariamente suspensa** para dar prioridade na isse dos testes de Fluxo de Migração e Fluxo de criação e envio de bloco.

**Comment by amelquia** [comment]
09/10/24
Issue  #663  Fluxo de Migração e Fluxo de criação e envio de bloco já atendida, portanto, a issue #632 voltará para o backlog da sprint para tratativas.

**Comment by Mauro1706** [comment]
Realizado a implementação dos tester nos PR:
ModTramitaGovBR -> https://github.com/pengovbr/mod-sei-pen/pull/680
SEI ->https://github.com/pengovbr/sei/pull/389

Foi realizado uma implementação da fixture TipoProcedimentoFixture.php para realizar a inclusão de um tipo de processo que tera recusa no tramita.

Segue evidências dos testes:
[TramiteBlocoExternoComProcessoNaoMapeadoRecusaTest.zip](https://github.com/user-attachments/files/17346985/TramiteBlocoExternoComProcessoNaoMapeadoRecusaTest.zip)

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para revisão de código.

**Comment by marvdias** [comment]
Revisão de código:
O código executa o teste que foi proposto na issue sem apresentar erros.
