### ISSUE TITLE
Correção do cenário:  não remover a unidade de origem / dona do processo após a migração entre os processos.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#635]
**Descreva o erro**
Cenário:
Quando cria-se o processo no org2 e é enviado para o org1, é alterada a unidade de origem e, após a migração é removido, mesmo sendo a unidade a dona do processo.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1.Criar processo no órgão 2
2. Enviar o processo para o órgão 1

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Informações adicionais**

if (atividade32 != null && atividade32->getNumIdUnidade() != $bloco->getNumIdUnidade())
      excluir
elseif ($bloco->getNumUnidade() != atividade->getNumIdUnidadeGeradoraProcesso())
   excluir!

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by mateussbh** [comment]
Concluindo a issue, tendo em vista que houve uma alteração de regra, de modo que no momento da migração para a versão 3.7.0, a solução passa a não levar nenhum bloco criado nas versões anteriores. A issue tornou-se obsoleta.
