### ISSUE TITLE
Criar teste funcional para botões em bloco.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#643]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

- [x] Botão "Incluir Processo em Bloco" exibido apenas para unidade mapeada e com bloco com Estado "aberto"
- [x] Botões "Envio Externo de Processo"
- [x] Botão "Incluir Processo em Bloco" substituído pelo botão "Remover Processo de Bloco" ao inserir processo em bloco.
 
-----

Definição de Feito (D.O.D. - Definition of Done)

- [x] Evidências dos testes realizados.

**Comment by NinetiesPaul** [comment]
Evidências de execução dos testes

![643 TramiteProcessoValidacaoBotaoIncluirTest](https://github.com/user-attachments/assets/e5543f4b-a1ce-452f-9be6-d2b4af0577c6)
![643 TramiteProcessoValidacaoBotoesAposIncluirTest](https://github.com/user-attachments/assets/92a0c571-81e5-4971-8546-7f01a29dad49)

**Comment by marvdias** [comment]
Revisão de Código:
Os testes executam com sucesso nas 3 versões do SEI (sei4,sei41,sei oficial). Unica sugestão pro código enviado é a utilização da função mb_convert_encoding ao invés de utf8_encode.

**Comment by NinetiesPaul** [comment]
Feito as alterações do código seguindo a sugestão do @marvdias

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Validação técnica.
