### ISSUE TITLE
Criar teste funcional para Processo já incluído em bloco.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#645]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

- [x] Processo já incluído em bloco não pode ser incluído em outro bloco.
- [x] Processo incluído em bloco não pode ser incluído em blocos de outra unidade.

 -----

Definição de Feito (D.O.D. - Definition of Done)

- [x] Evidências dos testes realizados.

**Comment by mrglaydson** [comment]
![Image](https://github.com/user-attachments/assets/c88d158d-248b-46af-baf4-5e56aedfa832)

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Validação técnica.
