### ISSUE TITLE
Criar teste funcional: Processos que não podem ser incluídos. 

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#646]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

 - [x] Processo com andamento aberto em mais de uma unidade não pode ser incluído em bloco.
 - [x] Processo com documento interno sem assinatura não pode ser incluído em bloco.
 - [x] Processo bloqueado não pode ser incluído em bloco.
 - [x] Processo sem documentos não pode ser incluído em bloco.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

 - [x] Evidências dos testes realizados.

**Comment by NinetiesPaul** [comment]
Evidencia da execução do teste

![646 TramiteProcessoBlocoDeTramiteRegrasTest](https://github.com/user-attachments/assets/eebd8cf2-4ab7-45ef-88ae-c91dd0883956)

**Comment by amelquia** [comment]
03/10
Issue voltou para o status "em andamento" para contemplarmos mais um novo teste (Processo sem documentos não pode ser incluído em bloco.)  que estava apartado em outra issue.

**Comment by marvdias** [comment]
Revisão de código:
- Adicionar ```parent::setUpBeforeClass();``` no método ```setUpBeforeClass()```, para que seja feito o mapeamento das unidades e o teste não dê erro;
- Utilizar ```mb_convert_encoding``` ao invés de ```utf8_encode```;
- Fazer algo parecido com o método ```cadastrarDocumentoInternoFixture``` com o que foi feito no ```tramitarProcessoInternamente```, colocando uma flag para sinalizar se vai ser assinado ou não, com o default ser true (assinado sempre);
- Com o acima feito, remover o use das fixtures do SEI;
- E trocar o bloco da linha 40 - 55 por ```$this->cadastrarDocumentoInternoFixture($documentoTeste, $objProtocoloDTO->getDblIdProtocolo(), false);```

**Comment by amelquia** [comment]
@NinetiesPaul 
Estou transferindo essa issue para Ajustes Necessários, para as devidas correções acima.

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Ajustes necessários.
