### ISSUE TITLE
Criar teste funcional: Processos sem dados.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#647]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

- [x] Processo sem "descrição" não pode ser incluído em bloco.
- [x]  Processo sem interessado não pode ser incluído em bloco.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

**Comment by NinetiesPaul** [comment]
Evidência da execução do teste

![647 TramiteProcessoSemDadosBlocoDeTramiteTest](https://github.com/user-attachments/assets/f6b0d9d2-922c-4652-9d10-6b410eb2305d)

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Ajustes necessários.

**Comment by NinetiesPaul** [comment]
PR atualizado com sugestões de alterações propostas pelo @Mauro1706, utilizando Fixtures pra alteraçao/exclusão ao invés de chamar diretamente via query SQL

Tambem foi aberto um PR no SEI para adicionar códigos nas fixtures para suportar essas operações

https://github.com/pengovbr/sei/pull/390

**Comment by Mauro1706** [comment]
Foi analisado e não tenho mais sugestões para implementação dessa tarefa de implementação de testes.
