### ISSUE TITLE
 Corrigir erro ao tentar incluir processos em bloco.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#648]
**Descreva o erro**

Ao clicar em visualização detalha em controle de processos, e tentar incluir no bloco gerar os erros anexados

![Screenshot from 2024-09-24 15-37-25](https://github.com/user-attachments/assets/b7457fbb-bb9f-4662-bf59-8b29d7fc2d8d)
![imagem (4)](https://github.com/user-attachments/assets/44b8db3e-a198-49ec-9eb2-b47b4a60be41)

-----

**Para reproduzir**
Passos para reproduzir o comportamento:

-Criar processos
-Selecionar controle de processos
-Selecionar o menu Visualização detalhada
-Selecionar processo para incluir no bloco
-Selecionar o icone "Incluir Processos no Bloco de Tramite.

-----

**Comportamento esperado**
Conseguir incluir processos em bloco.

-----

**Screenshots**
![Screenshot from 2024-09-24 15-37-25](https://github.com/user-attachments/assets/b7457fbb-bb9f-4662-bf59-8b29d7fc2d8d)
![imagem (4)](https://github.com/user-attachments/assets/44b8db3e-a198-49ec-9eb2-b47b4a60be41)

-----

**Comment by amelquia** [comment]
Devido a issue 350 ter sido criada em repositório errado (tramitagovbr) e, da não possibilidade de transferência da issue 350 entre repositórios, foi necessária a criação dessa nova issue 648 (repositório correto: mod-sei-pen), a fim de substituir a issue 350.

**Comment by amelquia** [comment]
Seguem as validações do @sergioadao  que foram registradas na issue 350:

@[sergioadao](https://github.com/sergioadao)
sergioadao
[3 hours ago](https://github.com/pengovbr/tramitagovbr/issues/350#issuecomment-2379358576)
Bom dia @amelquia, @Mauro1706 e @mateussbh ...... relaizado teste abaixo:

-Criar processos
-Selecionar controle de processos
-Selecionar o menu Visualização detalhada
-Selecionar processo para incluir no bloco
-Selecionar o icone "Incluir Processos no Bloco de Tramite.

Funcionou conforme solicitado. Segue evidência:

**Comment by sergioadao** [comment]
Boa tarde @amelquia , @mateussbh e @Mauro1706 ....issue testada e confirmado o funcionamento correto.

Ambiente: SEI 4.1.1 e MySql.

Segue evidência:

https://github.com/user-attachments/assets/7dccc7ca-aff6-4ac3-ad5f-1db41d1cbebd

**Comment by yurioliveiramgi** [comment]
Em testes realizados de forma individual e em conjunto com a CGSI, ficou evidenciado que o comportamento foi corrigido, de forma que a issue está apta a ser concluída.
