### ISSUE TITLE
Criar testes funcionais para Processos com diferentes situações e um ou mais blocos.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#653]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

- [x] Processos com situação "recusado", em um bloco ou mais blocos, podem ser incluídos em novos blocos.
- [x] Processos  com situação "cancelado", em um bloco ou mais blocos, podem ser incluídos em novos blocos.
- [x] Processos  com situação "concluído", em um bloco ou mais blocos,  podem ser incluídos em novos blocos.
- [x] Processos  com situação "aguardando processamento", em um bloco ou mais blocos, não podem ser incluídos em novos blocos.
- [x] Processos  com situação "aberto", em um bloco ou mais blocos, não podem ser incluídos em novos blocos.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

**Comment by mrglaydson** [comment]
PR dessa issue: https://github.com/pengovbr/mod-sei-pen/pull/681

**Comment by mrglaydson** [comment]
![Image](https://github.com/user-attachments/assets/ed621430-25f8-4afc-bc22-6664e89065c6)

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para revisão de código.

**Comment by NinetiesPaul** [comment]
Após revisão do código e execução satisfatatória dos testes, não possuo sugestões de melhorias e aprovo essa tarefa para validação técnica.
