### ISSUE TITLE
Criar teste funcional: Inclusão de processos via tela "visualização detalhada" .

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#654]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**
Criar teste funcional para:

- [x] Inclusão de processos via tela "visualização detalhada" deve funcionar de forma adequada, conforme a mesma funcionalidade do  btn de controle de processos.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

-----

*

**Comment by Mauro1706** [comment]
Realizado implementação no PR: https://github.com/pengovbr/mod-sei-pen/pull/673
Segue evidências de testes
[TramiteBlocoExternoInclusaoDeProcessoPorVisualizacaoDetalhadaTest.zip](https://github.com/user-attachments/files/17297933/TramiteBlocoExternoInclusaoDeProcessoPorVisualizacaoDetalhadaTest.zip)

**Comment by NinetiesPaul** [comment]
Após estudo do código e execução do testes finalizo minh análise sem sugestões de alterações, o teste atende o cenário proposto

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Validação técnica.
