### ISSUE TITLE
Criar testes funcionais para:  Blocos, processos (aberto e em andamento) e unidades x Trâmites.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#655]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

- [x] Bloco com processo **aberto** em mais de uma unidade não pode ser tramitado.
- [x] Bloco com processo **sem andamento** aberto na unidade não pode ser tramitado.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by NinetiesPaul** [comment]
Evidência de execução dos testes

![655 ProcessoBlocoDeTramiteTravasDeTramitacaoTest](https://github.com/user-attachments/assets/3b98112c-6b1f-4193-a330-ac2f23c62315)
