### ISSUE TITLE
Criar testes funcionais: Processos incluídos em blocos x Unidades.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#656]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

- [x] Processo incluído em bloco pode receber documentos de outras unidades.
- [x] Processo incluído em bloco pode ter documentos assinados por usuários de qualquer unidade.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

**Comment by NinetiesPaul** [comment]
Após estudo do código e execução do testes finalizo minha análise sem sugestões de alterações, o teste atende o cenário proposto

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Validação técnica.
