### ISSUE TITLE
Criar testes funcionais: Blocos tramitados (processos excluídos), blocos não tramitados  X  permissões e status.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#657]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar testes funcionais para:

- [x] Blocos tramitados não podem ser mais alterados (processos excluídos).
- [x] Blocos não tramitados devem possuir  estado "Aberto".

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by marvdias** [comment]
![Image](https://github.com/user-attachments/assets/486586e5-d818-4ae6-b180-f93ec71ff821)
Bloco com processos nos estados: concluído, recusado e cancelado
![Image](https://github.com/user-attachments/assets/3c976cbb-57f2-445e-a8c8-ce711feb4c91)
Teste executado no SEI41
![Image](https://github.com/user-attachments/assets/5063c7a6-6aa3-4656-9ccf-80fb030cca44)
Teste executado no SEI Oficial
![Image](https://github.com/user-attachments/assets/d0030d6a-91a5-440b-b523-020137f59d6e)
Teste executado no SEI4

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para revisão de código.
