### ISSUE TITLE
Criar teste funcional:  Trâmite - Status "Conclusão" (6,7,9 e 10).

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#658]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar teste funcional para:

- [x] Status 6, 7, 9 e 10 configuram a "conclusão" do trâmite. Logo, blocos que possuem somente processos com esses status, devem possuir estado **"Concluído"**.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

**Comment by NinetiesPaul** [comment]
Evidencia de execução do teste

![658 TramiteBlocoDeTramiteSituacaoProcessoConcluidoTest](https://github.com/user-attachments/assets/d25a1577-2dcc-4f53-9812-07d2a2d1563b)

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para revisão de código.

**Comment by Mauro1706** [comment]
Foi analisado e não tenho sugestões para implementação dessa tarefa de testes.

**Comment by NinetiesPaul** [comment]
Alterações finalizadas, PR foi atualizado
