### ISSUE TITLE
Criar teste funcional: Trâmite - Status "Andamento" (1,2,3,4,5 e 8).

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#659]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Criar teste funcional para:

- [x] Status 1, 2, 3, 4, 5 e 8 configuram "andamento" do trâmite. Logo, blocos que possuem pelo menos um processo com esse status deve possuir  estado **"Aguardando Processamento".**

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

**Comment by NinetiesPaul** [comment]
Evidência da execução do teste criado

![659 TramiteBlocoDeTramiteSituacaoProcessoTest](https://github.com/user-attachments/assets/1dcafe2e-4aef-4cd6-bc0e-af0aa7a06f79)

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Ajustes necessários.

**Comment by NinetiesPaul** [comment]
Adicionado melhorias propostas pelo @mrglaydson
