### ISSUE TITLE
Criar teste funcional: Processo com documento que possui restrição baseada em Hipótese Legal não mapeada para envio não pode ser inserido em bloco.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#661]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**
Criar teste funcional para:

- [x] Processo com documento que possui restrição baseada em Hipótese Legal não mapeada para envio, não pode ser inserido em 
       bloco.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

**Comment by Mauro1706** [comment]
Realizado a implementação dos tester nos PR: 
ModTramitaGovBR -> https://github.com/pengovbr/mod-sei-pen/pull/677
SEI -> https://github.com/pengovbr/sei/pull/388

Foi realizado uma correção na fixture DocumentoFixture.php para realizar a inclusão quando necessário para documento restrito 

Segue evidências dos testes:
[TramiteBlocoExternoInclusaoDeProcessoEmBlocoComHipoteseLegalNaoMapeadaTest.zip](https://github.com/user-attachments/files/17328583/TramiteBlocoExternoInclusaoDeProcessoEmBlocoComHipoteseLegalNaoMapeadaTest.zip)

**Comment by NinetiesPaul** [comment]
Após estudo do código e execução do testes finalizo minha análise sem sugestões de alterações, o teste atende o cenário proposto
