### ISSUE TITLE
Testes Negociais: Fluxo de Migração e Fluxo de Criação e Envio de Bloco.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#663]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.
-----

**Descreva a solução que você gostaria**

Criar testes negociais para os cenários abaixo:

**Fluxo de Migração:**

- [x] Remover  blocos existentes.

**Fluxo de criação e envio de bloco**

- [x] Incluso de processo concluído em outro bloco.
- [x] Não inclusão de processo já incluso em bloco aberto ou em andamento.
- [x] Não enviar processo com andamento aberto em mais de uma unidade.

-----

**Definição de Feito (D.O.D. - Definition of Done)**

- [x] Evidências dos testes realizados.

**Comment by Mauro1706** [comment]
Em reunião alinhada com @mateussbh @yurioliveiramgi @euviniciusmendonca, foi acordado que a migração referente as releses 3.6.2 para 3.7.0 serão feitas de maneira simplificada, ignorando todos os blocos criados e tramitados na versão 3.6.2.
Ref: https://github.com/pengovbr/mod-sei-pen/pull/670
E nessa mesma tarefa corrigido erro de teste funcional para asserto de mensagem de processo já incluído em outro bloco.
Ref: https://github.com/pengovbr/mod-sei-pen/pull/671

**Comment by amelquia** [comment]
14/10/24 - Planejamento da nova sprint 51.
Issue transferida para a próxima sprint 51 para dar continuidade no processo dos status : Validação técnica.

**Comment by NinetiesPaul** [comment]
Após estudo de código e execução dos testes informo que a task está atendendo as demandas da descrição e que não tenho sugestões de melhorias pra fazer
