### ISSUE TITLE
Branch - Teste funcional bloco.

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#682]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

A fim de agilizar o processo da revisão dos testes negociais da versão 3.7.0 do Tramita e, a fim de evitar conflitos nesses testes, é criar uma branch e  inserir  todos os testes que já estão prontos.

Criar uma branch 
Fazer os merges de  todos os testes que já estão prontos para essa branch.
Corrigir conflitos.
Fazer o teste full.

-----

**Critérios de aceite:**

- [ ] Evidências do trabalho realizado.

-----

**Comment by marvdias** [comment]
Os seguintes testes funcionais foram adicionados:
TramiteBlocoExternoComProcessoNaoMapeadoRecusaTest - #632
TramiteProcessoValidacaoBotaoIncluirTest - #643
TramiteProcessoValidacaoBotoesAposIncluirTest - #643
TramiteBlocoExternoInclusaoTest - #645
TramiteProcessoBlocoDeTramiteRegrasTest - #646
TramiteBlocoExternoInclusaoDeProcessoPorVisualizacaoDetalhadaTest - #654
ProcessoBlocoDeTramiteTravasDeTramitacaoTest - #655
TramiteBlocoExternoUnidadeTest - #656
TramiteBlocoDeTramiteSituacaoProcessoTest - #659
TramiteBlocoExternoInclusaoDeProcessoEmBlocoComHipoteseLegalNaoMapeadaTest - #661
TramiteProcessoSemDadosBlocoDeTramiteTest - #647
TramiteBlocoExternoEstadoProcessosTest - #653
TramiteProcessoBlocoDeTramitePermissoesTest - #657
TramiteBlocoDeTramiteSituacaoProcessoConcluidoTest - #658
