### ISSUE TITLE
Erro  SQL - migração versão 3.6.2 para versão 3.7.0

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#689]
**Descreva o erro**
O erro ocorre quando sobe o Tramita versão 3.6.2 e tenta migrar para a versão 3.7.0, utilizando a versão do SEI 4.0.12.15,utilizando o banco de dados SQL

-----

**Para reproduzir**
Passos para reproduzir o comportamento:

Tramita versão 3.6.2
Migrar para a versão 3.7.0
Versão SEI : 4.0.12.15
Banco de Dados - SQL
Veja o erro

----

**Log de Erros**

mateus@mateus-Vostro-5320:~/sei/FonteSEI/modulos/mod-sei-pen (release/3.7.0)$ make install

Testando se a pagina de login responde para o org1...
Tentativa 1/15
Página de login encontrada!
Testando se a pagina de login responde para o org2...
Tentativa 1/15
Página de login encontrada!
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env up -d	
funcional_smtp_1 is up-to-date
Starting funcional_php-test-unit_1 ... 
funcional_org2-memcached_1 is up-to-date
funcional_org1-database_1 is up-to-date
funcional_org2-database_1 is up-to-date
funcional_org1-memcached_1 is up-to-date
funcional_org2-http_1 is up-to-date
funcional_org1-http_1 is up-to-date
funcional_proxy_1 is up-to-date
Starting funcional_php-test-unit_1       ... done
Starting funcional_php-test-functional_1 ... done
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env exec org1-http bash -c "printenv | sed 's/^\(.*\)$/export \1/g' > /root/crond_env.sh"
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env exec org1-http chown -R root:root /etc/cron.d/
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env exec org1-http chmod 0644 /etc/cron.d/sei
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env exec org1-http chmod 0644 /etc/cron.d/sip
docker-compose -f tests_super/funcional/docker-compose.yml --env-file tests_super/funcional/.env exec -w /opt/sei/scripts/mod-pen org1-http bash -c "echo -ne 'sei_user\nsei_user\n' | php sei_atualizar_versao_modulo_pen.php"
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
00001 - Integra��o Tramita GOV.BR - INICIANDO ATUALIZACAO (VERSAO INSTALADA 3.6.2)
00001 - [InfraRN->__call] PenAtualizarSeiRN.atualizarVersao
00001 - INICIANDO ATUALIZACAO DO MODULO TRAMITA GOV.BR NO SEI 4.0.12.15
00002 - [InfraParametro->getStrValor] ID_USUARIO_SEI
00003 - [InfraRN->__call] InfraParametroRN.consultar
00004 - [InfraSqlServer->consultarSql] SELECT infra_parametro.valor FROM infra_parametro WHERE infra_parametro.nome=?

Bind:
0: ID_USUARIO_SEI

00005 - [InfraSqlServer->consultarSql] 1 registro(s)
00006 - [InfraSqlServer->consultarSql] 0 s
00007 - [InfraRN->__call] UsuarioRN.consultarRN0489
00008 - [InfraCache->conectar] Memcache memcached:11211
00009 - [InfraCache->getAtributo] INFRA_RA
00010 - [InfraSqlServer->consultarSql] SELECT usuario.id_usuario AS idusuario,usuario.id_origem AS idorigem,usuario.sigla,usuario.nome,usuario.id_orgao AS idorgao,orgao.sigla AS siglaorgao,orgao.descricao AS descricaoorgao FROM usuario  INNER JOIN orgao  ON usuario.id_orgao=orgao.id_orgao WHERE usuario.id_usuario=?

Bind:
0: 1

00011 - [InfraSqlServer->consultarSql] 1 registro(s)
00012 - [InfraSqlServer->consultarSql] 0 s
00013 - [InfraRN->__call] OrgaoRN.consultarRN1352
00014 - [InfraSqlServer->consultarSql] SELECT orgao.id_orgao AS idorgao,orgao.descricao FROM orgao WHERE orgao.sigla=?

Bind:
0: ABC

00015 - [InfraSqlServer->consultarSql] 1 registro(s)
00016 - [InfraSqlServer->consultarSql] 0 s
00017 - [InfraParametro->isSetStrValor] SEI_ID_SISTEMA
00018 - [InfraRN->__call] InfraParametroRN.consultar
00019 - [InfraSqlServer->consultarSql] SELECT infra_parametro.valor FROM infra_parametro WHERE infra_parametro.nome=?

Bind:
0: SEI_ID_SISTEMA

00020 - [InfraSqlServer->consultarSql] 1 registro(s)
00021 - [InfraSqlServer->consultarSql] 0 s
00022 - [InfraParametro->getStrValor] SEI_ID_SISTEMA
00023 - [InfraRN->__call] InfraParametroRN.consultar
00024 - [InfraSqlServer->consultarSql] SELECT infra_parametro.valor FROM infra_parametro WHERE infra_parametro.nome=?

Bind:
0: SEI_ID_SISTEMA

00025 - [InfraSqlServer->consultarSql] 1 registro(s)
00026 - [InfraSqlServer->consultarSql] 0 s
00027 - [InfraParametro->getStrValor] ID_UNIDADE_TESTE
00028 - [InfraRN->__call] InfraParametroRN.consultar
00029 - [InfraSqlServer->consultarSql] SELECT infra_parametro.valor FROM infra_parametro WHERE infra_parametro.nome=?

Bind:
0: ID_UNIDADE_TESTE

00030 - [InfraSqlServer->consultarSql] 1 registro(s)
00031 - [InfraSqlServer->consultarSql] 0 s
00032 - [InfraRN->__call] UnidadeRN.consultarRN0125
00033 - [InfraSqlServer->consultarSql] SELECT unidade.id_unidade AS idunidade,unidade.id_origem AS idorigem,unidade.sigla,unidade.id_orgao AS idorgao,orgao.sigla AS siglaorgao,orgao.descricao AS descricaoorgao FROM unidade  INNER JOIN orgao  ON unidade.id_orgao=orgao.id_orgao WHERE unidade.id_unidade=?

Bind:
0: 110000001

00034 - [InfraSqlServer->consultarSql] 1 registro(s)
00035 - [InfraSqlServer->consultarSql] 0 s
00036 - [InfraSqlServer->consultarSql] select lower(name) as table_name from sys.tables where lower(name) not in ('dtproperties') and lower(name)='pen_sei_teste' order by name asc
00037 - [InfraSqlServer->consultarSql] 0 registro(s)
00038 - [InfraSqlServer->consultarSql] 0.002 s
00039 - [InfraSqlServer->executar] CREATE TABLE pen_sei_teste (id integer null)
00040 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00041 - [InfraSqlServer->executar] 0.002 s
00042 - [InfraSqlServer->executar] DROP TABLE pen_sei_teste
00043 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00044 - [InfraSqlServer->executar] 0.002 s
00045 - [InfraParametro->getStrValor] VERSAO_MODULO_PEN
00046 - [InfraRN->__call] InfraParametroRN.consultar
00047 - [InfraSqlServer->consultarSql] SELECT infra_parametro.valor FROM infra_parametro WHERE infra_parametro.nome=?

Bind:
0: VERSAO_MODULO_PEN

00048 - [InfraSqlServer->consultarSql] 1 registro(s)
00049 - [InfraSqlServer->consultarSql] 0 s
00050 - CRIANDO TABELA DE CONFIGURACAO PARA RESTRICAO 
00051 - [InfraSqlServer->consultarSql] select lower(name) as table_name from sys.tables where lower(name) not in ('dtproperties') and lower(name)='md_pen_uni_restr' order by name asc
00052 - [InfraSqlServer->consultarSql] 0 registro(s)
00053 - [InfraSqlServer->consultarSql] 0.014 s
00054 - [InfraSqlServer->executar] CREATE TABLE md_pen_uni_restr (id bigint NOT NULL, id_unidade integer NOT NULL, id_unidade_rh bigint NOT NULL, id_unidade_restricao bigint NULL, nome_unidade_restricao varchar(255) NULL, id_unidade_rh_restricao bigint NULL, nome_unidade_rh_restricao varchar(255) NULL)
00055 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00056 - [InfraSqlServer->executar] 0.003 s
00057 - [InfraSqlServer->consultarSql] select lower(constraint_name) as constraint_name, lower(constraint_type) as constraint_type, lower(table_name) as table_name from INFORMATION_SCHEMA.TABLE_CONSTRAINTS where lower(constraint_type) <> 'unique' and lower(table_name)='md_pen_uni_restr' order by table_name, constraint_name
00058 - [InfraSqlServer->consultarSql] 0 registro(s)
00059 - [InfraSqlServer->consultarSql] 0.023 s
00060 - [InfraSqlServer->executar] alter table md_pen_uni_restr add constraint pk_md_pen_uni_restr primary key (id)
00061 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00062 - [InfraSqlServer->executar] 0.004 s
00063 - [InfraSqlServer->consultarSql] select lower(constraint_name) as constraint_name, lower(constraint_type) as constraint_type, lower(table_name) as table_name from INFORMATION_SCHEMA.TABLE_CONSTRAINTS where lower(constraint_type) <> 'unique' and lower(table_name)='md_pen_uni_restr' order by table_name, constraint_name
00064 - [InfraSqlServer->consultarSql] 1 registro(s)
00065 - [InfraSqlServer->consultarSql] 0.007 s
00066 - [InfraSqlServer->executar] alter table md_pen_uni_restr add constraint fk_md_pen_uni_restr_unidade foreign key (id_unidade) references unidade (id_unidade)
00067 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00068 - [InfraSqlServer->executar] 0.003 s
00069 - [InfraSqlServer->consultarSql] select max(id) as total from md_pen_uni_restr
00070 - [InfraSqlServer->consultarSql] 1 registro(s)
00071 - [InfraSqlServer->consultarSql] 0.001 s
00072 - [InfraSqlServer->criarSequencialNativa]
00073 - [InfraSqlServer->executar] create table md_pen_seq_uni_restr (id int identity(1,1), campo char(1) null)
00074 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00075 - [InfraSqlServer->executar] 0.002 s
00076 - [InfraRN->__call] InfraSequenciaRN.listar
00077 - [InfraSqlServer->consultarSql] SELECT infra_sequencia.nome_tabela AS nome FROM infra_sequencia WHERE infra_sequencia.nome_tabela=?

Bind:
0: md_pen_uni_restr

00078 - [InfraSqlServer->consultarSql] 0 registro(s)
00079 - [InfraSqlServer->consultarSql] 0.001 s
00080 - [InfraRN->__call] InfraSequenciaRN.excluir
00081 - [InfraSqlServer->abrirTransacao] InfraSqlServer-org1-database-1433-sei-sei_user
00082 - [InfraSqlServer->confirmarTransacao] InfraSqlServer-org1-database-1433-sei-sei_user
00083 - [InfraSqlServer->consultarSql] SELECT COUNT(*) AS total  FROM infra_agendamento_tarefa WHERE infra_agendamento_tarefa.comando=?

Bind:
0: PENAgendamentoRN::processarTarefasPEN

00084 - [InfraSqlServer->consultarSql] 1 registro(s)
00085 - [InfraSqlServer->consultarSql] 0.001 s
00086 - [InfraSqlServer->consultarSql] SELECT infra_agendamento_tarefa.sin_ativo AS sinativo,infra_agendamento_tarefa.comando,infra_agendamento_tarefa.id_infra_agendamento_tarefa AS idinfraagendamentotarefa,infra_agendamento_tarefa.descricao,infra_agendamento_tarefa.sta_periodicidade_execucao AS staperiodicidadeexecucao,infra_agendamento_tarefa.periodicidade_complemento AS periodicidadecomplemento,infra_agendamento_tarefa.parametro,infra_agendamento_tarefa.dth_ultima_execucao AS ultimaexecucao,infra_agendamento_tarefa.dth_ultima_conclusao AS ultimaconclusao,infra_agendamento_tarefa.sin_sucesso AS sinsucesso,infra_agendamento_tarefa.email_erro AS emailerro FROM infra_agendamento_tarefa WHERE infra_agendamento_tarefa.comando=?

Bind:
0: PENAgendamentoRN::processarTarefasPEN

00087 - [InfraSqlServer->consultarSql] 1 registro(s)
00088 - [InfraSqlServer->consultarSql] 0.001 s
00089 - [InfraSqlServer->executar] DELETE FROM infra_agendamento_tarefa WHERE infra_agendamento_tarefa.id_infra_agendamento_tarefa=?

Bind:
0: 12

00090 - [InfraSqlServer->executar] 1 registro(s) afetado(s)
00091 - [InfraSqlServer->executar] 0.002 s
00092 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column id_repositorio_destino integer NULL
00093 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00094 - [InfraSqlServer->executar] 0.002 s
00095 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column str_repositorio_destino varchar(250) NULL
00096 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00097 - [InfraSqlServer->executar] 0.002 s
00098 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column id_repositorio_origem integer NULL
00099 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00100 - [InfraSqlServer->executar] 0.002 s
00101 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column id_unidade_origem integer NULL
00102 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00103 - [InfraSqlServer->executar] 0.002 s
00104 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column id_unidade_destino integer NULL
00105 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00106 - [InfraSqlServer->executar] 0.002 s
00107 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column str_unidade_destino varchar(250) NULL
00108 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00109 - [InfraSqlServer->executar] 0.002 s
00110 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column id_usuario integer NULL
00111 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00112 - [InfraSqlServer->executar] 0.003 s
00113 - [InfraSqlServer->executar] alter table md_pen_expedir_lote alter column id_unidade integer NULL
00114 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00115 - [InfraSqlServer->executar] 0.003 s
00116 - [InfraSqlServer->executar] alter table md_pen_rel_expedir_lote drop constraint fk_md_pen_rel_expedir_lote
00117 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00118 - [InfraSqlServer->executar] 0.003 s
00119 - [InfraSqlServer->consultarSql] SELECT lower(column_name) as column_name, is_nullable as is_nullable, lower(data_type) as data_type, character_maximum_length as character_maximum_length , numeric_precision as numeric_precision, numeric_scale as numeric_scale
          FROM INFORMATION_SCHEMA.COLUMNS
          where lower(table_name)='md_pen_expedir_lote' order by ordinal_position asc
00120 - [InfraSqlServer->consultarSql] 10 registro(s)
00121 - [InfraSqlServer->consultarSql] 0.013 s
00122 - [InfraSqlServer->executar] SP_RENAME 'md_pen_expedir_lote.id_lote', 'id_bloco_processo', 'COLUMN'
00123 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add dth_atualizado datetime NULL
00124 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00125 - [InfraSqlServer->executar] 0.003 s
00126 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add dth_envio datetime NULL
00127 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00128 - [InfraSqlServer->executar] 0.002 s
00129 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add id_protocolo bigint NULL
00130 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00131 - [InfraSqlServer->executar] 0.003 s
00132 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add id_bloco integer NULL
00133 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00134 - [InfraSqlServer->executar] 0.002 s
00135 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add sequencia integer NULL
00136 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00137 - [InfraSqlServer->executar] 0.002 s
00138 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add id_andamento integer NULL
00139 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00140 - [InfraSqlServer->executar] 0.003 s
00141 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add id_atividade_expedicao varchar(4000) NULL
00142 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00143 - [InfraSqlServer->executar] 0.003 s
00144 - [InfraSqlServer->executar] alter table md_pen_expedir_lote add tentativas integer NULL
00145 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00146 - [InfraSqlServer->executar] 0.002 s
00147 - [InfraSqlServer->executar] alter table md_pen_expedir_lote drop constraint fk_bloco_protocolo
00148 - [InfraSqlServer->executar] alter table md_pen_rel_expedir_lote drop constraint fk_md_pen_rel_expedir_lote
00149 - [InfraSqlServer->executar] alter table md_pen_bloco_protocolo drop constraint fk_bloco_protocolo
00150 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00151 - [InfraSqlServer->executar] 0.002 s
00152 - [InfraSqlServer->consultarSql] select lower(name) as table_name from sys.tables where lower(name) not in ('dtproperties') and lower(name)='md_pen_expedir_lote' order by name asc
00153 - [InfraSqlServer->consultarSql] 1 registro(s)
00154 - [InfraSqlServer->consultarSql] 0.002 s
00155 - [InfraSqlServer->executar] sp_rename 'md_pen_expedir_lote', 'md_pen_bloco_processo'
00156 - [InfraSqlServer->consultarSql] select lower(constraint_name) as constraint_name, lower(constraint_type) as constraint_type, lower(table_name) as table_name from INFORMATION_SCHEMA.TABLE_CONSTRAINTS where lower(constraint_type) <> 'unique' and lower(table_name)='md_pen_bloco_processo' order by table_name, constraint_name
00157 - [InfraSqlServer->consultarSql] 3 registro(s)
00158 - [InfraSqlServer->consultarSql] 0.022 s
00159 - [InfraSqlServer->executar] alter table md_pen_bloco_processo add constraint fk_md_pen_bloco_proc_procedi foreign key (id_protocolo) references protocolo (id_protocolo)
00160 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00161 - [InfraSqlServer->executar] 0.005 s
00162 - [InfraSqlServer->consultarSql] select lower(constraint_name) as constraint_name, lower(constraint_type) as constraint_type, lower(table_name) as table_name from INFORMATION_SCHEMA.TABLE_CONSTRAINTS where lower(constraint_type) <> 'unique' and lower(table_name)='md_pen_bloco_processo' order by table_name, constraint_name
00163 - [InfraSqlServer->consultarSql] 4 registro(s)
00164 - [InfraSqlServer->consultarSql] 0.012 s
00165 - [InfraSqlServer->executar] alter table md_pen_bloco_processo add constraint fk_md_pen_bloco_processo_bl foreign key (id_bloco) references md_pen_bloco (id)
00166 - [InfraSqlServer->executar] -1 registro(s) afetado(s)
00167 - [InfraSqlServer->executar] 0.006 s
00168 - [InfraSqlServer->executar] alter table md_pen_bloco add ordem integer NOT NULL
Descri��o:
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'ordem' cannot be added to non-empty table 'md_pen_bloco' because it does not satisfy these conditions.

Mensagem:
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'ordem' cannot be added to non-empty table 'md_pen_bloco' because it does not satisfy these conditions.

Trilha de Processamento:
#0 /opt/infra/infra_php/InfraScriptVersao.php(235): InfraScript->processarErro('ERRO ATUALIZAND...', Object(InfraException))
#1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(3106): InfraScriptVersao->atualizarVersao()
#2 {main}

Detalhes:
alter table md_pen_bloco add ordem integer NOT NULL

Trilha de Processamento Original:
\n0 /opt/infra/infra_php/InfraMetaBD.php(776): InfraSqlServer->executarSql('alter table md_...')
\n1 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2904): InfraMetaBD->adicionarColuna('md_pen_bloco', 'ordem', 'integer', 'NOT NULL')
\n2 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(285): PenAtualizarSeiRN->instalarV3070()
\n3 /opt/infra/infra_php/InfraRN.php(149): PenAtualizarSeiRN->atualizarVersaoConectado()
\n4 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(45): InfraRN->__call('atualizarVersao', Array)
\n5 /opt/infra/infra_php/InfraScriptVersao.php(394): VersaoSei4RN->atualizarVersaoCompatibilidade('3.6.2')
\n6 /opt/infra/infra_php/InfraRN.php(151): InfraScriptVersao->atualizarVersaoInternoConectado(Object(BancoSEI))
\n7 /opt/infra/infra_php/InfraScriptVersao.php(233): InfraRN->__call('atualizarVersao...', Array)
\n8 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(3106): InfraScriptVersao->atualizarVersao()
\n9 {main}

make: *** [Makefile:147: install] Error 1

**Comment by marvdias** [comment]
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/691
