### ISSUE TITLE
Testes de Compatibilidade -Tramita 3.7.0 x SEI 4.1.3 e 4.1.4 (TRF4).  

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#705]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Verificar a compatibilidade da nova versão 3.7.0 do Tramita com as versões do SEI 4.1.3 e 4.1.4 do TRF4.

-----

**Critérios de aceitação:**

Executar os testes de compatibilidade nas versões 4.1.3 e 4.1.4  nos bancos de dados abaixo:

- [x] MySql
- [x] SQL Server
- [x] Oracle
- [x] PostgreSQL

**Definição de Feito (D.O.D. - Definition of Done)**

  - [x] Envio dos arquivos do SEI 4.1.3 e 4.1.4 do TRF4 para montagem do ambiente.

**Definição de Pronto  (D.O.R. - Definition of Ready)**

  - [ ] Evidência dos testes realizados.

-------

**Comment by amelquia** [comment]
11/11/24
@NinetiesPaul trabalhando nos testes de compatibilidade da versão do SEI 4.1.3.
@marvdias  trabalhando nos testes de compatibilidade da versão do SEI 4.1.4.

**Comment by marvdias** [comment]
Testes realizados com sucesso na versão SEI 4.1.4 para os bancos mysql e postgresql.
PR #706 faz a correção do script de instalação para o bd postgresql.

**Comment by NinetiesPaul** [comment]
Finalizado os testes com a versão do 4.1.3 TRF em cada banco de dados possivel

Evidencia MySQL
[4.1.3 mysql.txt](https://github.com/user-attachments/files/17717008/4.1.3.mysql.txt)

Evidencia Oracle
[4.1.3 oracle.txt](https://github.com/user-attachments/files/17717009/4.1.3.oracle.txt)

Evidencia PostgreSQL
[4.1.3 postgres.txt](https://github.com/user-attachments/files/17717010/4.1.3.postgres.txt)

Evidencia SQL Server
[4.1.3 sqlserver.txt](https://github.com/user-attachments/files/17717011/4.1.3.sqlserver.txt)

Alguns testes falharam por timeout e falsos positivos, porém é um comportamento que tambem pode ser observado nas versões não-TRF do SEI, conforme evidências na issue #685 . Apesar das falhas, quando rodado de forma avulsa os testes em questão passam sem erros, apenas ocorrendo na execução completa dos testes.
