### ISSUE TITLE
Testes Unitários  - Consultar Estrutura

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#714]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**

Não.

-----

**Descreva a solução que você gostaria**

Executar testes unitários para o método **Consultar Estrutura.**

-----

**Critérios de aceite:**

- [ ] Configurar o ambiente de testes, incluindo dependências e mocks necessários.
- [ ] Casos de sucesso (retorno esperado).
- [ ] Casos de erro (tratamento de exceções).

**Definição de Feito (D.O.D. - Definition of Done)**

- [ ] Evidências dos testes realizados.

-----

**Links úteis**

https://homolog.api.processoeletronico.gov.br/swagger/swagger-ui/index.html#/

-----

**Comment by sergioadao** [comment]
Bom dia @amelquia, @Mauro1706  e @mateussbh ....segue evidência do funcionamento do teste:

**$make test-unit teste=ProcessoEletronicoRN/ConsultarEstruturasTest**
**$ make test-unit teste=ProcessoEletronicoRN/ConsultarEstruturaTest**

RESULTADO: 4.0.12.15 ====> OK


Ambiente utilizado foi :

       SEI 4.1.2 
       Branch: feat/rest

==================================================

**$ make test-unit teste=ProcessoEletronicoRN/ConsultarEstruturasTest**
docker compose -f tests_super/funcional/docker-compose.yml run --rm -w /tests php-test-unit bash -c 'XDEBUG_MODE=coverage vendor/bin/phpunit --testdox --coverage-html html rn/ProcessoEletronicoRN/ConsultarEstruturasTest.php'
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad-4.0.12.15/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
PHPUnit 9.6.21 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

Consultar Estruturas
 ✔ Consultar estrutura lista sucesso  43 ms
 ✔ Consultar estrutura lista lanca excecao  5 ms

Time: 00:01.748, Memory: 36.00 MB

OK (2 tests, 5 assertions)

Generating code coverage report in Cobertura XML format ... done [00:14.823]

Generating code coverage report in HTML format ... done [00:03.163]

==================================================================
![image](https://github.com/user-attachments/assets/6eebf61b-ebb5-46ae-ac63-1c1ec4df065a)


==============================================================================
==============================================================================


**$ make test-unit teste=ProcessoEletronicoRN/ConsultarEstruturaTest**
docker compose -f tests_super/funcional/docker-compose.yml run --rm -w /tests php-test-unit bash -c 'XDEBUG_MODE=coverage vendor/bin/phpunit --testdox --coverage-html html rn/ProcessoEletronicoRN/ConsultarEstruturaTest.php'
WARN[0000] /home/toor/Documentos/ministerio_economia/aplicacao_sei/sei_versoes/sei-trad-4.0.12.15/src/sei/web/modulos/mod-sei-pen/tests_super/funcional/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
PHPUnit 9.6.21 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

Consultar Estrutura
 ✔ Consultar estrutura lista sucesso  44 ms
 ✔ Consultar estrutura lista bol retorno raw true sucesso  2 ms
 ✔ Consultar estrutura lista lanca excecao  5 ms

Time: 00:01.578, Memory: 36.00 MB

OK (3 tests, 7 assertions)

Generating code coverage report in Cobertura XML format ... done [00:13.552]

Generating code coverage report in HTML format ... done [00:02.916]


====================================================================

![image](https://github.com/user-attachments/assets/677b3e78-0b33-41ea-a54c-afc6a18a495a)

**Comment by sergioadao** [comment]
Boa tarde @amelquia, @Mauro1706 e @mateussbh ....segue evidência do funcionamento correto do teste:

$ make test-unit test-ProcessoEletronicoRN/ListarRepositorioTest

**Ambiente utilizado foi :

   SEI 4.1.2 
   Branch: feat/rest
   BANCO SQLSERVER**
=========================================================================
RESULTADO: OK

PHPUnit 9.6.22 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.28 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

Consultar Estrutura
 ✔ Consultar estrutura lista sucesso  46 ms
 ✔ Consultar estrutura lista bol retorno raw true sucesso  2 ms
 ✔ Consultar estrutura lista lanca excecao  5 ms

Time: 00:01.603, Memory: 36.00 MB

OK (3 tests, 7 assertions)

Generating code coverage report in HTML format ... done [00:18.455]

**Comment by sergioadao** [comment]
Boa tarde @amelquia, e @mateussbh ....segue evidência do funcionamento correto do teste:

$ make test-unit test-ProcessoEletronicoRN/ListarRepositorioTest

**Ambiente utilizado foi :

   SEI 4.1.2 
   Branch: feat/rest
   BANCO SQLSERVER**
=========================================================================
RESULTADO: OK

PHPUnit 9.6.22 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.28 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

Consultar Estrutura
 ✔ Consultar estrutura lista sucesso  46 ms
 ✔ Consultar estrutura lista bol retorno raw true sucesso  2 ms
 ✔ Consultar estrutura lista lanca excecao  5 ms

Time: 00:01.603, Memory: 36.00 MB

OK (3 tests, 7 assertions)

Generating code coverage report in HTML format ... done [00:18.455]

**Comment by sergioadao** [comment]
Boa tarde @amelquia, @Mauro1706 e @mateussbh ....segue evidência do funcionamento correto do teste:

$make test-unit teste=ProcessoEletronicoRN/ConsultarEstruturaTest

**Ambiente utilizado foi :

SEI 4.0.12.15
Branch: feat/rest
BANCO SQLSERVER
============================================================================
RESULTADO: OK
HPUnit 9.6.21 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.33 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

Consultar Estrutura
 ✔ Consultar estrutura lista sucesso  43 ms
 ✔ Consultar estrutura lista bol retorno raw true sucesso  2 ms
 ✔ Consultar estrutura lista lanca excecao  5 ms

Time: 00:01.566, Memory: 36.00 MB

OK (3 tests, 7 assertions)

Generating code coverage report in Cobertura XML format ... done [00:13.980]

Generating code coverage report in HTML format ... done [00:03.807]
